async function Vips(moduleArg={}){var moduleRtn;var n=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=!!globalThis.Deno;aa||=ca;var q=ba&&self.name?.startsWith("em-pthread"),da="./this.program",ea=import.meta.url,fa="",ha,ia;
if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ja=console.log.bind(console),r=console.error.bind(console),ka,la,ma=!1,na;class t extends Error{}class oa extends t{}
class pa extends t{constructor(a){super(a);this.Be=a;a=qa(a);this.name=a[0];this.message=a[1]}}var ra,sa,ta;
if(q){var ua=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.ge;if("load"===d){let e=[];self.onmessage=f=>e.push(f);ta=()=>{postMessage({ge:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Kf)if(!n[f]||n[f].proxy)n[f]=(...g)=>{postMessage({ge:"callHandler",Jf:f,tf:g})},"print"==f&&(ja=n[f]),"printErr"==f&&(r=n[f]);va=c.ig;wa();la=c.jg;xa();ya()}else if("run"===d){za(c.ce);Aa(c.ce,0,0,1,0,0);Ba();Ca(c.ce);ua||(Da(),ua=!0);try{Ea(c.fg,c.Je)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ua&&Fa():d&&(r(`worker: received unknown command ${d}`),r(c)))}catch(e){throw Ga(),e;}}self.onmessage=a}var v,w,y,B,C,D,Ha,Ia,E,Ja,Ka=!1,La=!1;function wa(){var a=va.buffer;v=new Int8Array(a);y=new Int16Array(a);w=new Uint8Array(a);B=new Uint16Array(a);C=new Int32Array(a);D=new Uint32Array(a);Ha=new Float32Array(a);Ia=new Float64Array(a);E=new BigInt64Array(a);Ja=new BigUint64Array(a)}
function Ma(){Ka=!0;q?ta():(n.noFSInit||FS.Me||FS.init(),Na.Lc(),Oa(Pa),FS.gf=!1)}function H(a){n.onAbort?.(a);a="Aborted("+a+")";r(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");sa?.(a);throw a;}var Qa;async function Ra(a){if(!ka)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Qa&&ka)a=new Uint8Array(ka);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Sa(a,b){try{var c=await Ra(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),H(d)}}async function Ta(a){var b=Qa;if(!ka)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return Sa(b,a)}
function Ua(){Va={l:Wa,J:Xa,V:Ya,b:Za,j:$a,Hc:ab,O:bb,mb:cb,$b:db,f:eb,rc:fb,uc:gb,jb:hb,pc:ib,lc:jb,kc:kb,yc:lb,nc:mb,mc:nb,Ga:ob,Zb:pb,oc:qb,db:rb,vc:sb,Kb:tb,Ta:ub,lb:vb,Ec:wb,R:xb,q:yb,U:zb,o:Ab,G:Bb,Cc:Cb,y:Db,p:Eb,kb:Fb,Z:Gb,_:Hb,H:Ib,Ua:Jb,Dc:Kb,Ha:Lb,Va:Mb,Lb:Nb,Fc:Ob,hc:Pb,Xb:Qb,ac:Rb,_b:Sb,eb:Tb,gc:Ca,qc:Ub,Tb:Vb,tc:Wb,B:Xb,Jb:Yb,N:Zb,ca:$b,Db:ac,S:bc,Gc:cc,A:dc,gb:ec,ra:fc,K:gc,Sa:hc,Kc:ic,Wb:jc,Ac:kc,dc:lc,ec:mc,bc:nc,cc:oc,Ub:pc,xc:qc,sc:rc,fb:sc,X:tc,cb:uc,bb:vc,Yb:wc,$:xc,Ia:yc,Vb:zc,
zc:Ac,Bc,T:Cc,sa:Dc,ic:Ec,ib:Fc,fc:Gc,hb:Hc,nb:Ic,ua:Jc,qa:Kc,C:Lc,pb:Mc,sb:Nc,D:Oc,ta:Pc,Cb:Qc,Eb:Rc,ob:Sc,wa:Tc,I:Uc,u:Vc,Jc:Wc,Ic:Xc,g:Yc,z:Zc,Xa:$c,Ma:ad,xa:bd,i:cd,x:dd,d:ed,w:fd,Mb:gd,t:hd,Rb:jd,Ab:kd,F:ld,ea:md,Wa:nd,ba:od,Sb:pd,Qb:qd,Nb:rd,Pb:sd,Ob:td,v:ud,Ja:vd,W:wd,Ka:xd,vb:yd,Za:zd,oa:Ad,m:Bd,Ib:Cd,la:Dd,Hb:Ed,c:Fd,xb:Gd,fa:Hd,Fa:Id,qb:Jd,P:Kd,Y:Ld,ja:Md,tb:Nd,Pa:Od,Qa:Pd,M:Qd,ya:Rd,Gb:Sd,Na:Ud,h:Vd,ab:Wd,aa:Xd,Aa:Yd,da:Zd,zb:$d,ka:ae,Oa:be,e:ce,$a:de,Ea:ee,pa:fe,Ca:ge,Da:he,yb:ie,Bb:je,
La:ke,n:le,k:me,s:ne,wb:oe,r:pe,Q:qe,E:re,L:se,ma:te,Ba:ue,_a:ve,na:we,Fb:xe,Ya:ye,ha:ze,Ra:Ae,za:Be,ub:Ce,va:De,ga:Ee,rb:Fe,ia:Ge,a:va,wc:He,jc:Ie};return{a:Va}}
async function xa(){function a(d,e){Na=d.exports;Je.push(Na.Yc);d=Na;Ke=d.Mc;Le=d.Nc;Me=n._main=d.Oc;I=d.Pc;Ne=d.Qc;n._calloc=d.Rc;Oe=d.Tc;Pe=d.Uc;Qe=d.Vc;Da=d.Wc;n._emscripten_builtin_free=d.Xc;Re=d.Zc;n._emscripten_builtin_malloc=d._c;Se=d.$c;n.___libc_calloc=d.ad;n.___libc_free=d.bd;n.___libc_malloc=d.cd;Aa=d.dd;Ga=d.ed;Te=d.fd;Ue=d.gd;Ve=d.hd;We=d.id;n._strndup=d.jd;Xe=d.kd;n.__Znaj=d.ld;n.__ZnajSt11align_val_t=d.md;n.__Znwj=d.nd;n.__ZnwjSt11align_val_t=d.od;n.___libc_realloc=d.pd;n._emscripten_builtin_calloc=
d.qd;n._emscripten_builtin_realloc=d.rd;n._malloc_size=d.sd;n._malloc_usable_size=d.td;n._reallocf=d.ud;J=d.vd;Ye=d.wd;Ze=d.xd;L=d.yd;$e=d.zd;N=d.Ad;af=d.Bd;bf=d.Cd;cf=d.Dd;df=d.Sc;la=e;return Na}var b=Ua();if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(q){var c=new WebAssembly.Instance(la,Ua());return a(c,la)}Qa??=n.locateFile?n.locateFile?n.locateFile("vips-es6.wasm",fa):fa+"vips-es6.wasm":(new URL("vips-es6.wasm",import.meta.url)).href;return function(d){return a(d.instance,
d.module)}(await Ta(b))}var ff=a=>{if(!(a instanceof ef||"unwind"==a))throw a;};class ef{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var gf=0,hf=a=>{a.terminate();a.onmessage=()=>{}},Oa=a=>{for(;0<a.length;)a.shift()(n)},jf=[],kf=0,lf=null,mf=()=>{kf--;n.monitorRunDependencies?.(kf);if(0==kf&&lf){var a=lf;lf=null;a()}},nf=()=>{kf++;n.monitorRunDependencies?.(kf)},tf=a=>{0==of.length&&(pf(),qf(of[0]));var b=of.pop();if(!b)return 6;rf.push(b);sf[a.ce]=b;b.ce=a.ce;b.postMessage({ge:"run",fg:a.eg,Je:a.Je,ce:a.ce},a.nf);return 0},of=[],rf=[],Je=[],sf={};
function uf(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)pf();jf.push(async()=>{var b=vf();nf("loading-workers");await b;mf("loading-workers")})}var wf=()=>{for(var a of rf)hf(a);for(a of of)hf(a);of=[];rf=[];sf={}},xf=a=>{var b=a.ce;delete sf[b];of.push(a);rf.splice(rf.indexOf(a),1);a.ce=0;Ue(b)};function Ba(){Je.forEach(a=>a())}
var qf=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.ge;if(g.He&&g.He!=Ke()){var h=sf[g.He];h?h.postMessage(g,g.nf):r(`Internal error! Worker sent a message "${f}" to target pthread ${g.He}, but that thread no longer exists!`)}else if("checkMailbox"===f)Fa();else if("spawnThread"===f)tf(g);else if("cleanupThread"===f)yf(()=>{xf(sf[g.gg])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)n[g.Jf](...g.tf);else f&&r(`worker sent an unknown command ${f}`)};
a.onerror=f=>{r(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&c.push(e);a.postMessage({ge:"load",Kf:c,ig:va,jg:la})});async function vf(){if(!q)return Promise.all(of.map(qf))}
function pf(){if(n.mainScriptUrlOrBlob){var a=n.mainScriptUrlOrBlob;"string"!=typeof a&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("vips-es6.js",import.meta.url),{type:"module",name:"em-pthread"});of.push(a)}var O=(a,b,...c)=>{for(var d=2*c.length,e=N(),f=$e(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(E[g+2*h]=1n,E[g+2*h+1]=k):(E[g+2*h]=0n,Ia[g+2*h+1]=k)}a=Te(a,0,d,f,b);L(e);return a};
function He(a){if(q)return O(0,1,a);na=a;zf||0<gf||(wf(),n.onExit?.(a),ma=!0);throw new ef(a);}function Af(a){if(q)return O(1,0,a);Cc(a)}var Cc=a=>{na=a;if(q)throw Af(a),"unwind";if(!(zf||0<gf||q)){Se();FS.Me=!1;Ne(0);for(var b of FS.streams)b&&FS.close(b);wf();La=!0}He(a)},yf=a=>{if(!La&&!ma)try{if(a(),!(La||zf||0<gf))try{q?Ke()&&Ve(na):Cc(na)}catch(b){ff(b)}}catch(b){ff(b)}},Bf=a=>{gf+=1;setTimeout(()=>{--gf;yf(a)},1E4)},Cf=[],Df=!1;
function Ef(){function a(){Df=document.pointerLockElement===n.canvas}if(!Ff){Ff=!0;Cf.push({canHandle:function(c){return!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Gf(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Gf(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,
0,0);URL.revokeObjectURL(f);g(c)};k.onerror=()=>{r(`Image ${f} could not be decoded`);h()};k.src=f})}});Cf.push({canHandle:function(c){return!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Gf(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){r(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="",m=0,p=0,u=0;u<c.length;u++)for(m=m<<8|c[u],p+=8;6<=p;){var x=m>>p-6&63;p-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==p?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],l+="=="):4==p&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;Bf(()=>{f(k)})})}});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),n.elementPointerLock&&b.addEventListener("click",c=>{!Df&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Gf(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var Hf={},Ff,If=[];function za(a){var b=D[a+52>>2];Ze(b,b-D[a+56>>2]);L(b)}
var Jf=[],P=a=>{var b=Jf[a];b||(Jf[a]=b=df.get(a));return b},Ea=(a,b)=>{zf=gf=0;a=P(a)(b);zf||0<gf?na=a:Ve(a)},zf=!1,va,Kf=new TextDecoder,Lf=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Q=(a,b,c)=>a?Kf.decode(w.slice(a,Lf(w,a,b,c))):"",Wa=(a,b,c,d)=>H(`Assertion failed: ${Q(a)}, at: `+[b?Q(b):"unknown filename",c,d?Q(d):"unknown function"]),Mf=[],Nf=0,Xa=a=>{var b=new Of(a);0==v[b.Id+12]&&(v[b.Id+12]=1,Nf--);v[b.Id+13]=0;Mf.push(b);Pe(a);return cf(a)},Pf=0,Ya=()=>{J(0,0);var a=
Mf.pop();Oe(a.Be);Pf=0};class Of{constructor(a){this.Be=a;this.Id=a-24}init(a,b){D[this.Id+16>>2]=0;D[this.Id+4>>2]=a;D[this.Id+8>>2]=b}}
var Qf=a=>{var b=Pf?.Be;if(!b)return Ye(0),0;var c=new Of(b);D[c.Id+16>>2]=b;var d=D[c.Id+4>>2];if(!d)return Ye(0),b;for(var e of a){if(0===e||e===d)break;if(bf(e,d,c.Id+16))return Ye(e),b}Ye(d);return b},Za=()=>Qf([]),$a=a=>Qf([a]),ab=()=>{var a=Mf.pop();a||H("no exception to throw");var b=a.Be;0==v[a.Id+13]&&(Mf.push(a),v[a.Id+13]=1,v[a.Id+12]=0,Nf++);Pf=new pa(b);throw Pf;},bb=(a,b,c)=>{(new Of(a)).init(b,c);Pf=new pa(a);Nf++;throw Pf;},cb=()=>Nf;
function Rf(a,b,c,d){return q?O(2,1,a,b,c,d):db(a,b,c,d)}
var db=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(q&&0===e.length)return Rf(a,b,c,d);a={eg:c,ce:a,Je:d,nf:e};return q?(a.ge="spawnThread",postMessage(a,e),0):tf(a)},eb=a=>{Pf||=new pa(a);throw Pf;},Sf=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Tf=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Sf(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=
".");a&&c&&(a+="/");return(b?"/":"")+a},Uf=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Vf=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Wf=(a,b)=>Tf(a+"/"+b),Xf=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),Yf=a=>{(Yf=Xf())(a)},Zf=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sf(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$f=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=Zf(a).slice(1);b=Zf(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},ag=a=>{var b=
Lf(a,0);return Kf.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(0,b):a.slice(0,b):new Uint8Array(a.slice(0,b)))},bg=[],cg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},dg=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=
224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},eg=a=>{var b=Array(cg(a)+1);a=dg(a,b,0,b.length);b.length=a;return b},fg=[];function gg(a,b){fg[a]={input:[],output:[],ke:b};FS.registerDevice(a,hg)}
var hg={open(a){var b=fg[a.node.xe];if(!b)throw new FS.Ed(43);a.Nd=b;a.seekable=!1},close(a){a.Nd.ke.De(a.Nd)},De(a){a.Nd.ke.De(a.Nd)},read(a,b,c,d){if(!a.Nd||!a.Nd.ke.ff)throw new FS.Ed(60);for(var e=0,f=0;f<d;f++){try{var g=a.Nd.ke.ff(a.Nd)}catch(h){throw new FS.Ed(29);}if(void 0===g&&0===e)throw new FS.Ed(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.fe=Date.now());return e},write(a,b,c,d){if(!a.Nd||!a.Nd.ke.Re)throw new FS.Ed(60);try{for(var e=0;e<d;e++)a.Nd.ke.Re(a.Nd,b[c+e])}catch(f){throw new FS.Ed(29);
}d&&(a.node.Wd=a.node.Vd=Date.now());return e}},ig={ff(){a:{if(!bg.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}bg=eg(a)}a=bg.shift()}return a},Re(a,b){null===b||10===b?(ja(ag(a.output)),a.output=[]):0!=b&&a.output.push(b)},De(a){0<a.output?.length&&(ja(ag(a.output)),a.output=[])},Nf(){return{pg:25856,rg:5,og:191,qg:35387,ng:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Of(){return 0},Pf(){return[24,
80]}},jg={Re(a,b){null===b||10===b?(r(ag(a.output)),a.output=[]):0!=b&&a.output.push(b)},De(a){0<a.output?.length&&(r(ag(a.output)),a.output=[])}},kg=a=>{a=65536*Math.ceil(a/65536);var b=Re(65536,a);b&&w.fill(0,b,b+a);return b},R={be:null,mount(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.Ed(63);R.be||(R.be={dir:{node:{Zd:R.Gd.Zd,ae:R.Gd.ae,pe:R.Gd.pe,ie:R.Gd.ie,rename:R.Gd.rename,unlink:R.Gd.unlink,rmdir:R.Gd.rmdir,
ye:R.Gd.ye,symlink:R.Gd.symlink},stream:{llseek:R.Hd.llseek}},file:{node:{Zd:R.Gd.Zd,ae:R.Gd.ae},stream:{llseek:R.Hd.llseek,read:R.Hd.read,write:R.Hd.write,qe:R.Hd.qe,se:R.Hd.se}},link:{node:{Zd:R.Gd.Zd,ae:R.Gd.ae,readlink:R.Gd.readlink},stream:{}},Ze:{node:{Zd:R.Gd.Zd,ae:R.Gd.ae},stream:FS.vf}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.Gd=R.be.dir.node,c.Hd=R.be.dir.stream,c.Jd={}):FS.isFile(c.mode)?(c.Gd=R.be.file.node,c.Hd=R.be.file.stream,c.Qd=0,c.Jd=null):FS.isLink(c.mode)?(c.Gd=R.be.link.node,
c.Hd=R.be.link.stream):FS.isChrdev(c.mode)&&(c.Gd=R.be.Ze.node,c.Hd=R.be.Ze.stream);c.fe=c.Wd=c.Vd=Date.now();a&&(a.Jd[b]=c,a.fe=a.Wd=a.Vd=c.fe);return c},yg(a){return a.Jd?a.Jd.subarray?a.Jd.subarray(0,a.Qd):new Uint8Array(a.Jd):new Uint8Array(0)},Gd:{Zd(a){var b={};b.xf=FS.isChrdev(a.mode)?a.id:1;b.Mf=a.id;b.mode=a.mode;b.Sf=1;b.uid=0;b.If=0;b.xe=a.xe;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.Qd:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.fe=new Date(a.fe);b.Wd=new Date(a.Wd);
b.Vd=new Date(a.Vd);b.uf=4096;b.Ye=Math.ceil(b.size/b.uf);return b},ae(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Qd!=b&&(0==b?(a.Jd=null,a.Qd=0):(c=a.Jd,a.Jd=new Uint8Array(b),c&&a.Jd.set(c.subarray(0,Math.min(b,a.Qd))),a.Qd=b)))},pe(){R.Ke||(R.Ke=new FS.Ed(44),R.Ke.stack="<generic error, no stack>");throw R.Ke;},ie(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=lg(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.Jd)throw new FS.Ed(55);
mg(d)}delete a.parent.Jd[a.name];b.Jd[c]=a;a.name=c;b.Vd=b.Wd=a.parent.Vd=a.parent.Wd=Date.now()},unlink(a,b){delete a.Jd[b];a.Vd=a.Wd=Date.now()},rmdir(a,b){var c=lg(a,b),d;for(d in c.Jd)throw new FS.Ed(55);delete a.Jd[b];a.Vd=a.Wd=Date.now()},ye(a){return[".","..",...Object.keys(a.Jd)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.Ed(28);return a.link}},Hd:{read(a,b,c,d,e){var f=a.node.Jd;if(e>=a.node.Qd)return 0;a=Math.min(a.node.Qd-
e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.Wd=a.Vd=Date.now();if(b.subarray&&(!a.Jd||a.Jd.subarray)){if(f)return a.Jd=b.subarray(c,c+d),a.Qd=d;if(0===a.Qd&&0===e)return a.Jd=b.slice(c,c+d),a.Qd=d;if(e+d<=a.Qd)return a.Jd.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Jd?a.Jd.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Jd,a.Jd=new Uint8Array(f),0<a.Qd&&a.Jd.set(g.subarray(0,
a.Qd),0));if(a.Jd.subarray&&b.subarray)a.Jd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Jd[e+f]=b[c+f];a.Qd=Math.max(a.Qd,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.Qd);if(0>b)throw new FS.Ed(28);return b},qe(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.Ed(43);a=a.node.Jd;if(e&2||!a||a.buffer!==v.buffer){d=!0;e=kg(b);if(!e)throw new FS.Ed(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);v.set(a,
e)}}else d=!1,e=a.byteOffset;return{Id:e,Xe:d}},se(a,b,c,d){R.Hd.write(a,b,0,d,c,!1);return 0}}},ng=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},og=async a=>{a=await ha(a);return new Uint8Array(a)},pg=async(a,b)=>{"undefined"!=typeof Hf&&Ef();for(var c of Cf)if(c.canHandle(b))return c.handle(a,b);return a},qg=async(a,b,c,d,e,f,g,h)=>{var k=b?Zf(Tf(a+"/"+b)):a,l=`cp ${k}`;nf(l);try{var m=c;"string"==typeof c&&(m=await og(c));m=await pg(m,k);h?.();f||FS.createDataFile(a,b,m,d,e,g)}finally{mf(l)}};
function lg(a,b){var c=FS.isDir(a.mode)?(c=rg(a,"x"))?c:a.Gd.pe?0:2:54;if(c)throw new FS.Ed(c);for(c=FS.je[sg(a.id,b)];c;c=c.re){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.pe(a,b)}function mg(a){var b=sg(a.parent.id,a.name);if(FS.je[b]===a)FS.je[b]=a.re;else for(b=FS.je[b];b;){if(b.re===a){b.re=a.re;break}b=b.re}}function sg(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.je.length}
function tg(a){var b=sg(a.parent.id,a.name);a.re=FS.je[b];FS.je[b]=a}function ug(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function rg(a,b){if(FS.gf)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function vg(a,b){if(!FS.isDir(a.mode))return 54;try{return lg(a,b),20}catch(c){}return rg(a,"wx")}
function wg(a,b,c){try{var d=lg(a,b)}catch(e){return e.Ld}if(a=rg(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.ue(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function xg(a,b){if(!a)throw new FS.Ed(b);return a}function S(a){a=FS.Ff(a);if(!a)throw new FS.Ed(8);return a}function yg(a,b=-1){a=Object.assign(new FS.qf,a);if(-1==b)a:{for(b=0;b<=FS.sf;b++)if(!FS.streams[b])break a;throw new FS.Ed(33);}a.he=b;return FS.streams[b]=a}
function zg(a,b=-1){a=yg(a,b);a.Hd?.tg?.(a);return a}function Ag(a,b,c){var d=a?.Hd.ae;a=d?a:b;d??=b.Gd.ae;xg(d,63);d(a,c)}function Bg(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.ve)}return b}function Cg(a){var b={mg:4096,wg:4096,Ye:1E6,lg:5E5,kg:5E5,files:FS.Qe,ug:FS.Qe-1,xg:42,flags:2,Bg:255};a.Gd.mf&&Object.assign(b,a.Gd.mf(a.mount.Uf.root));return b}function Dg(a,b,c,d){Ag(a,b,{mode:c&4095|b.mode&-4096,Vd:Date.now(),cf:d})}
function Eg(a,b,c){if(FS.isDir(b.mode))throw new FS.Ed(31);if(!FS.isFile(b.mode))throw new FS.Ed(28);var d=rg(b,"w");if(d)throw new FS.Ed(d);Ag(a,b,{size:c,timestamp:Date.now()})}function Fg(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Tf(a+"/"+b);return FS.create(b,ng(c,d))}
function Gg(a){if(!(a.Qf||a.Rf||a.link||a.Jd))if(globalThis.XMLHttpRequest)H("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Jd=ia(a.url)}catch(b){throw new FS.Ed(29);}}
var FS={root:null,ve:[],bf:{},streams:[],Qe:1,je:null,$e:"/",Me:!1,gf:!0,Bf:null,Ge:0,lf:{},Ed:class{name="ErrnoError";constructor(a){this.Ld=a}},qf:class{ee={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ee.flags}set flags(a){this.ee.flags=a}get position(){return this.ee.position}set position(a){this.ee.position=a}},pf:class{Gd={};Hd={};$d=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Qe++;this.name=b;this.mode=c;this.xe=
d;this.fe=this.Wd=this.Vd=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Rf(){return FS.isDir(this.mode)}get Qf(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.Ed(44);b.Ce??(b.Ce=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-
1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Uf(e),FS.ue(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Tf(e+"/"+a[f]);try{d=lg(d,a[f])}catch(h){if(44===h?.Ld&&g&&b.Tf)return{path:e};throw h;}!d.$d||g&&!b.Ce||(d=d.$d.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.Gd.readlink)throw new FS.Ed(52);d=d.Gd.readlink(d);"/"===d.charAt(0)||(d=Uf(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.Ed(32);},getPath(a){for(var b;;){if(FS.ue(a))return a=
a.mount.jf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.pf(a,b,c,d);tg(a);return a},ue(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},sf:4096,Ff:a=>FS.streams[a],vf:{open(a){a.Hd=FS.Df(a.node.xe).Hd;a.Hd.open?.(a)},llseek(){throw new FS.Ed(70);
}},Pe:a=>a>>8,zg:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.bf[a]={Hd:b}},Df:a=>FS.bf[a],syncfs(a,b){function c(h){FS.Ge--;return b(h)}function d(h){if(h){if(!d.zf)return d.zf=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ge++;1<FS.Ge&&r(`warning: ${FS.Ge} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Bg(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.Ed(10);
if(!d&&c){var e=FS.lookupPath(c,{Ce:!1});c=e.path;e=e.node;if(e.$d)throw new FS.Ed(10);if(!FS.isDir(e.mode))throw new FS.Ed(54);}b={type:a,Uf:b,jf:c,ve:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.$d=b,e.mount&&e.mount.ve.push(b));return a},unmount(a){a=FS.lookupPath(a,{Ce:!1});if(!a.node.$d)throw new FS.Ed(28);a=a.node;var b=a.$d,c=Bg(b);for([,e]of Object.entries(FS.je))for(;e;){var d=e.re;c.includes(e.mount)&&mg(e);var e=d}a.$d=null;a.mount.ve.splice(a.mount.ve.indexOf(b),1)},pe(a,b){return a.Gd.pe(a,
b)},ie(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Vf(a);if(!a)throw new FS.Ed(28);if("."===a||".."===a)throw new FS.Ed(20);var e=vg(d,a);if(e)throw new FS.Ed(e);if(!d.Gd.ie)throw new FS.Ed(63);return d.Gd.ie(d,a,b,c)},mf(a){return Cg(FS.lookupPath(a,{follow:!0}).node)},Dg(a){return Cg(a.node)},create(a,b=438){return FS.ie(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ie(a,b&1023|16384,0)},Ag(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.Ld)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ie(a,b|8192,c)},symlink(a,b){if(!Zf(a))throw new FS.Ed(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.Ed(44);b=Vf(b);var d=vg(c,b);if(d)throw new FS.Ed(d);if(!c.Gd.symlink)throw new FS.Ed(63);return c.Gd.symlink(c,b,a)},rename(a,b){var c=Uf(a),d=Uf(b),e=Vf(a),f=Vf(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.Ed(44);if(h.mount!==g.mount)throw new FS.Ed(75);
var k=lg(h,e);a=$f(a,d);if("."!==a.charAt(0))throw new FS.Ed(28);a=$f(b,c);if("."!==a.charAt(0))throw new FS.Ed(55);try{var l=lg(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=wg(h,e,b))throw new FS.Ed(e);if(e=l?wg(g,f,b):vg(g,f))throw new FS.Ed(e);if(!h.Gd.rename)throw new FS.Ed(63);if(k.$d||l&&l.$d)throw new FS.Ed(10);if(g!==h&&(e=rg(h,"w")))throw new FS.Ed(e);mg(k);try{h.Gd.rename(k,g,f),k.parent=g}catch(m){throw m;}finally{tg(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Vf(a);var c=
lg(b,a),d=wg(b,a,!0);if(d)throw new FS.Ed(d);if(!b.Gd.rmdir)throw new FS.Ed(63);if(c.$d)throw new FS.Ed(10);b.Gd.rmdir(b,a);mg(c)},ye(a){a=FS.lookupPath(a,{follow:!0}).node;return xg(a.Gd.ye,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.Ed(44);a=Vf(a);var c=lg(b,a),d=wg(b,a,!1);if(d)throw new FS.Ed(d);if(!b.Gd.unlink)throw new FS.Ed(63);if(c.$d)throw new FS.Ed(10);b.Gd.unlink(b,a);mg(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.Ed(44);if(!a.Gd.readlink)throw new FS.Ed(28);
return a.Gd.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return xg(a.Gd.Zd,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Dg(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);Dg(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Ag(null,a,{timestamp:Date.now(),cf:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);Ag(a,a.node,{timestamp:Date.now(),cf:!1})},truncate(a,b){if(0>
b)throw new FS.Ed(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Eg(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.Ed(28);Eg(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;xg(a.Gd.ae,63)(a,{fe:b,Wd:c})},open(a,b,c=438){if(""===a)throw new FS.Ed(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=
a;else{var e=a.endsWith("/");a=FS.lookupPath(a,{follow:!(b&131072),Tf:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.Ed(20);}else{if(e)throw new FS.Ed(31);d=FS.ie(a,c|511,0);f=!0}if(!d)throw new FS.Ed(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.Ed(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==ug(g)||g&576)?31:rg(e,ug(g)):44)throw new FS.Ed(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=yg({node:d,path:FS.getPath(d),
flags:b,seekable:!0,position:0,Hd:d.Hd,hg:[],error:!1});e.Hd.open&&e.Hd.open(e);f&&FS.chmod(d,c&511);!n.logReadFiles||b&1||a in FS.lf||(FS.lf[a]=1);return e},close(a){if(null===a.he)throw new FS.Ed(8);a.Le&&(a.Le=null);try{a.Hd.close&&a.Hd.close(a)}catch(b){throw b;}finally{FS.streams[a.he]=null}a.he=null},llseek(a,b,c){if(null===a.he)throw new FS.Ed(8);if(!a.seekable||!a.Hd.llseek)throw new FS.Ed(70);if(0!=c&&1!=c&&2!=c)throw new FS.Ed(28);a.position=a.Hd.llseek(a,b,c);a.hg=[];return a.position},
read(a,b,c,d,e){if(0>d||0>e)throw new FS.Ed(28);if(null===a.he)throw new FS.Ed(8);if(1===(a.flags&2097155))throw new FS.Ed(8);if(FS.isDir(a.node.mode))throw new FS.Ed(31);if(!a.Hd.read)throw new FS.Ed(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.Ed(70);b=a.Hd.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.Ed(28);if(null===a.he)throw new FS.Ed(8);if(0===(a.flags&2097155))throw new FS.Ed(8);if(FS.isDir(a.node.mode))throw new FS.Ed(31);
if(!a.Hd.write)throw new FS.Ed(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.Ed(70);b=a.Hd.write(a,b,c,d,e,f);g||(a.position+=b);return b},qe(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.Ed(2);if(1===(a.flags&2097155))throw new FS.Ed(2);if(!a.Hd.qe)throw new FS.Ed(43);if(!b)throw new FS.Ed(28);return a.Hd.qe(a,b,c,d,e)},se(a,b,c,d,e){return a.Hd.se?a.Hd.se(a,b,c,d,e):0},Ne(a,b,c){if(!a.Hd.Ne)throw new FS.Ed(59);
return a.Hd.Ne(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&H(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=ag(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(eg(b)));ArrayBuffer.isView(b)?FS.write(a,b,0,b.byteLength,void 0,c.sg):H("Unsupported data type");
FS.close(a)},cwd:()=>FS.$e,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.Ed(44);if(!FS.isDir(a.node.mode))throw new FS.Ed(54);var b=rg(a.node,"x");if(b)throw new FS.Ed(b);FS.$e=a.path},init(a,b,c){FS.Me=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",
0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},vg(a,b){a=FS.analyzePath(a,b);return a.df?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={ue:!1,df:!1,error:0,name:null,path:null,object:null,Vf:!1,Xf:null,Wf:null};try{c=FS.lookupPath(a,{parent:!0}),d.Vf=!0,d.Xf=c.path,d.Wf=c.node,d.name=Vf(a),c=FS.lookupPath(a,{follow:!b}),d.df=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.ue="/"===c.path}catch(e){d.error=e.Ld}return d},createPath(a,b){a=
"string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Tf(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.Ld)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Tf(a+"/"+b):a);a=ng(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,
b,c,d){a=Wf("string"==typeof a?a:FS.getPath(a),b);b=ng(!!c,!!d);var e;(e=FS.createDevice).Pe??(e.Pe=64);e=FS.makedev(FS.createDevice.Pe++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=0,m=0;m<k;m++){try{var p=c()}catch(u){throw new FS.Ed(29);}if(void 0===p&&0===l)throw new FS.Ed(6);if(null===p||void 0===p)break;l++;g[h+m]=p}l&&(f.node.fe=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.Ed(29);}k&&
(f.node.Wd=f.node.Vd=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,p,u,x,z){m=m.node.Jd;if(z>=m.length)return 0;x=Math.min(m.length-z,x);if(m.slice)for(var A=0;A<x;A++)p[u+A]=m[z+A];else for(A=0;A<x;A++)p[u+A]=m.get(z+A);return x}class g{Ie=!1;ee=[];te=void 0;Ue=0;Te=0;get(m){if(!(m>this.length-1||0>m)){var p=m%this.We;return this.te(m/this.We|0)[p]}}rf(m){this.te=m}Ve(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=m.status&&300>m.status||
304===m.status||H("Couldn't load "+c+". Status: "+m.status);var p=Number(m.getResponseHeader("Content-length")),u,x=(u=m.getResponseHeader("Accept-Ranges"))&&"bytes"===u;m=(u=m.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;x||(z=p);var A=this;A.rf(F=>{var K=F*z,G=(F+1)*z-1;G=Math.min(G,p-1);if("undefined"==typeof A.ee[F]){var X=A.ee;K>G&&H("invalid range ("+K+", "+G+") or no bytes requested!");G>p-1&&H("only "+p+" bytes available! programmer error!");var M=new XMLHttpRequest;M.open("GET",
c,!1);p!==z&&M.setRequestHeader("Range","bytes="+K+"-"+G);M.responseType="arraybuffer";M.overrideMimeType&&M.overrideMimeType("text/plain; charset=x-user-defined");M.send(null);200<=M.status&&300>M.status||304===M.status||H("Couldn't load "+c+". Status: "+M.status);K=void 0!==M.response?new Uint8Array(M.response||[]):eg(M.responseText||"");X[F]=K}"undefined"==typeof A.ee[F]&&H("doXHR failed!");return A.ee[F]});if(m||!p)z=p=1,z=p=this.te(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Ue=p;this.Te=z;this.Ie=!0}get length(){this.Ie||this.Ve();return this.Ue}get We(){this.Ie||this.Ve();return this.Te}}if(globalThis.XMLHttpRequest){ba||H("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var k=void 0}else k=c,h=void 0;var l=Fg(a,b,d,e);h?l.Jd=h:k&&(l.Jd=null,l.url=k);Object.defineProperties(l,{Qd:{get:function(){return this.Jd.length}}});a={};for(const [m,p]of Object.entries(l.Hd))a[m]=(...u)=>{Gg(l);
return p(...u)};a.read=(m,p,u,x,z)=>{Gg(l);return f(m,p,u,x,z)};a.qe=(m,p,u)=>{Gg(l);var x=kg(p);if(!x)throw new FS.Ed(48);f(m,v,x,p,u);return{Id:x,Xe:!0}};l.Hd=a;return l}};function Hg(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.Ed(44);return a}return a+"/"+b}
function Ig(a,b){D[a>>2]=b.xf;D[a+4>>2]=b.mode;D[a+8>>2]=b.Sf;D[a+12>>2]=b.uid;D[a+16>>2]=b.If;D[a+20>>2]=b.xe;E[a+24>>3]=BigInt(b.size);C[a+32>>2]=4096;C[a+36>>2]=b.Ye;var c=b.fe.getTime(),d=b.Wd.getTime(),e=b.Vd.getTime();E[a+40>>3]=BigInt(Math.floor(c/1E3));D[a+48>>2]=c%1E3*1E6;E[a+56>>3]=BigInt(Math.floor(d/1E3));D[a+64>>2]=d%1E3*1E6;E[a+72>>3]=BigInt(Math.floor(e/1E3));D[a+80>>2]=e%1E3*1E6;E[a+88>>3]=BigInt(b.Mf);return 0}var Jg=void 0;
function fb(a){if(q)return O(3,1,a);try{var b=S(a);return zg(b).he}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Ld}}function gb(a,b,c,d){if(q)return O(4,1,a,b,c,d);try{b=Q(b);b=Hg(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&rg(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Ld}}var Kg=()=>{var a=C[+Jg>>2];Jg+=4;return a};
function hb(a,b,c){if(q)return O(5,1,a,b,c);Jg=c;try{var d=S(a);switch(b){case 0:var e=Kg();if(0>e)break;for(;FS.streams[e];)e++;return zg(d,e).he;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Kg(),d.flags|=e,0;case 12:return e=Kg(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Ld}}
function ib(a,b){if(q)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.Hd.Zd;a=e?c:d;e??=d.Gd.Zd;xg(e,63);var f=e(a);return Ig(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.Ld}}function jb(a,b){if(q)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Ld}}
function kb(a,b){if(q)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=cg(c)+1;if(b<d)return-68;dg(c,w,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.Ld}}
function lb(a,b,c){if(q)return O(9,1,a,b,c);Jg=c;try{var d=S(a);switch(b){case 21509:return d.Nd?0:-59;case 21505:if(!d.Nd)return-59;if(d.Nd.ke.Nf){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Kg();C[e>>2]=25856;C[e+4>>2]=5;C[e+8>>2]=191;C[e+12>>2]=35387;for(var f=0;32>f;f++)v[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Nd?0:-59;case 21506:case 21507:case 21508:if(!d.Nd)return-59;if(d.Nd.ke.Of)for(e=Kg(),a=[],f=0;32>f;f++)a.push(v[e+f+
17]);return 0;case 21519:if(!d.Nd)return-59;e=Kg();return C[e>>2]=0;case 21520:return d.Nd?-28:-59;case 21537:case 21531:return e=Kg(),FS.Ne(d,b,e);case 21523:if(!d.Nd)return-59;d.Nd.ke.Pf&&(f=[24,80],e=Kg(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.Nd?0:-59;case 21515:return d.Nd?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.Ld}}
function mb(a,b){if(q)return O(10,1,a,b);try{return a=Q(a),Ig(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Ld}}function nb(a,b,c,d){if(q)return O(11,1,a,b,c,d);try{b=Q(b);var e=d&256;b=Hg(a,b,d&4096);return Ig(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Ld}}
function ob(a,b,c,d){if(q)return O(12,1,a,b,c,d);Jg=d;try{b=Q(b);b=Hg(a,b);var e=d?Kg():0;return FS.open(b,c,e).he}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Ld}}function pb(a){if(q)return O(13,1,a);try{return a=Q(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.Ld}}function qb(a,b){if(q)return O(14,1,a,b);try{return a=Q(a),Ig(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Ld}}
function rb(a,b,c){if(q)return O(15,1,a,b,c);try{b=Q(b);b=Hg(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.Ld}}var sb=()=>H(""),Lg={},Mg=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Ng(a){return this.Md(D[a>>2])}
var Og={},Pg={},Qg={},Rg=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Rg("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],h[k])}a.forEach(h=>Qg[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())Pg.hasOwnProperty(k)?e[h]=Pg[k]:(f.push(k),Og.hasOwnProperty(k)||(Og[k]=[]),Og[k].push(()=>{e[h]=Pg[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},tb=a=>{var b=Lg[a];delete Lg[a];
var c=b.Se,d=b.de,e=b.ef,f=e.map(g=>g.Hf).concat(e.map(g=>g.bg));U([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){const m=g[k],p=l.te,u=l.Gf,x=g[k+e.length],z=l.ag,A=l.cg;h[l.Af]={read:F=>m.Md(p(u,F)),write:(F,K)=>{var G=[];z(A,F,x.Rd(G,K));Mg(G)},optional:m.optional}}return[{name:b.name,Md:m=>{var p={},u;for(u in h)p[u]=h[u].read(m);d(m);return p},Rd:(m,p)=>{for(var u in h)if(!(u in p||h[u].optional))throw new TypeError(`Missing field: "${u}"`);var x=c();for(u in h)h[u].write(x,p[u]);null!==m&&
m.push(d,x);return x},Xd:Ng,Td:d}]})},V=a=>{for(var b="";;){var c=w[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Sg=a=>{throw new W(a);};function Tg(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Pg.hasOwnProperty(a)){if(c.Lf)return;throw new W(`Cannot register type '${d}' twice`);}Pg[a]=b;delete Qg[a];Og.hasOwnProperty(a)&&(b=Og[a],delete Og[a],b.forEach(e=>e()))}
function T(a,b,c={}){return Tg(a,b,c)}
var ub=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=Ha;break a;case 8:d=Ia;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?v:w;break a;case 2:d=e?y:B;break a;case 4:d=e?C:D;break a;case 8:d=e?E:Ja;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);T(a,{name:b,Md:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+D[h>>2]));I(h);return k},Rd:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new W(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),p=Le(m+l*c);m=p+m>>g;D[p>>2]=l;f.set(k,m);null!==h&&h.push(I,p);return p},Xd:Ng,Td(h){I(h)}})},Ug=(a,b,c)=>{switch(b){case 1:return c?d=>v[d]:d=>w[d];case 2:return c?d=>y[d>>1]:d=>B[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];case 8:return c?d=>E[d>>3]:d=>Ja[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},vb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}T(a,{name:b,
Md:f,Rd:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},Xd:Ug(b,c,!d),Td:null})},wb=(a,b,c,d)=>{b=V(b);T(a,{name:b,Md:function(e){return!!e},Rd:function(e,f){return f?c:d},Xd:function(e){return this.Md(w[e])},Td:null})},Vg=a=>{throw new W(a.Fd.Od.Kd.name+" instance already deleted");},Wg=!1,Xg=!1,Yg=()=>{},Zg=a=>{if(Wg)return Zg=b=>b.deleteLater(),Zg(a);if(!globalThis.FinalizationRegistry)return Zg=b=>b,a;Xg=new FinalizationRegistry(b=>{b=b.Fd;--b.count.value;0===b.count.value&&(b.Sd?b.Yd.de(b.Sd):
b.Od.Kd.de(b.Id))});Zg=b=>{var c=b.Fd;c.Sd&&Xg.register(b,{Fd:c},b);return b};Yg=b=>{Xg.unregister(b)};return Zg(a)},$g=[],ah=()=>{for(;$g.length;){var a=$g.pop();a.Fd.oe=!1;a["delete"]()}},bh;function ch(){}
var dh=(a,b)=>Object.defineProperty(b,"name",{value:a}),eh={},fh=(a,b,c)=>{if(void 0===a[b].Pd){var d=a[b];a[b]=function(...e){if(!a[b].Pd.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Pd})!`);return a[b].Pd[e.length].apply(this,e)};a[b].Pd=[];a[b].Pd[d.me]=d}},gh=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].Pd&&void 0!==n[a].Pd[c])throw new W(`Cannot register public name '${a}' twice`);fh(n,
a,a);if(n[a].Pd.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].Pd[c]=b}else n[a]=b,n[a].me=c},hh=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function ih(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.le=c;this.de=d;this.Ud=e;this.Cf=f;this.ze=g;this.yf=h;this.Zf=[]}
var jh=(a,b,c)=>{for(;b!==c;){if(!b.ze)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ze(a);b=b.Ud}return a},kh=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function lh(a,b){if(null===b){if(this.Oe)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.Fd)throw new W(`Cannot pass "${kh(b)}" as a ${this.name}`);if(!b.Fd.Id)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return jh(b.Fd.Id,b.Fd.Od.Kd,this.Kd)}
function mh(a,b){if(null===b){if(this.Oe)throw new W(`null is not a valid ${this.name}`);if(this.Fe){var c=this.Se();null!==a&&a.push(this.de,c);return c}return 0}if(!b||!b.Fd)throw new W(`Cannot pass "${kh(b)}" as a ${this.name}`);if(!b.Fd.Id)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Ee&&b.Fd.Od.Ee)throw new W(`Cannot convert argument of type ${b.Fd.Yd?b.Fd.Yd.name:b.Fd.Od.name} to parameter type ${this.name}`);c=jh(b.Fd.Id,b.Fd.Od.Kd,this.Kd);if(this.Fe){if(void 0===
b.Fd.Sd)throw new W("Passing raw pointer to smart pointer is illegal");switch(this.dg){case 0:if(b.Fd.Yd===this)c=b.Fd.Sd;else throw new W(`Cannot convert argument of type ${b.Fd.Yd?b.Fd.Yd.name:b.Fd.Od.name} to parameter type ${this.name}`);break;case 1:c=b.Fd.Sd;break;case 2:if(b.Fd.Yd===this)c=b.Fd.Sd;else{var d=b.clone();c=this.$f(c,nh(()=>d["delete"]()));null!==a&&a.push(this.de,c)}break;default:throw new W("Unsupporting sharing policy");}}return c}
function oh(a,b){if(null===b){if(this.Oe)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.Fd)throw new W(`Cannot pass "${kh(b)}" as a ${this.name}`);if(!b.Fd.Id)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Fd.Od.Ee)throw new W(`Cannot convert argument of type ${b.Fd.Od.name} to parameter type ${this.name}`);return jh(b.Fd.Id,b.Fd.Od.Kd,this.Kd)}
var ph=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ud)return null;a=ph(a,b,c.Ud);return null===a?null:c.yf(a)},qh={},rh=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.Ud;)b=a.ze(b),a=a.Ud;return qh[b]},sh=(a,b)=>{if(!b.Od||!b.Id)throw new Rg("makeClassHandle requires ptr and ptrType");if(!!b.Yd!==!!b.Sd)throw new Rg("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Zg(Object.create(a,{Fd:{value:b,writable:!0}}))};
function th(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.Kd=b;this.Oe=c;this.Ee=d;this.Fe=e;this.Yf=f;this.dg=g;this.kf=h;this.Se=k;this.$f=l;this.de=m;e||void 0!==b.Ud?this.Rd=mh:(this.Rd=d?lh:oh,this.Td=null)}var uh=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new Rg("Replacing nonexistent public symbol");void 0!==n[a].Pd&&void 0!==c?n[a].Pd[c]=b:(n[a]=b,n[a].me=c)},Y=(a,b)=>{a=V(a);var c=P(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class vh extends Error{}
var wh=a=>{a=Qe(a);var b=V(a);I(a);return b},xh=(a,b)=>{function c(f){e[f]||Pg[f]||(Qg[f]?Qg[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new vh(`${a}: `+d.map(wh).join([", "]));},xb=(a,b,c,d,e,f,g,h,k,l,m,p,u)=>{m=V(m);f=Y(e,f);h&&=Y(g,h);l&&=Y(k,l);u=Y(p,u);var x=hh(m);gh(x,function(){xh(`Cannot construct ${m} due to unbound types`,[d])});U([a,b,c],d?[d]:[],z=>{z=z[0];if(d){var A=z.Kd;var F=A.le}else F=ch.prototype;z=dh(m,function(...M){if(Object.getPrototypeOf(this)!==K)throw new W(`Use 'new' to construct ${m}`);
if(void 0===G.ne)throw new W(`${m} has no accessible constructor`);var Td=G.ne[M.length];if(void 0===Td)throw new W(`Tried to invoke ctor of ${m} with invalid number of parameters (${M.length}) - expected (${Object.keys(G.ne).toString()}) parameters instead!`);return Td.apply(this,M)});var K=Object.create(F,{constructor:{value:z}});z.prototype=K;var G=new ih(m,z,K,u,A,f,h,l);if(G.Ud){var X;(X=G.Ud).Ae??(X.Ae=[]);G.Ud.Ae.push(G)}A=new th(m,G,!0,!1,!1);X=new th(m+"*",G,!1,!1,!1);F=new th(m+" const*",
G,!1,!0,!1);eh[a]={pointerType:X,wf:F};uh(x,z);return[A,X,F]})};function yh(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Td)return!0;return!1}
function zh(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=yh(b);c=!b[0].hf;var l=b[0],m=b[1];d=[a,Sg,d,e,Mg,l.Md.bind(l),m?.Rd.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.Rd.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].Td&&d.push(b[e].Td);k=yh(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");
m=`return function (${m}) {\n`;k&&(m+="var destructors = [];\n");var p=k?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${p}, this);\n`);for(g=0;g<e;++g){var x=`toArg${g}Wire`;m+=`var arg${g}Wired = ${x}(${p}, arg${g});\n`;u.push(x)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].Td&&(m+=`${f}_dtor(${f});\n`,u.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,m+"}\n"))(...d);return dh(a,b)}
var Ah=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},Bh=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},yb=(a,b,c,d,e,f,g,h)=>{var k=Ah(c,d);b=V(b);b=Bh(b);f=Y(e,f);U([],[a],l=>{function m(){xh(`Cannot call ${p} due to unbound types`,k)}l=l[0];var p=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=l.Kd.constructor;void 0===u[b]?(m.me=c-1,u[b]=m):(fh(u,b,p),u[b].Pd[c-1]=m);U([],k,x=>{x=zh(p,[x[0],null].concat(x.slice(1)),null,f,g,h);void 0===
u[b].Pd?(x.me=c-1,u[b]=x):u[b].Pd[c-1]=x;if(l.Kd.Ae)for(const z of l.Kd.Ae)z.constructor.hasOwnProperty(b)||(z.constructor[b]=x);return[]});return[]})},zb=(a,b,c,d,e,f)=>{var g=Ah(b,c);e=Y(d,e);U([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.Kd.ne&&(h.Kd.ne=[]);if(void 0!==h.Kd.ne[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.Kd.ne[b-1]=()=>{xh(`Cannot construct ${h.name} due to unbound types`,g)};U([],g,l=>{l.splice(1,0,null);h.Kd.ne[b-1]=zh(k,l,null,e,f);return[]});return[]})},Ab=(a,b,c,d,e,f,g,h,k)=>{var l=Ah(c,d);b=V(b);b=Bh(b);f=Y(e,f);U([],[a],m=>{function p(){xh(`Cannot call ${u} due to unbound types`,l)}m=m[0];var u=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.Kd.Zf.push(b);var x=m.Kd.le,z=x[b];void 0===z||void 0===z.Pd&&z.className!==m.name&&z.me===c-2?(p.me=c-2,p.className=m.name,x[b]=
p):(fh(x,b,u),x[b].Pd[c-2]=p);U([],l,A=>{A=zh(u,A,m,f,g,k);void 0===x[b].Pd?(A.me=c-2,x[b]=A):x[b].Pd[c-2]=A;return[]});return[]})},Ch=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.Kd.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.Fd.Id)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return jh(a.Fd.Id,a.Fd.Od.Kd,b.Kd)},Bb=(a,b,c,d,e,f,g,h,k,l)=>{b=V(b);e=Y(d,e);U([],[a],
m=>{m=m[0];var p=`${m.name}.${b}`,u={get(){xh(`Cannot access ${p} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};u.set=k?()=>xh(`Cannot access ${p} due to unbound types`,[c,g]):()=>{throw new W(p+" is a read-only property");};Object.defineProperty(m.Kd.le,b,u);U([],k?[c,g]:[c],x=>{var z=x[0],A={get(){var K=Ch(this,m,p+" getter");return z.Md(e(f,K))},enumerable:!0};if(k){k=Y(h,k);var F=x[1];A.set=function(K){var G=Ch(this,m,p+" setter"),X=[];k(l,G,F.Rd(X,K));Mg(X)}}Object.defineProperty(m.Kd.le,
b,A);return[]});return[]})},Dh=[],Eh=[0,1,,1,null,1,!0,1,!1,1],Yb=a=>{9<a&&0===--Eh[a+1]&&(Eh[a]=void 0,Dh.push(a))},Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Eh[a]},nh=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Dh.pop()||Eh.length;Eh[b]=a;Eh[b+1]=1;return b}},Fh={name:"emscripten::val",Md:a=>{var b=Z(a);Yb(a);return b},Rd:(a,b)=>nh(b),Xd:Ng,Td:null},Cb=a=>T(a,Fh),Gh=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.Md(v[d])}:
function(d){return this.Md(w[d])};case 2:return c?function(d){return this.Md(y[d>>1])}:function(d){return this.Md(B[d>>1])};case 4:return c?function(d){return this.Md(C[d>>2])}:function(d){return this.Md(D[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Db=(a,b,c,d)=>{function e(){}b=V(b);e.values={};T(a,{name:b,constructor:e,Md:function(f){return this.constructor.values[f]},Rd:(f,g)=>g.value,Xd:Gh(b,c,d),Td:null});gh(b,e)},Hh=(a,b)=>{var c=Pg[a];if(void 0===c)throw a=
`${b} has unknown type ${wh(a)}`,new W(a);return c},Eb=(a,b,c)=>{var d=Hh(a,"enum");b=V(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:dh(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},Ih=(a,b)=>{switch(b){case 4:return function(c){return this.Md(Ha[c>>2])};case 8:return function(c){return this.Md(Ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Fb=(a,b,c)=>{b=V(b);T(a,{name:b,Md:d=>d,Rd:(d,e)=>e,Xd:Ih(b,c),Td:null})},
Gb=(a,b,c,d,e,f,g)=>{var h=Ah(b,c);a=V(a);a=Bh(a);e=Y(d,e);gh(a,function(){xh(`Cannot call ${a} due to unbound types`,h)},b-1);U([],h,k=>{uh(a,zh(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})},Hb=(a,b,c,d,e)=>{b=V(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}T(a,{name:b,Md:f,Rd:(h,k)=>k,Xd:Ug(b,c,0!==d),Td:null})},Ib=(a,b,c)=>{function d(f){return new e(v.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,
BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,Md:d,Xd:d},{Lf:!0})},Jh=Object.assign({optional:!0},Fh),Jb=a=>{T(a,Jh)},Kb=(a,b)=>{b=V(b);T(a,{name:b,Md(c){var d=Q(c+4,D[c>>2],!0);I(c);return d},Rd(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?cg(d):d.length;var g=Le(4+f+1),h=g+4;D[g>>2]=f;e?dg(d,w,h,f+1):w.set(d,h);null!==c&&c.push(I,g);return g},
Xd:Ng,Td(c){I(c)}})},Kh=new TextDecoder("utf-16le"),Lh=(a,b,c)=>{a>>=1;return Kh.decode(B.slice(a,Lf(B,a,b/2,c)))},Mh=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Nh=a=>2*a.length,Oh=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=D[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ph=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=
a.codePointAt(e);65535<f&&e++;C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Qh=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Lb=(a,b,c)=>{c=V(c);if(2===b){var d=Lh;var e=Mh;var f=Nh}else d=Oh,e=Ph,f=Qh;T(a,{name:c,Md:g=>{var h=d(g+4,D[g>>2]*b,!0);I(g);return h},Rd:(g,h)=>{if("string"!=typeof h)throw new W(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=Le(4+k+b);D[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(I,l);return l},Xd:Ng,Td(g){I(g)}})},Mb=(a,
b,c,d,e,f)=>{Lg[a]={name:V(b),Se:Y(c,d),de:Y(e,f),ef:[]}},Nb=(a,b,c,d,e,f,g,h,k,l)=>{Lg[a].ef.push({Af:V(b),Hf:c,te:Y(d,e),Gf:f,bg:g,ag:Y(h,k),cg:l})},Ob=(a,b)=>{b=V(b);T(a,{hf:!0,name:b,Md:()=>{},Rd:()=>{}})},Pb=a=>{Aa(a,!ba,1,!aa,262144,!1);Ba()},Ca=a=>{Atomics.waitAsync&&(Atomics.waitAsync(C,a>>2,a).value.then(Fa),Atomics.store(C,a+128>>2,1))},Fa=()=>yf(()=>{var a=Ke();a&&(Ca(a),Xe())}),Qb=(a,b)=>{a==b?setTimeout(Fa):q?postMessage({He:a,ge:"checkMailbox"}):(a=sf[a])&&a.postMessage({ge:"checkMailbox"})},
Rh=[],Rb=(a,b,c,d,e)=>{d/=2;Rh.length=d;b=e>>3;for(c=0;c<d;c++)Rh[c]=E[b+2*c]?E[b+2*c+1]:Ia[b+2*c+1];return(0,Sh[a])(...Rh)},Sb=()=>{zf=!1;gf=0},Tb=a=>{q?postMessage({ge:"cleanupThread",gg:a}):xf(sf[a])},Ub=()=>{},Vb=()=>{throw new oa;},Wb=(a,b)=>{a=Z(a);b=Z(b);a.set(b)},Th=[],Uh=a=>{var b=Th.length;Th.push(a);return b},Vh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Hh(D[b+4*d>>2],`parameter ${d}`);return c},Wh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(D[b>>2]=nh(d));return a},Xh={},Yh=a=>{var b=Xh[a];
return void 0===b?V(a):b},Xb=(a,b,c)=>{var [d,...e]=Vh(a,b);b=d.Rd.bind(d);var f=e.map(k=>k.Xd.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Yh,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.hf||(g.toReturnWire=b,g.emval_returnValue=Wh,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);
h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return Uh(dh(h,c))},Zb=a=>{if(!a)return nh(globalThis);a=Yh(a);return nh(globalThis[a])},$b=a=>{a=Yh(a);return nh(n[a])},ac=(a,b)=>{a=Z(a);b=Z(b);return nh(a[b])},bc=a=>{9<a&&(Eh[a+1]+=1)},cc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b},dc=(a,b,c,d,e)=>Th[a](b,c,d,e),ec=a=>{a=Z(a);return"number"==typeof a},fc=a=>
{a=Z(a);return"string"==typeof a},gc=a=>nh(Yh(a)),hc=a=>nh(Q(a)),ic=a=>{var b=Z(a);Mg(b);Yb(a)},jc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c},kc=a=>{a=Z(a);return nh(typeof a)};
function lc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);C[b>>2]=a.getUTCSeconds();C[b+4>>2]=a.getUTCMinutes();C[b+8>>2]=a.getUTCHours();C[b+12>>2]=a.getUTCDate();C[b+16>>2]=a.getUTCMonth();C[b+20>>2]=a.getUTCFullYear()-1900;C[b+24>>2]=a.getUTCDay();C[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}var Zh=[0,31,60,91,121,152,182,213,244,274,305,335],$h=[0,31,59,90,120,151,181,212,243,273,304,334];
function mc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);C[b>>2]=a.getSeconds();C[b+4>>2]=a.getMinutes();C[b+8>>2]=a.getHours();C[b+12>>2]=a.getDate();C[b+16>>2]=a.getMonth();C[b+20>>2]=a.getFullYear()-1900;C[b+24>>2]=a.getDay();var c=a.getFullYear();C[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?$h:Zh)[a.getMonth()]+a.getDate()-1|0;C[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
C[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}function nc(a,b,c,d,e,f,g){if(q)return O(16,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=S(d),k=FS.qe(h,a,e,b,c),l=k.Id;C[f>>2]=k.Xe;D[g>>2]=l;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.Ld}}
function oc(a,b,c,d,e,f){if(q)return O(17,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.Ed(43);d&2||FS.se(g,w.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.Ld}}var ai={},xc=()=>performance.timeOrigin+performance.now();
function pc(a,b){if(q)return O(18,1,a,b);ai[a]&&(clearTimeout(ai[a].id),delete ai[a]);if(!b)return 0;var c=setTimeout(()=>{delete ai[a];yf(()=>We(a,performance.timeOrigin+performance.now()))},b);ai[a]={id:c,Eg:b};return 0}
var qc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(f,e);C[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(dg(a,w,c,17),dg(b,w,d,17)):(dg(a,w,d,17),dg(b,w,c,17))},tc=()=>Date.now(),bi=1;
function rc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(bi)a=performance.timeOrigin+performance.now();else return 52;E[c>>3]=BigInt(Math.round(1E6*a));return 0}
var sc=()=>{},uc=a=>r(Q(a)),vc=()=>{gf+=1;throw"unwind";},wc=()=>w.length,yc=()=>navigator.hardwareConcurrency,zc=()=>!1,ci={},ei=()=>{if(!di){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in ci)void 0===ci[b]?delete a[b]:a[b]=ci[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);di=c}return di},di;
function Ac(a,b){if(q)return O(19,1,a,b);var c=0,d=0,e;for(e of ei()){var f=b+c;D[a+d>>2]=f;c+=dg(e,w,f,Infinity)+1;d+=4}return 0}function Bc(a,b){if(q)return O(20,1,a,b);var c=ei();D[a>>2]=c.length;a=0;for(var d of c)a+=cg(d)+1;D[b>>2]=a;return 0}function Dc(a){if(q)return O(21,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.Ld}}
function Ec(a,b){if(q)return O(22,1,a,b);try{var c=S(a),d=c.Nd?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;v[b]=d;y[b+2>>1]=0;E[b+8>>3]=BigInt(0);E[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.Ld}}
function Fc(a,b,c,d){if(q)return O(23,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var l=FS.read(e,v,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}D[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.Ld}}
function Gc(a,b,c,d){if(q)return O(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=S(a);FS.llseek(e,b,c);E[d>>3]=BigInt(e.position);e.Le&&0===b&&0===c&&(e.Le=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.Ld}}
function Hc(a,b,c,d){if(q)return O(25,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var l=FS.write(e,v,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}D[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.Ld}}function Ie(a,b){try{return Yf(w.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.Ld}}
var fi=[],gi=a=>{const b=a.length;return[b%128|128,b>>7,...a]},hi={i:127,p:127,j:126,f:125,d:124,e:111},ii=a=>gi(Array.from(a,b=>hi[b])),Pa=[],ji,qa=a=>{var b=N(),c=$e(4),d=$e(4);af(a,c,d);a=D[c>>2];d=D[d>>2];c=Q(a);I(a);if(d){var e=Q(d);I(d)}L(b);return[c,e]};q||uf();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{qg(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Cg=qg;FS.je=Array(4096);FS.mount(R,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));gg(FS.makedev(5,0),ig);gg(FS.makedev(6,0),jg);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Yf(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.Hd={llseek:R.Hd.llseek};b.Gd={pe(c,d){c=+d;var e=S(c);c={parent:null,mount:{jf:"fake"},Gd:{readlink:()=>e.path},id:c+1};return c.parent=c},ye(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Bf={MEMFS:R};
(()=>{let a=ch.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof ch&&c instanceof ch))return!1;var d=this.Fd.Od.Kd,e=this.Fd.Id;c.Fd=c.Fd;var f=c.Fd.Od.Kd;for(c=c.Fd.Id;d.Ud;)e=d.ze(e),d=d.Ud;for(;f.Ud;)c=f.ze(c),f=f.Ud;return d===f&&e===c},clone:function(){this.Fd.Id||Vg(this);if(this.Fd.we)return this.Fd.count.value+=1,this;var c=Zg,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.Fd;c=c(e.call(d,f,{Fd:{value:{count:g.count,oe:g.oe,we:g.we,Id:g.Id,Od:g.Od,Sd:g.Sd,Yd:g.Yd}}}));
c.Fd.count.value+=1;c.Fd.oe=!1;return c},["delete"](){this.Fd.Id||Vg(this);if(this.Fd.oe&&!this.Fd.we)throw new W("Object already scheduled for deletion");Yg(this);var c=this.Fd;--c.count.value;0===c.count.value&&(c.Sd?c.Yd.de(c.Sd):c.Od.Kd.de(c.Id));this.Fd.we||(this.Fd.Sd=void 0,this.Fd.Id=void 0)},isDeleted:function(){return!this.Fd.Id},deleteLater:function(){this.Fd.Id||Vg(this);if(this.Fd.oe&&!this.Fd.we)throw new W("Object already scheduled for deletion");$g.push(this);1===$g.length&&bh&&bh(ah);
this.Fd.oe=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(th.prototype,{Ef(a){this.kf&&(a=this.kf(a));return a},af(a){this.de?.(a)},Xd:Ng,Md:function(a){function b(){return this.Fe?sh(this.Kd.le,{Od:this.Yf,Id:c,Yd:this,Sd:a}):sh(this.Kd.le,{Od:this,Id:a})}var c=this.Ef(a);if(!c)return this.af(a),null;var d=rh(this.Kd,c);if(void 0!==d){if(0===d.Fd.count.value)return d.Fd.Id=c,d.Fd.Sd=a,d.clone();d=d.clone();this.af(a);return d}d=this.Kd.Cf(c);d=eh[d];if(!d)return b.call(this);d=this.Ee?d.wf:d.pointerType;var e=ph(c,this.Kd,d.Kd);return null===
e?b.call(this):this.Fe?sh(d.Kd.le,{Od:d,Id:e,Yd:this,Sd:a}):sh(d.Kd.le,{Od:d,Id:e})}});jf.push(()=>{ci.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;ci.VIPS_CONCURRENCY=1});
Pa.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>nh(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(ch.prototype,{preventAutoDelete:function(){const a=$g.indexOf(this);-1<a&&$g.splice(a,1);this.Fd.oe=!1;return this}});
if(!q){if(n.wasmMemory)va=n.wasmMemory;else{var ki=n.INITIAL_MEMORY||1073741824;va=new WebAssembly.Memory({initial:ki/65536,maximum:ki/65536,shared:!0})}wa()}n.preloadPlugins&&(Cf=n.preloadPlugins);n.noExitRuntime&&(zf=n.noExitRuntime);n.print&&(ja=n.print);n.printErr&&(r=n.printErr);n.wasmBinary&&(ka=n.wasmBinary);n.thisProgram&&(da=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();n.ENV=ci;n.addRunDependency=nf;
n.removeRunDependency=mf;
n.addFunction=(a,b)=>{if(!ji){ji=new WeakMap;var c=df.length;if(ji)for(var d=0;d<0+c;d++){var e=P(d);e&&ji.set(e,d)}}if(c=ji.get(a)||0)return c;c=fi.length?fi.pop():df.grow(1);try{df.set(c,a),Jf[c]=df.get(c)}catch(f){if(!(f instanceof TypeError))throw f;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...gi([1,96,...ii(b.slice(1)),...ii("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;df.set(c,b);Jf[c]=df.get(c)}ji.set(a,
c);return c};n.FS_preloadFile=qg;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{Wg=a};n.deletionQueue=$g;n.setDelayFunction=a=>{bh=a;$g.length&&bh&&bh(ah)};n.incrementExceptionRefcount=a=>Pe(a);n.decrementExceptionRefcount=a=>Oe(a);n.getExceptionMessage=a=>qa(a);
var Sh=[He,Af,Rf,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,rb,nc,oc,pc,Ac,Bc,Dc,Ec,Fc,Gc,Hc];function li(a){for(var b=B[a+6>>1];13===b&&!(16<D[a>>2]);){var c=D[a+8>>2],d=D[c>>2];if(0===d){b=0;break}else if(0===D[(c>>2)+1])a=d,b=B[d+6>>1];else break}return[a,b]}
function Ic(a,b,c,d){var e=D[(a>>2)+1],f=D[(a>>2)+6],g=D[(a>>2)+2],h=D[(a>>2)+5];a=li(D[(a>>2)+3])[1];var k=N(),l=k,m=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),p=!0;for(var u=0;u<f;u++){var x=D[(d>>2)+u],z=li(D[(g>>2)+u]),A=z[0];z=z[1];switch(z){case 1:case 10:case 9:m.push(D[x>>2]);break;case 2:m.push(Ha[x>>2]);break;case 3:m.push(Ia[x>>3]);break;case 5:m.push(w[x]);break;case 6:m.push(v[x]);break;case 7:m.push(B[x>>
1]);break;case 8:m.push(y[x>>1]);break;case 11:case 12:m.push(Ja[x>>3]);break;case 4:m.push(Ja[x>>3]);m.push(Ja[(x>>3)+1]);break;case 13:z=D[A>>2];A=B[A+4>>1];l-=z;l&=~(A-1);v.subarray(l,l+z).set(v.subarray(x,x+z));m.push(l);break;case 14:m.push(D[x>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+z);}}if(h&1){h=[];for(u=e-1;u>=f;u--)switch(x=D[(d>>2)+u],z=li(D[(g>>2)+u]),A=z[0],z=z[1],z){case 5:case 6:--l;l&=-1;w[l]=w[x];break;case 7:case 8:l-=2;l&=
-2;B[l>>1]=B[x>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;D[l>>2]=D[x>>2];break;case 3:case 11:case 12:l-=8;l&=-8;D[l>>2]=D[x>>2];D[(l>>2)+1]=D[(x>>2)+1];break;case 4:l-=16;l&=-8;D[l>>2]=D[x>>2];D[(l>>2)+1]=D[(x>>2)+1];D[(l>>2)+2]=D[(x>>2)+2];D[(l>>2)+3]=D[(x>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,x,D[A>>2],B[A+4>>1]]);break;case 14:l-=4;l&=-4;D[l>>2]=D[x>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+z);}m.push(l);for(u=0;u<h.length;u++)e=
h[u],d=e[0],x=e[1],z=e[2],A=e[3],l-=z,l&=~(A-1),v.subarray(l,l+z).set(v.subarray(x,x+z)),D[d>>2]=l}L(l);$e(0);b=P(b).apply(null,m);L(k);if(!p)switch(a){case 0:break;case 1:case 9:case 10:D[c>>2]=b;break;case 2:Ha[c>>2]=b;break;case 3:Ia[c>>3]=b;break;case 5:case 6:w[c+0]=b;break;case 7:case 8:B[c>>1]=b;break;case 11:case 12:Ja[c>>3]=b;break;case 14:D[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}
var Ke,Le,Me,I,Ne,Oe,Pe,Qe,Da,Re,Se,Aa,Ga,Te,Ue,Ve,We,Xe,J,Ye,Ze,L,$e,N,af,bf,cf,df,Va;function Fd(a,b){var c=N();try{P(a)(b)}catch(d){L(c);if(!(d instanceof t))throw d;J(1,0)}}function Vd(a,b,c){var d=N();try{P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function ce(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function fd(a,b,c,d,e){var f=N();try{return P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}
function le(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function me(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function ed(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function od(a,b,c,d,e,f,g,h,k,l,m,p){var u=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m,p)}catch(x){L(u);if(!(x instanceof t))throw x;J(1,0)}}
function qe(a,b,c,d,e,f,g,h,k){var l=N();try{P(a)(b,c,d,e,f,g,h,k)}catch(m){L(l);if(!(m instanceof t))throw m;J(1,0)}}function pe(a,b,c,d,e,f,g,h){var k=N();try{P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function ne(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Be(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}
function te(a,b,c,d,e,f,g,h,k,l,m,p){var u=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p)}catch(x){L(u);if(!(x instanceof t))throw x;J(1,0)}}function Cd(a,b,c,d,e,f,g,h,k,l,m,p){var u=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p)}catch(x){L(u);if(!(x instanceof t))throw x;J(1,0)}}function Ed(a,b,c,d,e,f,g,h){var k=N();try{P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function Sd(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}
function Dd(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Qd(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function ld(a,b,c,d,e,f,g){var h=N();try{return P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function xe(a,b,c,d,e,f,g,h,k,l,m,p,u,x,z,A,F,K,G){var X=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p,u,x,z,A,F,K,G)}catch(M){L(X);if(!(M instanceof t))throw M;J(1,0)}}
function Ae(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function ae(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Pd(a,b,c,d,e,f,g,h,k){var l=N();try{P(a)(b,c,d,e,f,g,h,k)}catch(m){L(l);if(!(m instanceof t))throw m;J(1,0)}}function Od(a,b,c,d,e,f,g,h,k,l){var m=N();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(p){L(m);if(!(p instanceof t))throw p;J(1,0)}}
function Rc(a,b,c,d,e,f,g,h,k,l,m,p,u){var x=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m,p,u)}catch(z){L(x);if(!(z instanceof t))throw z;J(1,0)}}function Qc(a,b,c,d,e,f,g,h,k,l,m,p,u,x,z){var A=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m,p,u,x,z)}catch(F){L(A);if(!(F instanceof t))throw F;J(1,0)}}function Rd(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function je(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}
function cd(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function Bd(a){var b=N();try{P(a)()}catch(c){L(b);if(!(c instanceof t))throw c;J(1,0)}}function se(a,b,c,d,e,f,g,h,k,l,m){var p=N();try{P(a)(b,c,d,e,f,g,h,k,l,m)}catch(u){L(p);if(!(u instanceof t))throw u;J(1,0)}}function re(a,b,c,d,e,f,g,h,k,l){var m=N();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(p){L(m);if(!(p instanceof t))throw p;J(1,0)}}
function be(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function bd(a,b,c,d,e){var f=N();try{return P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function Ud(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Yc(a,b){var c=N();try{return P(a)(b)}catch(d){L(c);if(!(d instanceof t))throw d;J(1,0)}}
function ad(a,b,c,d,e,f,g){var h=N();try{return P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Kd(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Md(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Oc(a,b,c,d,e,f,g){var h=N();try{return P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}
function ud(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function kd(a,b,c,d,e,f,g,h,k,l,m){var p=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m)}catch(u){L(p);if(!(u instanceof t))throw u;J(1,0)}}function ke(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function $d(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}
function ie(a,b,c,d,e,f,g,h,k,l,m){var p=N();try{P(a)(b,c,d,e,f,g,h,k,l,m)}catch(u){L(p);if(!(u instanceof t))throw u;J(1,0)}}function Hd(a,b,c){var d=N();try{P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function Uc(a,b,c,d,e,f,g){var h=N();try{return P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Gd(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}
function oe(a,b,c,d,e,f,g,h,k,l){var m=N();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(p){L(m);if(!(p instanceof t))throw p;J(1,0)}}function md(a,b,c,d,e,f,g,h){var k=N();try{return P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function Tc(a,b,c,d,e){var f=N();try{return P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function yd(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0);return 0n}}
function Ce(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function Nd(a,b,c,d,e,f,g,h){var k=N();try{P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function Ld(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function Nc(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}
function xd(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0);return 0n}}function wd(a,b){var c=N();try{return P(a)(b)}catch(d){L(c);if(!(d instanceof t))throw d;J(1,0);return 0n}}function Fe(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function De(a,b,c){var d=N();try{P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}
function vd(a,b,c,d,e){var f=N();try{return P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function Ge(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function Jd(a,b,c){var d=N();try{P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function Jc(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}
function Pc(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function Mc(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Wc(a,b){var c=N();try{return P(a)(b)}catch(d){L(c);if(!(d instanceof t))throw d;J(1,0)}}function Sc(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}
function Xc(a,b){var c=N();try{return P(a)(b)}catch(d){L(c);if(!(d instanceof t))throw d;J(1,0)}}function Vc(a){var b=N();try{return P(a)()}catch(c){L(b);if(!(c instanceof t))throw c;J(1,0)}}function hd(a,b,c,d,e,f){var g=N();try{return P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function Lc(a,b,c,d,e,f){var g=N();try{return P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}
function Xd(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function dd(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Wd(a,b,c,d){var e=N();try{P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0)}}function Kc(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}
function Id(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function fe(a,b,c,d,e,f,g,h){var k=N();try{P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function de(a,b,c,d,e,f,g,h,k,l){var m=N();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(p){L(m);if(!(p instanceof t))throw p;J(1,0)}}function ee(a,b,c,d,e,f,g,h,k){var l=N();try{P(a)(b,c,d,e,f,g,h,k)}catch(m){L(l);if(!(m instanceof t))throw m;J(1,0)}}
function he(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function ge(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Zd(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function ue(a,b,c,d,e,f,g,h,k,l,m,p,u){var x=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p,u)}catch(z){L(x);if(!(z instanceof t))throw z;J(1,0)}}
function ve(a,b,c,d,e,f,g,h,k,l,m,p,u,x){var z=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p,u,x)}catch(A){L(z);if(!(A instanceof t))throw A;J(1,0)}}function Yd(a,b,c,d,e,f){var g=N();try{P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function zd(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0);return 0n}}function pd(a,b,c,d,e,f,g,h,k,l,m,p,u){var x=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m,p,u)}catch(z){L(x);if(!(z instanceof t))throw z;J(1,0)}}
function jd(a,b,c,d,e,f,g,h){var k=N();try{return P(a)(b,c,d,e,f,g,h)}catch(l){L(k);if(!(l instanceof t))throw l;J(1,0)}}function Zc(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}function Ad(a,b,c,d){var e=N();try{return P(a)(b,c,d)}catch(f){L(e);if(!(f instanceof t))throw f;J(1,0);return 0n}}function ye(a,b,c,d,e,f,g,h,k,l,m){var p=N();try{P(a)(b,c,d,e,f,g,h,k,l,m)}catch(u){L(p);if(!(u instanceof t))throw u;J(1,0)}}
function ze(a,b,c,d,e,f,g){var h=N();try{P(a)(b,c,d,e,f,g)}catch(k){L(h);if(!(k instanceof t))throw k;J(1,0)}}function Ee(a,b,c,d,e){var f=N();try{P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function qd(a,b,c,d,e,f,g,h,k,l,m,p,u,x,z,A,F){var K=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m,p,u,x,z,A,F)}catch(G){L(K);if(!(G instanceof t))throw G;J(1,0)}}function $c(a,b,c){var d=N();try{return P(a)(b,c)}catch(e){L(d);if(!(e instanceof t))throw e;J(1,0)}}
function sd(a,b,c,d,e){var f=N();try{return P(a)(b,c,d,e)}catch(g){L(f);if(!(g instanceof t))throw g;J(1,0)}}function td(a,b,c,d,e,f){var g=N();try{return P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function nd(a,b,c,d,e,f,g,h,k,l,m){var p=N();try{return P(a)(b,c,d,e,f,g,h,k,l,m)}catch(u){L(p);if(!(u instanceof t))throw u;J(1,0)}}function rd(a,b,c,d,e,f){var g=N();try{return P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}
function gd(a,b,c,d,e,f){var g=N();try{return P(a)(b,c,d,e,f)}catch(h){L(g);if(!(h instanceof t))throw h;J(1,0)}}function we(a,b,c,d,e,f,g,h,k,l,m,p,u,x,z,A){var F=N();try{P(a)(b,c,d,e,f,g,h,k,l,m,p,u,x,z,A)}catch(K){L(F);if(!(K instanceof t))throw K;J(1,0)}}
function ya(){function a(){n.calledRun=!0;if(!ma){Ma();ra?.(n);n.onRuntimeInitialized?.();if(!n.noInitialRun){var b=Me;try{var c=b(0,0);Cc(c,!0)}catch(d){ff(d)}}if(!q){if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)b=n.postRun.shift(),If.push(b);Oa(If)}}}if(0<kf)lf=ya;else if(q)ra?.(n),Ma();else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)jf.push(n.preRun.shift());Oa(jf);0<kf?lf=ya:n.setStatus?(n.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);a()},1)):a()}}var Na;q||(Na=await (xa()),ya());Ka?moduleRtn=n:moduleRtn=new Promise((a,b)=>{ra=a;sa=b});
;return moduleRtn}export default Vips;var isPthread=globalThis.self?.name?.startsWith("em-pthread");isPthread&&Vips();
