var Vips=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var n=moduleArg;n.workaroundCors&&(n.mainScriptUrlOrBlob=n.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var aa="./this.program",ba="",ca;try{ba=(new URL(".",_scriptName)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),q=console.error.bind(console),ea,fa=!1,ha;class v extends Error{}
class ia extends v{}class ja extends v{constructor(a){super(a);this.cd=a;a=ka(a);this.name=a[0];this.message=a[1]}}var la,ma,na,x,y,z,A,B,C,oa,pa,D,qa,ra=!1,sa=!1;function ta(){var a=na.buffer;x=new Int8Array(a);z=new Int16Array(a);y=new Uint8Array(a);A=new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);oa=new Float32Array(a);pa=new Float64Array(a);D=new BigInt64Array(a);qa=new BigUint64Array(a)}
function F(a){n.onAbort?.(a);a="Aborted("+a+")";q(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var ua;async function va(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==ua&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),F(d)}}
async function xa(a){var b=ua;if(!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return wa(b,a)}var za=a=>{if(!(a instanceof ya||"unwind"==a))throw a;};class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=0,Ca=a=>{ha=a;Ba||0<Aa||(n.onExit?.(a),fa=!0);throw new ya(a);},Ga=a=>{ha=a;if(!(Ba||0<Aa)){Da();FS.ed=!1;Fa(0);for(var b of FS.streams)b&&FS.close(b);sa=!0}Ca(a)},Ha=a=>{if(!sa&&!fa)try{if(a(),!(sa||Ba||0<Aa))try{Ga(ha)}catch(b){za(b)}}catch(b){za(b)}},Ia=a=>{Aa+=1;setTimeout(()=>{--Aa;Ha(a)},1E4)},Ja=[],Ka=!1;
function La(){function a(){Ka=document.pointerLockElement===n.canvas}if(!Ma){Ma=!0;Ja.push({canHandle:function(c){return!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Na(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Na(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var l=new Image;l.onload=()=>{var k=document.createElement("canvas");k.width=l.width;k.height=l.height;k.getContext("2d").drawImage(l,
0,0);URL.revokeObjectURL(f);g(c)};l.onerror=()=>{q(`Image ${f} could not be decoded`);h()};l.src=f})}});Ja.push({canHandle:function(c){return!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Na(d)})),l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=function(){if(!g){q(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var k="",m=0,p=0,t=0;t<c.length;t++)for(m=m<<8|c[t],p+=8;6<=p;){var r=m>>p-6&63;p-=6;k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==p?(k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],k+="=="):4==p&&(k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],k+="=");l.src="data:audio/x-"+d.slice(-3)+";base64,"+k;f(l)}};l.src=h;Ia(()=>{f(l)})})}});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),n.elementPointerLock&&b.addEventListener("click",c=>{!Ka&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Na(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Oa={},Ma,Pa=a=>{for(;0<a.length;)a.shift()(n)},Qa=[],Ra=[],Ba=!1,Sa=new TextDecoder,Ta=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},G=(a,b,c)=>a?Sa.decode(y.subarray(a,Ta(y,a,b,c))):"",Ua=[],Va,I=a=>{var b=Ua[a];b||(Ua[a]=b=Va.get(a));return b},Wa=[],Xa=0,Ya=0;class Za{constructor(a){this.cd=a;this.ec=a-24}init(a,b){C[this.ec+16>>2]=0;C[this.ec+4>>2]=a;C[this.ec+8>>2]=b}}
var bb=a=>{var b=Ya?.cd;if(!b)return $a(0),0;var c=new Za(b);C[c.ec+16>>2]=b;var d=C[c.ec+4>>2];if(!d)return $a(0),b;for(var e of a){if(0===e||e===d)break;if(ab(e,d,c.ec+16))return $a(e),b}$a(d);return b},cb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},db=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=cb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");
return(b?"/":"")+a},eb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},fb=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],gb=(a,b)=>db(a+"/"+b),hb=()=>a=>crypto.getRandomValues(a),ib=a=>{(ib=hb())(a)},jb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
cb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},kb=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var l=g.length-1;0<=l&&""===g[l];l--);return h>l?[]:g.slice(h,l-h+1)}a=jb(a).slice(1);b=jb(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},lb=a=>{var b=Ta(a,0);return Sa.decode(a.buffer?a.subarray(0,
b):new Uint8Array(a.slice(0,b)))},mb=[],nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ob=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=
128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},pb=a=>{var b=Array(nb(a)+1);a=ob(a,b,0,b.length);b.length=a;return b},qb=[];function rb(a,b){qb[a]={input:[],output:[],Fc:b};FS.registerDevice(a,sb)}
var sb={open(a){var b=qb[a.node.Sc];if(!b)throw new FS.$b(43);a.jc=b;a.seekable=!1},close(a){a.jc.Fc.Xc(a.jc)},Xc(a){a.jc.Fc.Xc(a.jc)},read(a,b,c,d){if(!a.jc||!a.jc.Fc.Ad)throw new FS.$b(60);for(var e=0,f=0;f<d;f++){try{var g=a.jc.Fc.Ad(a.jc)}catch(h){throw new FS.$b(29);}if(void 0===g&&0===e)throw new FS.$b(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Cc=Date.now());return e},write(a,b,c,d){if(!a.jc||!a.jc.Fc.kd)throw new FS.$b(60);try{for(var e=0;e<d;e++)a.jc.Fc.kd(a.jc,b[c+e])}catch(f){throw new FS.$b(29);
}d&&(a.node.sc=a.node.rc=Date.now());return e}},tb={Ad(){a:{if(!mb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}mb=pb(a)}a=mb.shift()}return a},kd(a,b){null===b||10===b?(da(lb(a.output)),a.output=[]):0!=b&&a.output.push(b)},Xc(a){0<a.output?.length&&(da(lb(a.output)),a.output=[])},ae(){return{ze:25856,Be:5,ye:191,Ae:35387,xe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0]}},be(){return 0},ce(){return[24,80]}},ub={kd(a,b){null===b||10===b?(q(lb(a.output)),a.output=[]):0!=b&&a.output.push(b)},Xc(a){0<a.output?.length&&(q(lb(a.output)),a.output=[])}},wb=a=>{a=65536*Math.ceil(a/65536);var b=vb(65536,a);b&&y.fill(0,b,b+a);return b},J={zc:null,mount(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.$b(63);J.zc||(J.zc={dir:{node:{vc:J.bc.vc,xc:J.bc.xc,Kc:J.bc.Kc,Ec:J.bc.Ec,rename:J.bc.rename,
unlink:J.bc.unlink,rmdir:J.bc.rmdir,Tc:J.bc.Tc,symlink:J.bc.symlink},stream:{llseek:J.cc.llseek}},file:{node:{vc:J.bc.vc,xc:J.bc.xc},stream:{llseek:J.cc.llseek,read:J.cc.read,write:J.cc.write,Lc:J.cc.Lc,Nc:J.cc.Nc}},link:{node:{vc:J.bc.vc,xc:J.bc.xc,readlink:J.bc.readlink},stream:{}},qd:{node:{vc:J.bc.vc,xc:J.bc.xc},stream:FS.Ld}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.bc=J.zc.dir.node,c.cc=J.zc.dir.stream,c.dc={}):FS.isFile(c.mode)?(c.bc=J.zc.file.node,c.cc=J.zc.file.stream,c.mc=0,c.dc=null):
FS.isLink(c.mode)?(c.bc=J.zc.link.node,c.cc=J.zc.link.stream):FS.isChrdev(c.mode)&&(c.bc=J.zc.qd.node,c.cc=J.zc.qd.stream);c.Cc=c.sc=c.rc=Date.now();a&&(a.dc[b]=c,a.Cc=a.sc=a.rc=c.Cc);return c},Ie(a){return a.dc?a.dc.subarray?a.dc.subarray(0,a.mc):new Uint8Array(a.dc):new Uint8Array(0)},bc:{vc(a){var b={};b.Nd=FS.isChrdev(a.mode)?a.id:1;b.$d=a.id;b.mode=a.mode;b.fe=1;b.uid=0;b.Yd=0;b.Sc=a.Sc;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.mc:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;
b.Cc=new Date(a.Cc);b.sc=new Date(a.sc);b.rc=new Date(a.rc);b.Kd=4096;b.od=Math.ceil(b.size/b.Kd);return b},xc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.mc!=b&&(0==b?(a.dc=null,a.mc=0):(c=a.dc,a.dc=new Uint8Array(b),c&&a.dc.set(c.subarray(0,Math.min(b,a.mc))),a.mc=b)))},Kc(){J.bd||(J.bd=new FS.$b(44),J.bd.stack="<generic error, no stack>");throw J.bd;},Ec(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=M(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.dc)throw new FS.$b(55);
xb(d)}delete a.parent.dc[a.name];b.dc[c]=a;a.name=c;b.rc=b.sc=a.parent.rc=a.parent.sc=Date.now()},unlink(a,b){delete a.dc[b];a.rc=a.sc=Date.now()},rmdir(a,b){var c=M(a,b),d;for(d in c.dc)throw new FS.$b(55);delete a.dc[b];a.rc=a.sc=Date.now()},Tc(a){return[".","..",...Object.keys(a.dc)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.$b(28);return a.link}},cc:{read(a,b,c,d,e){var f=a.node.dc;if(e>=a.node.mc)return 0;a=Math.min(a.node.mc-
e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===x.buffer&&(f=!1);if(!d)return 0;a=a.node;a.sc=a.rc=Date.now();if(b.subarray&&(!a.dc||a.dc.subarray)){if(f)return a.dc=b.subarray(c,c+d),a.mc=d;if(0===a.mc&&0===e)return a.dc=b.slice(c,c+d),a.mc=d;if(e+d<=a.mc)return a.dc.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.dc?a.dc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.dc,a.dc=new Uint8Array(f),
0<a.mc&&a.dc.set(g.subarray(0,a.mc),0));if(a.dc.subarray&&b.subarray)a.dc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.dc[e+f]=b[c+f];a.mc=Math.max(a.mc,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.mc);if(0>b)throw new FS.$b(28);return b},Lc(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.$b(43);a=a.node.dc;if(e&2||!a||a.buffer!==x.buffer){d=!0;e=wb(b);if(!e)throw new FS.$b(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);x.set(a,e)}}else d=!1,e=a.byteOffset;return{ec:e,md:d}},Nc(a,b,c,d){J.cc.write(a,b,0,d,c,!1);return 0}}},yb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},zb=async a=>{a=await ca(a);return new Uint8Array(a)},Ab=0,Bb=null,Cb=()=>{Ab--;n.monitorRunDependencies?.(Ab);if(0==Ab&&Bb){var a=Bb;Bb=null;a()}},Db=()=>{Ab++;n.monitorRunDependencies?.(Ab)},Eb=async(a,b)=>{"undefined"!=typeof Oa&&La();for(var c of Ja)if(c.canHandle(b))return c.handle(a,b);return a},Fb=async(a,b,c,d,e,f,g,h)=>{var l=
b?jb(db(a+"/"+b)):a,k=`cp ${l}`;Db(k);try{var m=c;"string"==typeof c&&(m=await zb(c));m=await Eb(m,l);h?.();f||FS.createDataFile(a,b,m,d,e,g)}finally{Cb(k)}};function M(a,b){var c=FS.isDir(a.mode)?(c=Gb(a,"x"))?c:a.bc.Kc?0:2:54;if(c)throw new FS.$b(c);for(c=FS.yc[Hb(a.id,b)];c;c=c.Mc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.Kc(a,b)}function xb(a){var b=Hb(a.parent.id,a.name);if(FS.yc[b]===a)FS.yc[b]=a.Mc;else for(b=FS.yc[b];b;){if(b.Mc===a){b.Mc=a.Mc;break}b=b.Mc}}
function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.yc.length}function Ib(a){var b=Hb(a.parent.id,a.name);a.Mc=FS.yc[b];FS.yc[b]=a}function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(FS.Bd)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Kb(a,b){if(!FS.isDir(a.mode))return 54;try{return M(a,b),20}catch(c){}return Gb(a,"wx")}function Lb(a,b,c){try{var d=M(a,b)}catch(e){return e.hc}if(a=Gb(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.Pc(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Mb(a,b){if(!a)throw new FS.$b(b);return a}function O(a){a=FS.zd(a);if(!a)throw new FS.$b(8);return a}
function Nb(a,b=-1){a=Object.assign(new FS.Id,a);if(-1==b)a:{for(b=0;b<=FS.Jd;b++)if(!FS.streams[b])break a;throw new FS.$b(33);}a.Dc=b;return FS.streams[b]=a}function Ob(a,b=-1){a=Nb(a,b);a.cc?.De?.(a);return a}function Pb(a,b,c){var d=a?.cc.xc;a=d?a:b;d??=b.bc.xc;Mb(d,63);d(a,c)}function Qb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Qc)}return b}
function Rb(a){var b={we:4096,Ge:4096,od:1E6,ve:5E5,ue:5E5,files:FS.jd,Ee:FS.jd-1,He:42,flags:2,Le:255};a.bc.Gd&&Object.assign(b,a.bc.Gd(a.mount.he.root));return b}function Sb(a,b,c,d){Pb(a,b,{mode:c&4095|b.mode&-4096,rc:Date.now(),vd:d})}function Tb(a,b,c){if(FS.isDir(b.mode))throw new FS.$b(31);if(!FS.isFile(b.mode))throw new FS.$b(28);var d=Gb(b,"w");if(d)throw new FS.$b(d);Pb(a,b,{size:c,timestamp:Date.now()})}
function Ub(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=db(a+"/"+b);return FS.create(b,yb(c,d))}function Vb(a){if(!(a.de||a.ee||a.link||a.dc))if("undefined"!=typeof XMLHttpRequest)F("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.dc=(void 0)(a.url)}catch(b){throw new FS.$b(29);}}
var FS={root:null,Qc:[],ud:{},streams:[],jd:1,yc:null,rd:"/",ed:!1,Bd:!0,Sd:null,$c:0,Fd:{},$b:class{name="ErrnoError";constructor(a){this.hc=a}},Id:class{Bc={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Bc.flags}set flags(a){this.Bc.flags=a}get position(){return this.Bc.position}set position(a){this.Bc.position=a}},Hd:class{bc={};cc={};wc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.jd++;this.name=b;this.mode=c;this.Sc=
d;this.Cc=this.sc=this.rc=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ee(){return FS.isDir(this.mode)}get de(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.$b(44);b.Wc??(b.Wc=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-
1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=eb(e),FS.Pc(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=db(e+"/"+a[f]);try{d=M(d,a[f])}catch(h){if(44===h?.hc&&g&&b.ge)return{path:e};throw h;}!d.wc||g&&!b.Wc||(d=d.wc.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.bc.readlink)throw new FS.$b(52);d=d.bc.readlink(d);"/"===d.charAt(0)||(d=eb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.$b(32);},getPath(a){for(var b;;){if(FS.Pc(a))return a=
a.mount.Dd,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.Hd(a,b,c,d);Ib(a);return a},Pc(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},Jd:4096,zd:a=>FS.streams[a],Ld:{open(a){a.cc=FS.Ud(a.node.Sc).cc;a.cc.open?.(a)},llseek(){throw new FS.$b(70);
}},hd:a=>a>>8,Je:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.ud[a]={cc:b}},Ud:a=>FS.ud[a],syncfs(a,b){function c(g){FS.$c--;return b(g)}function d(g){if(g){if(!d.Pd)return d.Pd=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.$c++;1<FS.$c&&q(`warning: ${FS.$c} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Qb(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.$b(10);
if(!d&&c){var e=FS.lookupPath(c,{Wc:!1});c=e.path;e=e.node;if(e.wc)throw new FS.$b(10);if(!FS.isDir(e.mode))throw new FS.$b(54);}b={type:a,he:b,Dd:c,Qc:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.wc=b,e.mount&&e.mount.Qc.push(b));return a},unmount(a){a=FS.lookupPath(a,{Wc:!1});if(!a.node.wc)throw new FS.$b(28);a=a.node;var b=a.wc,c=Qb(b);Object.keys(FS.yc).forEach(d=>{for(d=FS.yc[d];d;){var e=d.Mc;c.includes(d.mount)&&xb(d);d=e}});a.wc=null;a.mount.Qc.splice(a.mount.Qc.indexOf(b),1)},Kc(a,
b){return a.bc.Kc(a,b)},Ec(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=fb(a);if(!a)throw new FS.$b(28);if("."===a||".."===a)throw new FS.$b(20);var e=Kb(d,a);if(e)throw new FS.$b(e);if(!d.bc.Ec)throw new FS.$b(63);return d.bc.Ec(d,a,b,c)},Gd(a){return Rb(FS.lookupPath(a,{follow:!0}).node)},Ne(a){return Rb(a.node)},create(a,b=438){return FS.Ec(a,b&4095|32768,0)},mkdir(a,b=511){return FS.Ec(a,b&1023|16384,0)},Ke(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=
e;try{FS.mkdir(d,b)}catch(f){if(20!=f.hc)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.Ec(a,b|8192,c)},symlink(a,b){if(!jb(a))throw new FS.$b(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.$b(44);b=fb(b);var d=Kb(c,b);if(d)throw new FS.$b(d);if(!c.bc.symlink)throw new FS.$b(63);return c.bc.symlink(c,b,a)},rename(a,b){var c=eb(a),d=eb(b),e=fb(a),f=fb(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.$b(44);
if(h.mount!==g.mount)throw new FS.$b(75);var l=M(h,e);a=kb(a,d);if("."!==a.charAt(0))throw new FS.$b(28);a=kb(b,c);if("."!==a.charAt(0))throw new FS.$b(55);try{var k=M(g,f)}catch(m){}if(l!==k){b=FS.isDir(l.mode);if(e=Lb(h,e,b))throw new FS.$b(e);if(e=k?Lb(g,f,b):Kb(g,f))throw new FS.$b(e);if(!h.bc.rename)throw new FS.$b(63);if(l.wc||k&&k.wc)throw new FS.$b(10);if(g!==h&&(e=Gb(h,"w")))throw new FS.$b(e);xb(l);try{h.bc.rename(l,g,f),l.parent=g}catch(m){throw m;}finally{Ib(l)}}},rmdir(a){var b=FS.lookupPath(a,
{parent:!0}).node;a=fb(a);var c=M(b,a),d=Lb(b,a,!0);if(d)throw new FS.$b(d);if(!b.bc.rmdir)throw new FS.$b(63);if(c.wc)throw new FS.$b(10);b.bc.rmdir(b,a);xb(c)},Tc(a){a=FS.lookupPath(a,{follow:!0}).node;return Mb(a.bc.Tc,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.$b(44);a=fb(a);var c=M(b,a),d=Lb(b,a,!1);if(d)throw new FS.$b(d);if(!b.bc.unlink)throw new FS.$b(63);if(c.wc)throw new FS.$b(10);b.bc.unlink(b,a);xb(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.$b(44);
if(!a.bc.readlink)throw new FS.$b(28);return a.bc.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Mb(a.bc.vc,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Sb(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=O(a);Sb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Pb(null,a,{timestamp:Date.now(),vd:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=O(a);Pb(a,a.node,{timestamp:Date.now(),
vd:!1})},truncate(a,b){if(0>b)throw new FS.$b(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Tb(null,a,b)},ftruncate(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new FS.$b(28);Tb(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Mb(a.bc.xc,63)(a,{Cc:b,sc:c})},open(a,b,c=438){if(""===a)throw new FS.$b(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:
0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=FS.lookupPath(a,{follow:!(b&131072),ge:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.$b(20);}else{if(e)throw new FS.$b(31);d=FS.Ec(a,c|511,0);f=!0}if(!d)throw new FS.$b(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.$b(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==Jb(g)||g&576)?31:Gb(e,Jb(g)):44)throw new FS.$b(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=Nb({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,cc:d.cc,te:[],error:!1});e.cc.open&&e.cc.open(e);f&&FS.chmod(d,c&511);!n.logReadFiles||b&1||a in FS.Fd||(FS.Fd[a]=1);return e},close(a){if(null===a.Dc)throw new FS.$b(8);a.dd&&(a.dd=null);try{a.cc.close&&a.cc.close(a)}catch(b){throw b;}finally{FS.streams[a.Dc]=null}a.Dc=null},llseek(a,b,c){if(null===a.Dc)throw new FS.$b(8);if(!a.seekable||!a.cc.llseek)throw new FS.$b(70);if(0!=c&&1!=c&&2!=c)throw new FS.$b(28);a.position=a.cc.llseek(a,b,c);a.te=[];
return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.$b(28);if(null===a.Dc)throw new FS.$b(8);if(1===(a.flags&2097155))throw new FS.$b(8);if(FS.isDir(a.node.mode))throw new FS.$b(31);if(!a.cc.read)throw new FS.$b(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.$b(70);b=a.cc.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.$b(28);if(null===a.Dc)throw new FS.$b(8);if(0===(a.flags&2097155))throw new FS.$b(8);if(FS.isDir(a.node.mode))throw new FS.$b(31);
if(!a.cc.write)throw new FS.$b(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.$b(70);b=a.cc.write(a,b,c,d,e,f);g||(a.position+=b);return b},Lc(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.$b(2);if(1===(a.flags&2097155))throw new FS.$b(2);if(!a.cc.Lc)throw new FS.$b(43);if(!b)throw new FS.$b(28);return a.cc.Lc(a,b,c,d,e)},Nc(a,b,c,d,e){return a.cc.Nc?a.cc.Nc(a,b,c,d,e):0},fd(a,b,c){if(!a.cc.fd)throw new FS.$b(59);
return a.cc.fd(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&F(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=lb(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(pb(b)));ArrayBuffer.isView(b)?FS.write(a,b,0,b.byteLength,void 0,c.Ce):F("Unsupported data type");
FS.close(a)},cwd:()=>FS.rd,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.$b(44);if(!FS.isDir(a.node.mode))throw new FS.$b(54);var b=Gb(a.node,"x");if(b)throw new FS.$b(b);FS.rd=a.path},init(a,b,c){FS.ed=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",
0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Fe(a,b){a=FS.analyzePath(a,b);return a.xd?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={Pc:!1,xd:!1,error:0,name:null,path:null,object:null,ie:!1,ke:null,je:null};try{c=FS.lookupPath(a,{parent:!0}),d.ie=!0,d.ke=c.path,d.je=c.node,d.name=fb(a),c=FS.lookupPath(a,{follow:!b}),d.xd=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Pc="/"===c.path}catch(e){d.error=e.hc}return d},createPath(a,b){a=
"string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=db(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.hc)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?db(a+"/"+b):a);a=yb(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,
b,c,d){a=gb("string"==typeof a?a:FS.getPath(a),b);b=yb(!!c,!!d);var e;(e=FS.createDevice).hd??(e.hd=64);e=FS.makedev(FS.createDevice.hd++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,l){for(var k=0,m=0;m<l;m++){try{var p=c()}catch(t){throw new FS.$b(29);}if(void 0===p&&0===k)throw new FS.$b(6);if(null===p||void 0===p)break;k++;g[h+m]=p}k&&(f.node.Cc=Date.now());return k},write(f,g,h,l){for(var k=0;k<l;k++)try{d(g[h+k])}catch(m){throw new FS.$b(29);}l&&
(f.node.sc=f.node.rc=Date.now());return k}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(p,t,r,u,w){p=p.node.dc;if(w>=p.length)return 0;u=Math.min(p.length-w,u);if(p.slice)for(var E=0;E<u;E++)t[r+E]=p[w+E];else for(E=0;E<u;E++)t[r+E]=p.get(w+E);return u}class g{ad=!1;Bc=[];Oc=void 0;pd=0;nd=0;get(p){if(!(p>this.length-1||0>p)){var t=p%this.wd;return this.Oc(p/this.wd|0)[t]}}Qd(p){this.Oc=p}sd(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);200<=p.status&&300>p.status||
304===p.status||F("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),r,u=(r=p.getResponseHeader("Accept-Ranges"))&&"bytes"===r;p=(r=p.getResponseHeader("Content-Encoding"))&&"gzip"===r;var w=1048576;u||(w=t);var E=this;E.Qd(K=>{var H=K*w,N=(K+1)*w-1;N=Math.min(N,t-1);if("undefined"==typeof E.Bc[K]){var Ea=E.Bc;H>N&&F("invalid range ("+H+", "+N+") or no bytes requested!");N>t-1&&F("only "+t+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",
c,!1);t!==w&&L.setRequestHeader("Range","bytes="+H+"-"+N);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);200<=L.status&&300>L.status||304===L.status||F("Couldn't load "+c+". Status: "+L.status);H=void 0!==L.response?new Uint8Array(L.response||[]):pb(L.responseText||"");Ea[K]=H}"undefined"==typeof E.Bc[K]&&F("doXHR failed!");return E.Bc[K]});if(p||!t)w=t=1,w=t=this.Oc(0).length,da("LazyFiles on gzip forces download of the whole file when length is accessed");
this.pd=t;this.nd=w;this.ad=!0}get length(){this.ad||this.sd();return this.pd}get wd(){this.ad||this.sd();return this.nd}}if("undefined"!=typeof XMLHttpRequest){F("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var l=void 0}else l=c,h=void 0;var k=Ub(a,b,d,e);h?k.dc=h:l&&(k.dc=null,k.url=l);Object.defineProperties(k,{mc:{get:function(){return this.dc.length}}});var m={};Object.keys(k.cc).forEach(p=>{var t=k.cc[p];m[p]=
(...r)=>{Vb(k);return t(...r)}});m.read=(p,t,r,u,w)=>{Vb(k);return f(p,t,r,u,w)};m.Lc=(p,t,r)=>{Vb(k);var u=wb(t);if(!u)throw new FS.$b(48);f(p,x,u,t,r);return{ec:u,md:!0}};k.cc=m;return k}};function Wb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():O(a).path;if(0==b.length){if(!c)throw new FS.$b(44);return a}return a+"/"+b}
function Xb(a,b){C[a>>2]=b.Nd;C[a+4>>2]=b.mode;C[a+8>>2]=b.fe;C[a+12>>2]=b.uid;C[a+16>>2]=b.Yd;C[a+20>>2]=b.Sc;D[a+24>>3]=BigInt(b.size);B[a+32>>2]=4096;B[a+36>>2]=b.od;var c=b.Cc.getTime(),d=b.sc.getTime(),e=b.rc.getTime();D[a+40>>3]=BigInt(Math.floor(c/1E3));C[a+48>>2]=c%1E3*1E6;D[a+56>>3]=BigInt(Math.floor(d/1E3));C[a+64>>2]=d%1E3*1E6;D[a+72>>3]=BigInt(Math.floor(e/1E3));C[a+80>>2]=e%1E3*1E6;D[a+88>>3]=BigInt(b.$d);return 0}
var Yb=void 0,Zb=()=>{var a=B[+Yb>>2];Yb+=4;return a},$b={},ac=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function bc(a){return this.ic(C[a>>2])}
var cc={},dc={},ec={},fc=class extends Error{constructor(a){super(a);this.name="InternalError"}},Q=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new fc("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],h[l])}a.forEach(h=>ec[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{dc.hasOwnProperty(h)?e[l]=dc[h]:(f.push(h),cc.hasOwnProperty(h)||(cc[h]=[]),cc[h].push(()=>{e[l]=dc[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},R=a=>{for(var b="";;){var c=y[a++];if(!c)return b;
b+=String.fromCharCode(c)}},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},gc=a=>{throw new S(a);};function hc(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(dc.hasOwnProperty(a)){if(c.Zd)return;throw new S(`Cannot register type '${d}' twice`);}dc[a]=b;delete ec[a];cc.hasOwnProperty(a)&&(b=cc[a],delete cc[a],b.forEach(e=>e()))}function P(a,b,c={}){return hc(a,b,c)}
var ic=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>y[d];case 2:return c?d=>z[d>>1]:d=>A[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];case 8:return c?d=>D[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},jc=a=>{throw new S(a.ac.kc.fc.name+" instance already deleted");},kc=!1,lc=!1,mc=()=>{},nc=a=>{if(kc)return nc=b=>b.deleteLater(),nc(a);if("undefined"===typeof FinalizationRegistry)return nc=b=>b,a;lc=new FinalizationRegistry(b=>{b=b.ac;--b.count.value;0===b.count.value&&
(b.oc?b.uc.Ac(b.oc):b.kc.fc.Ac(b.ec))});nc=b=>{var c=b.ac;c.oc&&lc.register(b,{ac:c},b);return b};mc=b=>{lc.unregister(b)};return nc(a)},oc=[],pc=()=>{for(;oc.length;){var a=oc.pop();a.ac.Jc=!1;a["delete"]()}},qc;function rc(){}
var sc=(a,b)=>Object.defineProperty(b,"name",{value:a}),tc={},uc=(a,b,c)=>{if(void 0===a[b].lc){var d=a[b];a[b]=function(...e){if(!a[b].lc.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].lc})!`);return a[b].lc[e.length].apply(this,e)};a[b].lc=[];a[b].lc[d.Hc]=d}},vc=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].lc&&void 0!==n[a].lc[c])throw new S(`Cannot register public name '${a}' twice`);uc(n,
a,a);if(n[a].lc.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].lc[c]=b}else n[a]=b,n[a].Hc=c},wc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function xc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Gc=c;this.Ac=d;this.qc=e;this.Td=f;this.Uc=g;this.Od=h;this.ne=[]}
var yc=(a,b,c)=>{for(;b!==c;){if(!b.Uc)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Uc(a);b=b.qc}return a},zc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Ac(a,b){if(null===b){if(this.gd)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.ac)throw new S(`Cannot pass "${zc(b)}" as a ${this.name}`);if(!b.ac.ec)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return yc(b.ac.ec,b.ac.kc.fc,this.fc)}
function Bc(a,b){if(null===b){if(this.gd)throw new S(`null is not a valid ${this.name}`);if(this.Zc){var c=this.ld();null!==a&&a.push(this.Ac,c);return c}return 0}if(!b||!b.ac)throw new S(`Cannot pass "${zc(b)}" as a ${this.name}`);if(!b.ac.ec)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Yc&&b.ac.kc.Yc)throw new S(`Cannot convert argument of type ${b.ac.uc?b.ac.uc.name:b.ac.kc.name} to parameter type ${this.name}`);c=yc(b.ac.ec,b.ac.kc.fc,this.fc);if(this.Zc){if(void 0===
b.ac.oc)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.se){case 0:if(b.ac.uc===this)c=b.ac.oc;else throw new S(`Cannot convert argument of type ${b.ac.uc?b.ac.uc.name:b.ac.kc.name} to parameter type ${this.name}`);break;case 1:c=b.ac.oc;break;case 2:if(b.ac.uc===this)c=b.ac.oc;else{var d=b.clone();c=this.oe(c,T(()=>d["delete"]()));null!==a&&a.push(this.Ac,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Cc(a,b){if(null===b){if(this.gd)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.ac)throw new S(`Cannot pass "${zc(b)}" as a ${this.name}`);if(!b.ac.ec)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ac.kc.Yc)throw new S(`Cannot convert argument of type ${b.ac.kc.name} to parameter type ${this.name}`);return yc(b.ac.ec,b.ac.kc.fc,this.fc)}
var Dc=(a,b,c)=>{if(b===c)return a;if(void 0===c.qc)return null;a=Dc(a,b,c.qc);return null===a?null:c.Od(a)},Ec={},Fc=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.qc;)b=a.Uc(b),a=a.qc;return Ec[b]},Gc=(a,b)=>{if(!b.kc||!b.ec)throw new fc("makeClassHandle requires ptr and ptrType");if(!!b.uc!==!!b.oc)throw new fc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return nc(Object.create(a,{ac:{value:b,writable:!0}}))};
function Hc(a,b,c,d,e,f,g,h,l,k,m){this.name=a;this.fc=b;this.gd=c;this.Yc=d;this.Zc=e;this.le=f;this.se=g;this.Ed=h;this.ld=l;this.oe=k;this.Ac=m;e||void 0!==b.qc?this.nc=Bc:(this.nc=d?Ac:Cc,this.pc=null)}var Ic=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new fc("Replacing nonexistent public symbol");void 0!==n[a].lc&&void 0!==c?n[a].lc[c]=b:(n[a]=b,n[a].Hc=c)},U=(a,b)=>{a=R(a);var c=I(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};
class Jc extends Error{}var Lc=a=>{a=Kc(a);var b=R(a);V(a);return b},Mc=(a,b)=>{function c(f){e[f]||dc[f]||(ec[f]?ec[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Jc(`${a}: `+d.map(Lc).join([", "]));};function Nc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].pc)return!0;return!1}
function Oc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=Nc(b);c=!b[0].Cd;var k=b[0],m=b[1];d=[a,gc,d,e,ac,k.ic.bind(k),m?.nc.bind(m)];for(e=2;e<g;++e)k=b[e],d.push(k.nc.bind(k));if(!l)for(e=h?1:2;e<b.length;++e)null!==b[e].pc&&d.push(b[e].pc);l=Nc(b);e=b.length-2;m=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),k.push(`arg${g}Wired`);m=m.join(",");k=k.join(",");
m=`return function (${m}) {\n`;l&&(m+="var destructors = [];\n");var p=l?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${p}, this);\n`);for(g=0;g<e;++g){var r=`toArg${g}Wire`;m+=`var arg${g}Wired = ${r}(${p}, arg${g});\n`;t.push(r)}m+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].pc&&(m+=`${f}_dtor(${f});\n`,t.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(t,m+"}\n"))(...d);return sc(a,b)}
var Pc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},Qc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Rc=(a,b,c)=>{if(!(a instanceof Object))throw new S(`${c} with invalid "this": ${a}`);if(!(a instanceof b.fc.constructor))throw new S(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.ac.ec)throw new S(`cannot call emscripten binding method ${c} on deleted object`);return yc(a.ac.ec,a.ac.kc.fc,b.fc)},Sc=[],Tc=[0,1,,1,null,1,!0,1,!1,1],Uc=a=>
{9<a&&0===--Tc[a+1]&&(Tc[a]=void 0,Sc.push(a))},W=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return Tc[a]},T=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Sc.pop()||Tc.length;Tc[b]=a;Tc[b+1]=1;return b}},Vc={name:"emscripten::val",ic:a=>{var b=W(a);Uc(a);return b},nc:(a,b)=>T(b),tc:bc,pc:null},Wc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.ic(x[d])}:function(d){return this.ic(y[d])};case 2:return c?function(d){return this.ic(z[d>>
1])}:function(d){return this.ic(A[d>>1])};case 4:return c?function(d){return this.ic(B[d>>2])}:function(d){return this.ic(C[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xc=(a,b)=>{var c=dc[a];if(void 0===c)throw a=`${b} has unknown type ${Lc(a)}`,new S(a);return c},Yc=(a,b)=>{switch(b){case 4:return function(c){return this.ic(oa[c>>2])};case 8:return function(c){return this.ic(pa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Zc=Object.assign({optional:!0},
Vc),$c=new TextDecoder("utf-16le"),ad=(a,b,c)=>{a>>=1;return $c.decode(A.subarray(a,Ta(A,a,b/2,c)))},bd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},cd=a=>2*a.length,dd=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=C[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ed=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},fd=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},gd=[],hd=a=>{var b=gd.length;gd.push(a);return b},jd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Xc(C[b+4*d>>2],`parameter ${d}`);return c},kd=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(C[b>>2]=T(d));return a},ld={},md=a=>{var b=ld[a];return void 0===b?R(a):b},nd=globalThis,od=[0,31,60,91,121,152,182,213,244,274,305,335],pd=[0,31,59,90,120,151,181,212,243,273,
304,334],qd={},rd={},td=()=>{if(!sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in rd)void 0===rd[b]?delete a[b]:a[b]=rd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);sd=c}return sd},sd,ud=[],vd=a=>{const b=a.length;return[b%128|128,b>>7,...a]},wd={i:127,p:127,j:126,f:125,d:124,e:111},xd=a=>vd(Array.from(a,b=>wd[b])),yd=[],zd,ka=a=>{var b=X(),c=
Ad(4),d=Ad(4);Bd(a,c,d);a=C[c>>2];d=C[d>>2];c=G(a);V(a);if(d){var e=G(d);V(d)}Y(b);return[c,e]};FS.createPreloadedFile=(a,b,c,d,e,f,g,h,l,k)=>{Fb(a,b,c,d,e,h,l,k).then(f).catch(g)};FS.Me=Fb;FS.yc=Array(4096);FS.mount(J,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));rb(FS.makedev(5,0),tb);rb(FS.makedev(6,0),ub);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(ib(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.cc={llseek:J.cc.llseek};b.bc={Kc(c,d){c=+d;var e=O(c);c={parent:null,mount:{Dd:"fake"},bc:{readlink:()=>e.path},id:c+1};return c.parent=c},Tc(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Sd={MEMFS:J};
(()=>{let a=rc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof rc&&c instanceof rc))return!1;var d=this.ac.kc.fc,e=this.ac.ec;c.ac=c.ac;var f=c.ac.kc.fc;for(c=c.ac.ec;d.qc;)e=d.Uc(e),d=d.qc;for(;f.qc;)c=f.Uc(c),f=f.qc;return d===f&&e===c},clone:function(){this.ac.ec||jc(this);if(this.ac.Rc)return this.ac.count.value+=1,this;var c=nc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.ac;c=c(e.call(d,f,{ac:{value:{count:g.count,Jc:g.Jc,Rc:g.Rc,ec:g.ec,kc:g.kc,oc:g.oc,uc:g.uc}}}));
c.ac.count.value+=1;c.ac.Jc=!1;return c},["delete"](){this.ac.ec||jc(this);if(this.ac.Jc&&!this.ac.Rc)throw new S("Object already scheduled for deletion");mc(this);var c=this.ac;--c.count.value;0===c.count.value&&(c.oc?c.uc.Ac(c.oc):c.kc.fc.Ac(c.ec));this.ac.Rc||(this.ac.oc=void 0,this.ac.ec=void 0)},isDeleted:function(){return!this.ac.ec},deleteLater:function(){this.ac.ec||jc(this);if(this.ac.Jc&&!this.ac.Rc)throw new S("Object already scheduled for deletion");oc.push(this);1===oc.length&&qc&&qc(pc);
this.ac.Jc=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Hc.prototype,{Vd(a){this.Ed&&(a=this.Ed(a));return a},td(a){this.Ac?.(a)},tc:bc,ic:function(a){function b(){return this.Zc?Gc(this.fc.Gc,{kc:this.le,ec:c,uc:this,oc:a}):Gc(this.fc.Gc,{kc:this,ec:a})}var c=this.Vd(a);if(!c)return this.td(a),null;var d=Fc(this.fc,c);if(void 0!==d){if(0===d.ac.count.value)return d.ac.ec=c,d.ac.oc=a,d.clone();d=d.clone();this.td(a);return d}d=this.fc.Td(c);d=tc[d];if(!d)return b.call(this);d=this.Yc?d.Md:d.pointerType;var e=Dc(c,this.fc,d.fc);return null===
e?b.call(this):this.Zc?Gc(d.fc.Gc,{kc:d,ec:e,uc:this,oc:a}):Gc(d.fc.Gc,{kc:d,ec:e})}});Ra.push(()=>{rd.VIPS_MAX_THREADS=1;rd.VIPS_CONCURRENCY=1});
yd.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>T(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(W(d)))}})});Object.assign(rc.prototype,{preventAutoDelete:function(){const a=oc.indexOf(this);-1<a&&oc.splice(a,1);this.ac.Jc=!1;return this}});
n.preloadPlugins&&(Ja=n.preloadPlugins);n.noExitRuntime&&(Ba=n.noExitRuntime);n.print&&(da=n.print);n.printErr&&(q=n.printErr);n.wasmBinary&&(ea=n.wasmBinary);n.thisProgram&&(aa=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();n.ENV=rd;n.addRunDependency=Db;n.removeRunDependency=Cb;
n.addFunction=(a,b)=>{if(!zd){zd=new WeakMap;var c=Va.length;if(zd)for(var d=0;d<0+c;d++){var e=I(d);e&&zd.set(e,d)}}if(c=zd.get(a)||0)return c;c=ud.length?ud.pop():Va.grow(1);try{Va.set(c,a),Ua[c]=Va.get(c)}catch(f){if(!(f instanceof TypeError))throw f;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...vd([1,96,...xd(b.slice(1)),...xd("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;Va.set(c,b);Ua[c]=Va.get(c)}zd.set(a,
c);return c};n.FS_preloadFile=Fb;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{kc=a};n.deletionQueue=oc;n.setDelayFunction=a=>{qc=a;oc.length&&qc&&qc(pc)};n.incrementExceptionRefcount=a=>Cd(a);n.decrementExceptionRefcount=a=>Dd(a);n.getExceptionMessage=a=>ka(a);
function Ed(a){for(var b=A[a+6>>1];13===b&&!(16<C[a>>2]);){var c=C[a+8>>2],d=C[c>>2];if(0===d){b=0;break}else if(0===C[(c>>2)+1])a=d,b=A[d+6>>1];else break}return[a,b]}
var Kc,Fd,Gd,V,Fa,Dd,Cd,Da,vb,Hd,Z,$a,Y,Ad,X,Bd,ab,Id,te={g:(a,b,c,d)=>F(`Assertion failed: ${G(a)}, at: `+[b?G(b):"unknown filename",c,d?G(d):"unknown function"]),Ba:(a,b)=>I(a)(b),$:a=>{var b=new Za(a);0==x[b.ec+12]&&(x[b.ec+12]=1,Xa--);x[b.ec+13]=0;Wa.push(b);Cd(a);return Id(a)},_a:()=>{Z(0,0);var a=Wa.pop();Dd(a.cd);Ya=0},a:()=>bb([]),f:a=>bb([a]),N:(a,b,c)=>{(new Za(a)).init(b,c);Ya=new ja(a);Xa++;throw Ya;},c:a=>{Ya||=new ja(a);throw Ya;},Qa:function(a){try{var b=O(a);return Ob(b).Dc}catch(c){if("undefined"==
typeof FS||"ErrnoError"!==c.name)throw c;return-c.hc}},Sa:function(a,b,c){try{b=G(b);b=Wb(a,b);if(c&-8)return-28;var d=FS.lookupPath(b,{follow:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Gb(d,a)?-2:0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.hc}},ka:function(a,b,c){Yb=c;try{var d=O(a);switch(b){case 0:var e=Zb();if(0>e)break;for(;FS.streams[e];)e++;return Ob(d,e).Dc;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=
Zb(),d.flags|=e,0;case 12:return e=Zb(),z[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.hc}},Pa:function(a,b){try{var c=O(a),d=c.node,e=c.cc.vc;a=e?c:d;e??=d.bc.vc;Mb(e,63);var f=e(a);return Xb(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.hc}},La:function(a,b){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==
typeof FS||"ErrnoError"!==c.name)throw c;return-c.hc}},Ka:function(a,b){try{if(0===b)return-28;var c=FS.cwd(),d=nb(c)+1;if(b<d)return-68;ob(c,y,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.hc}},Xa:function(a,b,c){Yb=c;try{var d=O(a);switch(b){case 21509:return d.jc?0:-59;case 21505:if(!d.jc)return-59;if(d.jc.Fc.ae){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Zb();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=
35387;for(var f=0;32>f;f++)x[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.jc?0:-59;case 21506:case 21507:case 21508:if(!d.jc)return-59;if(d.jc.Fc.be)for(e=Zb(),a=[],f=0;32>f;f++)a.push(x[e+f+17]);return 0;case 21519:if(!d.jc)return-59;e=Zb();return B[e>>2]=0;case 21520:return d.jc?-28:-59;case 21537:case 21531:return e=Zb(),FS.fd(d,b,e);case 21523:if(!d.jc)return-59;d.jc.Fc.ce&&(f=[24,80],e=Zb(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.jc?0:-59;case 21515:return d.jc?
0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.hc}},Na:function(a,b){try{return a=G(a),Xb(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.hc}},Ma:function(a,b,c,d){try{b=G(b);var e=d&256;b=Wb(a,b,d&4096);return Xb(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.hc}},Y:function(a,b,c,d){Yb=d;try{b=G(b);b=Wb(a,b);var e=d?Zb():0;return FS.open(b,c,e).Dc}catch(f){if("undefined"==
typeof FS||"ErrnoError"!==f.name)throw f;return-f.hc}},Da:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=z[e+4>>1],g=32,h=FS.zd(B[e>>2]);h&&(g=5,h.cc.me&&(g=h.cc.me(h,-1)));(g&=f|24)&&c++;z[e+6>>1]=g}return c}catch(l){if("undefined"==typeof FS||"ErrnoError"!==l.name)throw l;return-l.hc}},Aa:function(a){try{return a=G(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.hc}},Oa:function(a,b){try{return a=G(a),Xb(b,FS.stat(a))}catch(c){if("undefined"==
typeof FS||"ErrnoError"!==c.name)throw c;return-c.hc}},ha:function(a,b,c){try{b=G(b);b=Wb(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.hc}},Ta:()=>F(""),gb:a=>{var b=$b[a];delete $b[a];var c=b.ld,d=b.Ac,e=b.yd,f=e.map(g=>g.Xd).concat(e.map(g=>g.qe));Q([a],f,g=>{var h={};e.forEach((l,k)=>{var m=g[k],p=l.Oc,t=l.Wd,r=g[k+e.length],u=l.pe,w=l.re;h[l.Rd]={read:E=>m.ic(p(t,E)),write:(E,K)=>{var H=[];
u(w,E,r.nc(H,K));ac(H)},optional:g[k].optional}});return[{name:b.name,ic:l=>{var k={},m;for(m in h)k[m]=h[m].read(l);d(l);return k},nc:(l,k)=>{for(var m in h)if(!(m in k||h[m].optional))throw new TypeError(`Missing field: "${m}"`);var p=c();for(m in h)h[m].write(p,k[m]);null!==l&&l.push(d,p);return p},tc:bc,pc:d}]})},pa:(a,b,c,d,e)=>{b=R(b);if(d)a:switch(c){case 4:d=oa;break a;case 8:d=pa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?x:y;break a;
case 2:d=e?z:A;break a;case 4:d=e?B:C;break a;case 8:d=e?D:qa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);P(a,{name:b,ic:h=>{var l=h+Math.max(4,c)>>g;l=Array.from(f.subarray(l,l+C[h>>2]));V(h);return l},nc:(h,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new S(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var k=l.length,m=Math.max(4,c),p=Fd(m+k*c);m=p+m>>g;C[p>>2]=k;f.set(l,m);null!==h&&h.push(V,
p);return p},tc:bc,pc(h){V(h)}})},na:(a,b,c,d,e)=>{b=R(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}P(a,{name:b,ic:f,nc:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},tc:ic(b,c,!d),pc:null})},db:(a,b,c,d)=>{b=R(b);P(a,{name:b,ic:function(e){return!!e},nc:function(e,f){return f?c:d},tc:function(e){return this.ic(y[e])},pc:null})},A:(a,b,c,d,e,f,g,h,l,k,m,p,t)=>{m=R(m);f=U(e,f);h&&=U(g,h);k&&=U(l,k);t=U(p,t);var r=wc(m);vc(r,function(){Mc(`Cannot construct ${m} due to unbound types`,
[d])});Q([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.fc;var E=w.Gc}else E=rc.prototype;u=sc(m,function(...Ea){if(Object.getPrototypeOf(this)!==K)throw new S(`Use 'new' to construct ${m}`);if(void 0===H.Ic)throw new S(`${m} has no accessible constructor`);var L=H.Ic[Ea.length];if(void 0===L)throw new S(`Tried to invoke ctor of ${m} with invalid number of parameters (${Ea.length}) - expected (${Object.keys(H.Ic).toString()}) parameters instead!`);return L.apply(this,Ea)});var K=Object.create(E,{constructor:{value:u}});
u.prototype=K;var H=new xc(m,u,K,t,w,f,h,k);if(H.qc){var N;(N=H.qc).Vc??(N.Vc=[]);H.qc.Vc.push(H)}w=new Hc(m,H,!0,!1,!1);N=new Hc(m+"*",H,!1,!1,!1);E=new Hc(m+" const*",H,!1,!0,!1);tc[a]={pointerType:N,Md:E};Ic(r,u);return[w,N,E]})},m:(a,b,c,d,e,f,g,h)=>{var l=Pc(c,d);b=R(b);b=Qc(b);f=U(e,f);Q([],[a],k=>{function m(){Mc(`Cannot call ${p} due to unbound types`,l)}k=k[0];var p=`${k.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=k.fc.constructor;void 0===t[b]?(m.Hc=c-1,t[b]=m):(uc(t,
b,p),t[b].lc[c-1]=m);Q([],l,r=>{r=Oc(p,[r[0],null].concat(r.slice(1)),null,f,g,h);void 0===t[b].lc?(r.Hc=c-1,t[b]=r):t[b].lc[c-1]=r;if(k.fc.Vc)for(const u of k.fc.Vc)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})},C:(a,b,c,d,e,f)=>{var g=Pc(b,c);e=U(d,e);Q([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.fc.Ic&&(h.fc.Ic=[]);if(void 0!==h.fc.Ic[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.fc.Ic[b-1]=()=>{Mc(`Cannot construct ${h.name} due to unbound types`,g)};Q([],g,k=>{k.splice(1,0,null);h.fc.Ic[b-1]=Oc(l,k,null,e,f);return[]});return[]})},h:(a,b,c,d,e,f,g,h,l)=>{var k=Pc(c,d);b=R(b);b=Qc(b);f=U(e,f);Q([],[a],m=>{function p(){Mc(`Cannot call ${t} due to unbound types`,k)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.fc.ne.push(b);var r=m.fc.Gc,u=r[b];void 0===u||void 0===u.lc&&u.className!==m.name&&u.Hc===c-2?(p.Hc=c-2,p.className=m.name,r[b]=
p):(uc(r,b,t),r[b].lc[c-2]=p);Q([],k,w=>{w=Oc(t,w,m,f,g,l);void 0===r[b].lc?(w.Hc=c-2,r[b]=w):r[b].lc[c-2]=w;return[]});return[]})},w:(a,b,c,d,e,f,g,h,l,k)=>{b=R(b);e=U(d,e);Q([],[a],m=>{m=m[0];var p=`${m.name}.${b}`,t={get(){Mc(`Cannot access ${p} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=l?()=>Mc(`Cannot access ${p} due to unbound types`,[c,g]):()=>{throw new S(p+" is a read-only property");};Object.defineProperty(m.fc.Gc,b,t);Q([],l?[c,g]:[c],r=>{var u=r[0],w={get(){var K=
Rc(this,m,p+" getter");return u.ic(e(f,K))},enumerable:!0};if(l){l=U(h,l);var E=r[1];w.set=function(K){var H=Rc(this,m,p+" setter"),N=[];l(k,H,E.nc(N,K));ac(N)}}Object.defineProperty(m.fc.Gc,b,w);return[]});return[]})},bb:a=>P(a,Vc),s:(a,b,c,d)=>{function e(){}b=R(b);e.values={};P(a,{name:b,constructor:e,ic:function(f){return this.constructor.values[f]},nc:(f,g)=>g.value,tc:Wc(b,c,d),pc:null});vc(b,e)},k:(a,b,c)=>{var d=Xc(a,"enum");b=R(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},
constructor:{value:sc(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},ma:(a,b,c)=>{b=R(b);P(a,{name:b,ic:d=>d,nc:(d,e)=>e,tc:Yc(b,c),pc:null})},I:(a,b,c,d,e,f,g)=>{var h=Pc(b,c);a=R(a);a=Qc(a);e=U(d,e);vc(a,function(){Mc(`Cannot call ${a} due to unbound types`,h)},b-1);Q([],h,l=>{Ic(a,Oc(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})},H:(a,b,c,d,e)=>{b=R(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}P(a,{name:b,ic:f,nc:(h,l)=>l,tc:ic(b,c,0!==d),pc:null})},x:(a,b,
c)=>{function d(f){return new e(x.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);P(a,{name:c,ic:d,tc:d},{Zd:!0})},qa:a=>{P(a,Zc)},cb:(a,b)=>{b=R(b);P(a,{name:b,ic(c){var d=G(c+4,C[c>>2],!0);V(c);return d},nc(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");
var f=e?nb(d):d.length;var g=Fd(4+f+1),h=g+4;C[g>>2]=f;e?ob(d,y,h,f+1):y.set(d,h);null!==c&&c.push(V,g);return g},tc:bc,pc(c){V(c)}})},_:(a,b,c)=>{c=R(c);if(2===b){var d=ad;var e=bd;var f=cd}else d=dd,e=ed,f=fd;P(a,{name:c,ic:g=>{var h=d(g+4,C[g>>2]*b,!0);V(g);return h},nc:(g,h)=>{if("string"!=typeof h)throw new S(`Cannot pass non-string to C++ string type ${c}`);var l=f(h),k=Fd(4+l+b);C[k>>2]=l/b;e(h,k+4,l+b);null!==g&&g.push(V,k);return k},tc:bc,pc(g){V(g)}})},ra:(a,b,c,d,e,f)=>{$b[a]={name:R(b),
ld:U(c,d),Ac:U(e,f),yd:[]}},hb:(a,b,c,d,e,f,g,h,l,k)=>{$b[a].yd.push({Rd:R(b),Xd:c,Oc:U(d,e),Wd:f,qe:g,pe:U(h,l),re:k})},eb:(a,b)=>{b=R(b);P(a,{Cd:!0,name:b,ic:()=>{},nc:()=>{}})},Ca:()=>{Ba=!1;Aa=0},wa:()=>{throw new ia;},v:(a,b,c)=>{var [d,...e]=jd(a,b);b=d.nc.bind(d);var f=e.map(l=>l.tc.bind(l));a--;var g={toValue:W};a=f.map((l,k)=>{var m=`argFromPtr${k}`;g[m]=l;return`${m}(args${k?"+"+8*k:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";
break;case 1:g.getStringOrSymbol=md,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.Cd||(g.toReturnWire=b,g.emval_returnValue=kd,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return hd(sc(h,c))},fb:Uc,y:a=>{if(!a)return T(nd);a=md(a);return T(nd[a])},P:a=>{a=md(a);return T(n[a])},
Wa:(a,b)=>{a=W(a);b=W(b);return T(a[b])},E:a=>{9<a&&(Tc[a+1]+=1)},nb:(a,b)=>{a=W(a);b=W(b);return a instanceof b},u:(a,b,c,d,e)=>gd[a](b,c,d,e),sa:a=>{a=W(a);return"number"==typeof a},U:a=>{a=W(a);return"string"==typeof a},J:a=>T(md(a)),oa:a=>T(G(a)),ob:a=>{var b=W(a);ac(b);Uc(a)},jb:(a,b,c)=>{a=W(a);b=W(b);c=W(c);a[b]=c},lb:a=>{a=W(a);return T(typeof a)},Ga:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getUTCSeconds();B[b+4>>2]=a.getUTCMinutes();
B[b+8>>2]=a.getUTCHours();B[b+12>>2]=a.getUTCDate();B[b+16>>2]=a.getUTCMonth();B[b+20>>2]=a.getUTCFullYear()-1900;B[b+24>>2]=a.getUTCDay();B[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},Ha:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=a.getFullYear();B[b+
28>>2]=(0!==c%4||0===c%100&&0!==c%400?pd:od)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Ea:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=O(d),l=FS.Lc(h,a,e,b,c),k=l.ec;B[f>>2]=l.md;C[g>>2]=k;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;
return-m.hc}},Fa:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=O(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.$b(43);d&2||FS.Nc(g,y.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.hc}},va:(a,b)=>{qd[a]&&(clearTimeout(qd[a].id),delete qd[a]);if(!b)return 0;var c=setTimeout(()=>{delete qd[a];Ha(()=>Hd(a,performance.now()))},b);qd[a]={id:c,Oe:b};return 0},Va:(a,b,c,d)=>{var e=(new Date).getFullYear(),
f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();C[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(ob(a,y,c,17),ob(b,y,d,17)):(ob(a,y,d,17),ob(b,y,c,17))},Ra:function(a,b,c){if(!(0<=a&&3>=a))return 28;D[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},F:()=>Date.now(),ga:a=>q(G(a)),ib:()=>{Aa+=1;throw"unwind";
},za:()=>2147483648,X:()=>performance.now(),xa:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Ya:(a,b)=>{var c=0,d=0,e;for(e of td()){var f=b+c;C[a+d>>2]=f;c+=ob(e,y,f,Infinity)+1;d+=4}return 0},Za:(a,b)=>{var c=td();C[a>>2]=c.length;a=0;for(var d of c)a+=
nb(d)+1;C[b>>2]=a;return 0},B:Ga,S:function(a){try{var b=O(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.hc}},Ja:function(a,b){try{var c=O(a),d=c.jc?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;x[b]=d;z[b+2>>1]=0;D[b+8>>3]=BigInt(0);D[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.hc}},ja:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],l=C[a+4>>2];a+=8;var k=FS.read(e,
x,h,l,f);if(0>k){var m=-1;break a}b+=k;if(k<l)break;"undefined"!=typeof f&&(f+=k)}m=b}C[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.hc}},Ia:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=O(a);FS.llseek(e,b,c);D[d>>3]=BigInt(e.position);e.dd&&0===b&&0===c&&(e.dd=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.hc}},ia:function(a,b,c,d){try{a:{var e=O(a);
a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],l=C[a+4>>2];a+=8;var k=FS.write(e,x,h,l,f);if(0>k){var m=-1;break a}b+=k;if(k<l)break;"undefined"!=typeof f&&(f+=k)}m=b}C[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.hc}},la:function(a,b,c,d){var e=C[(a>>2)+1],f=C[(a>>2)+6],g=C[(a>>2)+2],h=C[(a>>2)+5];a=Ed(C[(a>>2)+3])[1];var l=X(),k=l,m=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===
a)m.push(c),p=!0;for(var t=0;t<f;t++){var r=C[(d>>2)+t],u=Ed(C[(g>>2)+t]),w=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(C[r>>2]);break;case 2:m.push(oa[r>>2]);break;case 3:m.push(pa[r>>3]);break;case 5:m.push(y[r]);break;case 6:m.push(x[r]);break;case 7:m.push(A[r>>1]);break;case 8:m.push(z[r>>1]);break;case 11:case 12:m.push(qa[r>>3]);break;case 4:m.push(qa[r>>3]);m.push(qa[(r>>3)+1]);break;case 13:u=C[w>>2];w=A[w+4>>1];k-=u;k&=~(w-1);x.subarray(k,k+u).set(x.subarray(r,r+u));m.push(k);break;
case 14:m.push(C[r>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(t=e-1;t>=f;t--)switch(r=C[(d>>2)+t],u=Ed(C[(g>>2)+t]),w=u[0],u=u[1],u){case 5:case 6:--k;k&=-1;y[k]=y[r];break;case 7:case 8:k-=2;k&=-2;A[k>>1]=A[r>>1];break;case 1:case 9:case 10:case 2:k-=4;k&=-4;C[k>>2]=C[r>>2];break;case 3:case 11:case 12:k-=8;k&=-8;C[k>>2]=C[r>>2];C[(k>>2)+1]=C[(r>>2)+1];break;case 4:k-=16;k&=-8;C[k>>2]=C[r>>2];C[(k>>2)+1]=C[(r>>2)+1];C[(k>>
2)+2]=C[(r>>2)+2];C[(k>>2)+3]=C[(r>>2)+3];break;case 13:k-=4;k&=-4;h.push([k,r,C[w>>2],A[w+4>>1]]);break;case 14:k-=4;k&=-4;C[k>>2]=C[r>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(k);for(t=0;t<h.length;t++)e=h[t],d=e[0],r=e[1],u=e[2],w=e[3],k-=u,k&=~(w-1),x.subarray(k,k+u).set(x.subarray(r,r+u)),C[d>>2]=k}Y(k);Ad(0);b=I(b).apply(null,m);Y(l);if(!p)switch(a){case 0:break;case 1:case 9:case 10:C[c>>2]=b;break;case 2:oa[c>>2]=b;break;
case 3:pa[c>>3]=b;break;case 5:case 6:y[c+0]=b;break;case 7:case 8:A[c>>1]=b;break;case 11:case 12:qa[c>>3]=b;break;case 14:C[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}},T:Jd,D:Kd,q:Ld,d:Md,l:Nd,r:Od,e:Pd,M:Qd,p:Rd,z:Sd,ab:Td,$a:Ud,O:Vd,t:Wd,b:Xd,fa:Yd,n:Zd,W:$d,L:ae,aa:be,Q:ce,j:de,ua:ee,ea:fe,V:ge,ca:he,da:ie,o:je,i:ke,G:le,K:me,kb:ne,ta:oe,R:pe,mb:qe,ba:re,Z:se,Ua:Ca,ya:function(a,b){try{return ib(y.subarray(a,a+b)),0}catch(c){if("undefined"==
typeof FS||"ErrnoError"!==c.name)throw c;return c.hc}}};function Sd(a,b,c,d,e,f,g){var h=X();try{return I(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}function Md(a,b){var c=X();try{return I(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0)}}function Pd(a,b,c,d){var e=X();try{return I(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function Nd(a,b,c){var d=X();try{return I(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}
function de(a,b,c,d){var e=X();try{I(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function Xd(a,b){var c=X();try{I(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0)}}function Ld(a){var b=X();try{return I(a)()}catch(c){Y(b);if(!(c instanceof v))throw c;Z(1,0)}}function Td(a,b,c,d,e,f,g,h){var l=X();try{return I(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}
function Vd(a,b){var c=X();try{return I(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0);return 0n}}function Ud(a,b,c,d,e,f,g,h,l,k,m,p,t){var r=X();try{return I(a)(b,c,d,e,f,g,h,l,k,m,p,t)}catch(u){Y(r);if(!(u instanceof v))throw u;Z(1,0)}}function se(a,b,c,d,e,f,g,h,l,k,m,p,t,r){var u=X();try{I(a)(b,c,d,e,f,g,h,l,k,m,p,t,r)}catch(w){Y(u);if(!(w instanceof v))throw w;Z(1,0)}}function Zd(a,b,c){var d=X();try{I(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}
function Wd(a){var b=X();try{I(a)()}catch(c){Y(b);if(!(c instanceof v))throw c;Z(1,0)}}function je(a,b,c,d,e){var f=X();try{I(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Rd(a,b,c,d,e,f){var g=X();try{return I(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function Kd(a,b,c,d,e,f){var g=X();try{return I(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function ke(a,b,c,d,e,f){var g=X();try{I(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function Qd(a,b,c,d,e){var f=X();try{return I(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Jd(a,b,c){var d=X();try{return I(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function $d(a,b,c,d){var e=X();try{I(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}
function ae(a,b,c,d,e){var f=X();try{I(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Od(a,b,c,d){var e=X();try{return I(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function pe(a,b,c,d,e,f,g,h,l,k,m){var p=X();try{I(a)(b,c,d,e,f,g,h,l,k,m)}catch(t){Y(p);if(!(t instanceof v))throw t;Z(1,0)}}function le(a,b,c,d,e,f,g){var h=X();try{I(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}
function me(a,b,c,d,e,f,g,h){var l=X();try{I(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}function Yd(a,b,c,d,e){var f=X();try{I(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function ge(a,b,c,d,e,f,g,h){var l=X();try{I(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}function ee(a,b,c,d,e,f,g,h,l,k){var m=X();try{I(a)(b,c,d,e,f,g,h,l,k)}catch(p){Y(m);if(!(p instanceof v))throw p;Z(1,0)}}
function fe(a,b,c,d,e,f,g,h,l){var k=X();try{I(a)(b,c,d,e,f,g,h,l)}catch(m){Y(k);if(!(m instanceof v))throw m;Z(1,0)}}function ie(a,b,c,d,e,f){var g=X();try{I(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function he(a,b,c,d,e,f,g){var h=X();try{I(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}function ce(a,b,c,d,e){var f=X();try{I(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}
function re(a,b,c,d,e,f,g,h,l,k,m,p,t){var r=X();try{I(a)(b,c,d,e,f,g,h,l,k,m,p,t)}catch(u){Y(r);if(!(u instanceof v))throw u;Z(1,0)}}function qe(a,b,c,d,e,f,g,h,l,k,m,p){var t=X();try{I(a)(b,c,d,e,f,g,h,l,k,m,p)}catch(r){Y(t);if(!(r instanceof v))throw r;Z(1,0)}}function oe(a,b,c,d,e,f,g,h,l,k){var m=X();try{I(a)(b,c,d,e,f,g,h,l,k)}catch(p){Y(m);if(!(p instanceof v))throw p;Z(1,0)}}
function ne(a,b,c,d,e,f,g,h,l){var k=X();try{I(a)(b,c,d,e,f,g,h,l)}catch(m){Y(k);if(!(m instanceof v))throw m;Z(1,0)}}function be(a,b,c,d,e,f){var g=X();try{I(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function ue(){function a(){n.calledRun=!0;if(!fa){ra=!0;n.noFSInit||FS.ed||FS.init();ve.qb();Pa(yd);FS.Bd=!1;la?.(n);n.onRuntimeInitialized?.();if(!n.noInitialRun){var b=Gd;try{var c=b(0,0);Ga(c,!0)}catch(d){za(d)}}if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)b=n.postRun.shift(),Qa.push(b);Pa(Qa)}}if(0<Ab)Bb=ue;else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Ra.push(n.preRun.shift());Pa(Ra);0<Ab?Bb=ue:n.setStatus?
(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);a()},1)):a()}}var ve;
ve=await (async function(){function a(c){ve=c.exports;na=ve.pb;ta();Va=ve.ub;c=ve;Kc=c.rb;Fd=c.sb;n._main=Gd=c.tb;V=c.vb;Fa=c.wb;n._calloc=c.xb;Dd=c.yb;Cd=c.zb;n._emscripten_builtin_malloc=c.Ab;Da=c.Bb;n.___libc_calloc=c.Cb;n.___libc_free=c.Db;n.___libc_malloc=c.Eb;n._emscripten_builtin_free=c.Fb;vb=c.Gb;Hd=c.Hb;n._strndup=c.Ib;n.__Znaj=c.Jb;n.__ZnajSt11align_val_t=c.Kb;n.__Znwj=c.Lb;n.__ZnwjSt11align_val_t=c.Mb;n.___libc_realloc=c.Nb;n._emscripten_builtin_calloc=c.Ob;n._emscripten_builtin_realloc=
c.Pb;n._malloc_size=c.Qb;n._malloc_usable_size=c.Rb;n._reallocf=c.Sb;Z=c.Tb;$a=c.Ub;Y=c.Vb;Ad=c.Wb;X=c.Xb;Bd=c.Yb;ab=c.Zb;Id=c._b;return ve}var b={a:te};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=n.locateFile?n.locateFile("vips.wasm",ba):ba+"vips.wasm";return a((await xa(b)).instance)}());ue();ra?moduleRtn=n:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);
