var Vips=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var n=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope;n.workaroundCors&&(n.mainScriptUrlOrBlob=n.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca="./this.program";ba&&(_scriptName=self.location.href);var da="",ea,fa;
if(aa||ba){try{da=(new URL(".",_scriptName)).href}catch{}ba&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ha=console.log.bind(console),t=console.error.bind(console),ia,ja=!1,ka;class v extends Error{}class la extends v{}
class ma extends v{constructor(a){super(a);this.qd=a;a=na(a);this.name=a[0];this.message=a[1]}}var oa,pa,qa,w,x,y,z,B,C,ra,sa,D,ta,ua=!1,va=!1;function wa(){var a=qa.buffer;w=new Int8Array(a);y=new Int16Array(a);x=new Uint8Array(a);z=new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);ra=new Float32Array(a);sa=new Float64Array(a);D=new BigInt64Array(a);ta=new BigUint64Array(a)}
function F(a){n.onAbort?.(a);a="Aborted("+a+")";t(a);ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");pa?.(a);throw a;}var xa;async function ya(a){if(!ia)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==xa&&ia)a=new Uint8Array(ia);else if(fa)a=fa(a);else throw"both async and sync fetching of the wasm failed";return a}
async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),F(d)}}async function Aa(a){var b=xa;if(!ia)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return za(b,a)}var Ca=a=>{if(!(a instanceof Ba||"unwind"==a))throw a;};
class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Da=0,Ga=a=>{ka=a;Fa||0<Da||(n.onExit?.(a),ja=!0);throw new Ba(a);},Ja=a=>{ka=a;if(!(Fa||0<Da)){Ha();FS.yd=!1;Ia(0);for(var b of FS.streams)b&&FS.close(b);va=!0}Ga(a)},Ka=a=>{Da+=1;setTimeout(()=>{--Da;if(!va&&!ja)try{if(a(),!(va||Fa||0<Da))try{Ja(ka)}catch(b){Ca(b)}}catch(b){Ca(b)}},1E4)},La=[],Ma=!1;
function Na(){function a(){Ma=document.pointerLockElement===n.canvas}if(!Oa){Oa=!0;La.push({canHandle:function(c){return!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Pa(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Pa(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var l=new Image;l.onload=()=>{var k=document.createElement("canvas");k.width=l.width;k.height=l.height;k.getContext("2d").drawImage(l,
0,0);URL.revokeObjectURL(f);g(c)};l.onerror=()=>{t(`Image ${f} could not be decoded`);h()};l.src=f})}});La.push({canHandle:function(c){return!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Pa(d)})),l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=function(){if(!g){t(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var k="",m=0,p=0,q=0;q<c.length;q++)for(m=m<<8|c[q],p+=8;6<=p;){var r=m>>p-6&63;p-=6;k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==p?(k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],k+="=="):4==p&&(k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],k+="=");l.src="data:audio/x-"+d.slice(-3)+";base64,"+k;f(l)}};l.src=h;Ka(()=>{f(l)})})}});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),n.elementPointerLock&&b.addEventListener("click",c=>{!Ma&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Pa(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Qa={},Oa,Ra=a=>{for(;0<a.length;)a.shift()(n)},Sa=[],Ta=[],Fa=!1,Ua=new TextDecoder,Va=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},G=(a,b,c)=>a?Ua.decode(x.subarray(a,Va(x,a,b,c))):"",Wa=[],Xa,J=a=>{var b=Wa[a];b||(Wa[a]=b=Xa.get(a));return b},Ya=[],Za=0,$a=0;class ab{constructor(a){this.qd=a;this.yc=a-24}init(a,b){C[this.yc+16>>2]=0;C[this.yc+4>>2]=a;C[this.yc+8>>2]=b}}
var db=a=>{var b=$a?.qd;if(!b)return bb(0),0;var c=new ab(b);C[c.yc+16>>2]=b;var d=C[c.yc+4>>2];if(!d)return bb(0),b;for(var e of a){if(0===e||e===d)break;if(cb(e,d,c.yc+16))return bb(e),b}bb(d);return b},eb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},fb=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=eb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");
return(b?"/":"")+a},gb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},hb=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],ib=(a,b)=>fb(a+"/"+b),jb=()=>a=>crypto.getRandomValues(a),kb=a=>{(kb=jb())(a)},lb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
eb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},mb=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var l=g.length-1;0<=l&&""===g[l];l--);return h>l?[]:g.slice(h,l-h+1)}a=lb(a).slice(1);b=lb(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},nb=a=>{var b=Va(a,0);return Ua.decode(a.buffer?a.subarray(0,
b):new Uint8Array(a.slice(0,b)))},ob=[],pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},qb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=
128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},rb=a=>{var b=Array(pb(a)+1);a=qb(a,b,0,b.length);b.length=a;return b},sb=[];function tb(a,b){sb[a]={input:[],output:[],Yc:b};FS.registerDevice(a,ub)}
var ub={open(a){var b=sb[a.node.md];if(!b)throw new FS.uc(43);a.Dc=b;a.seekable=!1},close(a){a.Dc.Yc.sd(a.Dc)},sd(a){a.Dc.Yc.sd(a.Dc)},read(a,b,c,d){if(!a.Dc||!a.Dc.Yc.Pd)throw new FS.uc(60);for(var e=0,f=0;f<d;f++){try{var g=a.Dc.Yc.Pd(a.Dc)}catch(h){throw new FS.uc(29);}if(void 0===g&&0===e)throw new FS.uc(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Vc=Date.now());return e},write(a,b,c,d){if(!a.Dc||!a.Dc.Yc.Dd)throw new FS.uc(60);try{for(var e=0;e<d;e++)a.Dc.Yc.Dd(a.Dc,b[c+e])}catch(f){throw new FS.uc(29);
}d&&(a.node.Mc=a.node.Lc=Date.now());return e}},vb={Pd(){a:{if(!ob.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ob=rb(a)}a=ob.shift()}return a},Dd(a,b){null===b||10===b?(ha(nb(a.output)),a.output=[]):0!=b&&a.output.push(b)},sd(a){0<a.output?.length&&(ha(nb(a.output)),a.output=[])},ue(){return{Se:25856,Ue:5,Re:191,Te:35387,Qe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0]}},ve(){return 0},we(){return[24,80]}},wb={Dd(a,b){null===b||10===b?(t(nb(a.output)),a.output=[]):0!=b&&a.output.push(b)},sd(a){0<a.output?.length&&(t(nb(a.output)),a.output=[])}},yb=a=>{a=65536*Math.ceil(a/65536);var b=xb(65536,a);b&&x.fill(0,b,b+a);return b},K={Tc:null,mount(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.uc(63);K.Tc||(K.Tc={dir:{node:{Pc:K.wc.Pc,Rc:K.wc.Rc,dd:K.wc.dd,Xc:K.wc.Xc,rename:K.wc.rename,
unlink:K.wc.unlink,rmdir:K.wc.rmdir,nd:K.wc.nd,symlink:K.wc.symlink},stream:{llseek:K.xc.llseek}},file:{node:{Pc:K.wc.Pc,Rc:K.wc.Rc},stream:{llseek:K.xc.llseek,read:K.xc.read,write:K.xc.write,ed:K.xc.ed,gd:K.xc.gd}},link:{node:{Pc:K.wc.Pc,Rc:K.wc.Rc,readlink:K.wc.readlink},stream:{}},Id:{node:{Pc:K.wc.Pc,Rc:K.wc.Rc},stream:FS.ee}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.wc=K.Tc.dir.node,c.xc=K.Tc.dir.stream,c.zc={}):FS.isFile(c.mode)?(c.wc=K.Tc.file.node,c.xc=K.Tc.file.stream,c.Gc=0,c.zc=null):
FS.isLink(c.mode)?(c.wc=K.Tc.link.node,c.xc=K.Tc.link.stream):FS.isChrdev(c.mode)&&(c.wc=K.Tc.Id.node,c.xc=K.Tc.Id.stream);c.Vc=c.Mc=c.Lc=Date.now();a&&(a.zc[b]=c,a.Vc=a.Mc=a.Lc=c.Vc);return c},af(a){return a.zc?a.zc.subarray?a.zc.subarray(0,a.Gc):new Uint8Array(a.zc):new Uint8Array(0)},wc:{Pc(a){var b={};b.ge=FS.isChrdev(a.mode)?a.id:1;b.te=a.id;b.mode=a.mode;b.ze=1;b.uid=0;b.re=0;b.md=a.md;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.Gc:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;
b.Vc=new Date(a.Vc);b.Mc=new Date(a.Mc);b.Lc=new Date(a.Lc);b.de=4096;b.Hd=Math.ceil(b.size/b.de);return b},Rc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Gc!=b&&(0==b?(a.zc=null,a.Gc=0):(c=a.zc,a.zc=new Uint8Array(b),c&&a.zc.set(c.subarray(0,Math.min(b,a.Gc))),a.Gc=b)))},dd(){K.wd||(K.wd=new FS.uc(44),K.wd.stack="<generic error, no stack>");throw K.wd;},Xc(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){try{var d=N(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.zc)throw new FS.uc(55);
zb(d)}delete a.parent.zc[a.name];b.zc[c]=a;a.name=c;b.Lc=b.Mc=a.parent.Lc=a.parent.Mc=Date.now()},unlink(a,b){delete a.zc[b];a.Lc=a.Mc=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.zc)throw new FS.uc(55);delete a.zc[b];a.Lc=a.Mc=Date.now()},nd(a){return[".","..",...Object.keys(a.zc)]},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.uc(28);return a.link}},xc:{read(a,b,c,d,e){var f=a.node.zc;if(e>=a.node.Gc)return 0;a=Math.min(a.node.Gc-
e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.Mc=a.Lc=Date.now();if(b.subarray&&(!a.zc||a.zc.subarray)){if(f)return a.zc=b.subarray(c,c+d),a.Gc=d;if(0===a.Gc&&0===e)return a.zc=b.slice(c,c+d),a.Gc=d;if(e+d<=a.Gc)return a.zc.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.zc?a.zc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.zc,a.zc=new Uint8Array(f),
0<a.Gc&&a.zc.set(g.subarray(0,a.Gc),0));if(a.zc.subarray&&b.subarray)a.zc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.zc[e+f]=b[c+f];a.Gc=Math.max(a.Gc,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.Gc);if(0>b)throw new FS.uc(28);return b},ed(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.uc(43);a=a.node.zc;if(e&2||!a||a.buffer!==w.buffer){d=!0;e=yb(b);if(!e)throw new FS.uc(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);w.set(a,e)}}else d=!1,e=a.byteOffset;return{yc:e,Gd:d}},gd(a,b,c,d){K.xc.write(a,b,0,d,c,!1);return 0}}},Ab=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Bb=async a=>{a=await ea(a);return new Uint8Array(a)},Cb=0,Db=null,Eb=()=>{Cb--;n.monitorRunDependencies?.(Cb);if(0==Cb&&Db){var a=Db;Db=null;a()}},Fb=()=>{Cb++;n.monitorRunDependencies?.(Cb)},Gb=async(a,b)=>{"undefined"!=typeof Qa&&Na();for(var c of La)if(c.canHandle(b))return c.handle(a,b);return a},Hb=async(a,b,c,d,e,f,g,h)=>{var l=
b?lb(fb(a+"/"+b)):a,k=`cp ${l}`;Fb(k);try{var m=c;"string"==typeof c&&(m=await Bb(c));m=await Gb(m,l);h?.();f||FS.createDataFile(a,b,m,d,e,g)}finally{Eb(k)}};function N(a,b){var c=FS.isDir(a.mode)?(c=Ib(a,"x"))?c:a.wc.dd?0:2:54;if(c)throw new FS.uc(c);for(c=FS.Sc[Jb(a.id,b)];c;c=c.fd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.dd(a,b)}function zb(a){var b=Jb(a.parent.id,a.name);if(FS.Sc[b]===a)FS.Sc[b]=a.fd;else for(b=FS.Sc[b];b;){if(b.fd===a){b.fd=a.fd;break}b=b.fd}}
function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.Sc.length}function Kb(a){var b=Jb(a.parent.id,a.name);a.fd=FS.Sc[b];FS.Sc[b]=a}function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(FS.Qd)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Mb(a,b){if(!FS.isDir(a.mode))return 54;try{return N(a,b),20}catch(c){}return Ib(a,"wx")}function Nb(a,b,c){try{var d=N(a,b)}catch(e){return e.Bc}if(a=Ib(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.jd(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Ob(a,b){if(!a)throw new FS.uc(b);return a}function O(a){a=FS.oe(a);if(!a)throw new FS.uc(8);return a}
function Pb(a,b=-1){a=Object.assign(new FS.be,a);if(-1==b)a:{for(b=0;b<=FS.ce;b++)if(!FS.streams[b])break a;throw new FS.uc(33);}a.Wc=b;return FS.streams[b]=a}function Qb(a,b=-1){a=Pb(a,b);a.xc?.We?.(a);return a}function Rb(a,b,c){var d=a?.xc.Rc;a=d?a:b;d??=b.wc.Rc;Ob(d,63);d(a,c)}function Sb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.kd)}return b}
function Tb(a){var b={Pe:4096,Ze:4096,Hd:1E6,Oe:5E5,Ne:5E5,files:FS.Cd,Xe:FS.Cd-1,$e:42,flags:2,df:255};a.wc.Vd&&Object.assign(b,a.wc.Vd(a.mount.Be.root));return b}function Ub(a,b,c,d){Rb(a,b,{mode:c&4095|b.mode&-4096,Lc:Date.now(),Md:d})}function Vb(a,b,c){if(FS.isDir(b.mode))throw new FS.uc(31);if(!FS.isFile(b.mode))throw new FS.uc(28);var d=Ib(b,"w");if(d)throw new FS.uc(d);Rb(a,b,{size:c,timestamp:Date.now()})}
function Wb(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=fb(a+"/"+b);return FS.create(b,Ab(c,d))}function Xb(a){if(!(a.xe||a.ye||a.link||a.zc))if("undefined"!=typeof XMLHttpRequest)F("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.zc=fa(a.url)}catch(b){throw new FS.uc(29);}}
var FS={root:null,kd:[],Ld:{},streams:[],Cd:1,Sc:null,Jd:"/",yd:!1,Qd:!0,ke:null,vd:0,Ud:{},uc:class{name="ErrnoError";constructor(a){this.Bc=a}},be:class{Zc={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Zc.flags}set flags(a){this.Zc.flags=a}get position(){return this.Zc.position}set position(a){this.Zc.position=a}},ae:class{wc={};xc={};Qc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Cd++;this.name=b;this.mode=c;this.md=
d;this.Vc=this.Mc=this.Lc=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ye(){return FS.isDir(this.mode)}get xe(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.uc(44);b.rd??(b.rd=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-
1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=gb(e),FS.jd(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=fb(e+"/"+a[f]);try{d=N(d,a[f])}catch(h){if(44===h?.Bc&&g&&b.Ae)return{path:e};throw h;}!d.Qc||g&&!b.rd||(d=d.Qc.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.wc.readlink)throw new FS.uc(52);d=d.wc.readlink(d);"/"===d.charAt(0)||(d=gb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.uc(32);},getPath(a){for(var b;;){if(FS.jd(a))return a=
a.mount.Sd,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.ae(a,b,c,d);Kb(a);return a},jd(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},ce:4096,oe:a=>FS.streams[a],ee:{open(a){a.xc=FS.me(a.node.md).xc;a.xc.open?.(a)},llseek(){throw new FS.uc(70);
}},Bd:a=>a>>8,bf:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Ld[a]={xc:b}},me:a=>FS.Ld[a],syncfs(a,b){function c(g){FS.vd--;return b(g)}function d(g){if(g){if(!d.ie)return d.ie=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.vd++;1<FS.vd&&t(`warning: ${FS.vd} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Sb(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.uc(10);
if(!d&&c){var e=FS.lookupPath(c,{rd:!1});c=e.path;e=e.node;if(e.Qc)throw new FS.uc(10);if(!FS.isDir(e.mode))throw new FS.uc(54);}b={type:a,Be:b,Sd:c,kd:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.Qc=b,e.mount&&e.mount.kd.push(b));return a},unmount(a){a=FS.lookupPath(a,{rd:!1});if(!a.node.Qc)throw new FS.uc(28);a=a.node;var b=a.Qc,c=Sb(b);Object.keys(FS.Sc).forEach(d=>{for(d=FS.Sc[d];d;){var e=d.fd;c.includes(d.mount)&&zb(d);d=e}});a.Qc=null;a.mount.kd.splice(a.mount.kd.indexOf(b),1)},dd(a,
b){return a.wc.dd(a,b)},Xc(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=hb(a);if(!a)throw new FS.uc(28);if("."===a||".."===a)throw new FS.uc(20);var e=Mb(d,a);if(e)throw new FS.uc(e);if(!d.wc.Xc)throw new FS.uc(63);return d.wc.Xc(d,a,b,c)},Vd(a){return Tb(FS.lookupPath(a,{follow:!0}).node)},ff(a){return Tb(a.node)},create(a,b=438){return FS.Xc(a,b&4095|32768,0)},mkdir(a,b=511){return FS.Xc(a,b&1023|16384,0)},cf(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=
e;try{FS.mkdir(d,b)}catch(f){if(20!=f.Bc)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.Xc(a,b|8192,c)},symlink(a,b){if(!lb(a))throw new FS.uc(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.uc(44);b=hb(b);var d=Mb(c,b);if(d)throw new FS.uc(d);if(!c.wc.symlink)throw new FS.uc(63);return c.wc.symlink(c,b,a)},rename(a,b){var c=gb(a),d=gb(b),e=hb(a),f=hb(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.uc(44);
if(h.mount!==g.mount)throw new FS.uc(75);var l=N(h,e);a=mb(a,d);if("."!==a.charAt(0))throw new FS.uc(28);a=mb(b,c);if("."!==a.charAt(0))throw new FS.uc(55);try{var k=N(g,f)}catch(m){}if(l!==k){b=FS.isDir(l.mode);if(e=Nb(h,e,b))throw new FS.uc(e);if(e=k?Nb(g,f,b):Mb(g,f))throw new FS.uc(e);if(!h.wc.rename)throw new FS.uc(63);if(l.Qc||k&&k.Qc)throw new FS.uc(10);if(g!==h&&(e=Ib(h,"w")))throw new FS.uc(e);zb(l);try{h.wc.rename(l,g,f),l.parent=g}catch(m){throw m;}finally{Kb(l)}}},rmdir(a){var b=FS.lookupPath(a,
{parent:!0}).node;a=hb(a);var c=N(b,a),d=Nb(b,a,!0);if(d)throw new FS.uc(d);if(!b.wc.rmdir)throw new FS.uc(63);if(c.Qc)throw new FS.uc(10);b.wc.rmdir(b,a);zb(c)},nd(a){a=FS.lookupPath(a,{follow:!0}).node;return Ob(a.wc.nd,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.uc(44);a=hb(a);var c=N(b,a),d=Nb(b,a,!1);if(d)throw new FS.uc(d);if(!b.wc.unlink)throw new FS.uc(63);if(c.Qc)throw new FS.uc(10);b.wc.unlink(b,a);zb(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.uc(44);
if(!a.wc.readlink)throw new FS.uc(28);return a.wc.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Ob(a.wc.Pc,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Ub(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=O(a);Ub(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Rb(null,a,{timestamp:Date.now(),Md:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=O(a);Rb(a,a.node,{timestamp:Date.now(),
Md:!1})},truncate(a,b){if(0>b)throw new FS.uc(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Vb(null,a,b)},ftruncate(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new FS.uc(28);Vb(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Ob(a.wc.Rc,63)(a,{Vc:b,Mc:c})},open(a,b,c=438){if(""===a)throw new FS.uc(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:
0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=FS.lookupPath(a,{follow:!(b&131072),Ae:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.uc(20);}else{if(e)throw new FS.uc(31);d=FS.Xc(a,c|511,0);f=!0}if(!d)throw new FS.uc(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.uc(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==Lb(g)||g&576)?31:Ib(e,Lb(g)):44)throw new FS.uc(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=Pb({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,xc:d.xc,Me:[],error:!1});e.xc.open&&e.xc.open(e);f&&FS.chmod(d,c&511);!n.logReadFiles||b&1||a in FS.Ud||(FS.Ud[a]=1);return e},close(a){if(null===a.Wc)throw new FS.uc(8);a.xd&&(a.xd=null);try{a.xc.close&&a.xc.close(a)}catch(b){throw b;}finally{FS.streams[a.Wc]=null}a.Wc=null},llseek(a,b,c){if(null===a.Wc)throw new FS.uc(8);if(!a.seekable||!a.xc.llseek)throw new FS.uc(70);if(0!=c&&1!=c&&2!=c)throw new FS.uc(28);a.position=a.xc.llseek(a,b,c);a.Me=[];
return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.uc(28);if(null===a.Wc)throw new FS.uc(8);if(1===(a.flags&2097155))throw new FS.uc(8);if(FS.isDir(a.node.mode))throw new FS.uc(31);if(!a.xc.read)throw new FS.uc(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.uc(70);b=a.xc.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.uc(28);if(null===a.Wc)throw new FS.uc(8);if(0===(a.flags&2097155))throw new FS.uc(8);if(FS.isDir(a.node.mode))throw new FS.uc(31);
if(!a.xc.write)throw new FS.uc(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.uc(70);b=a.xc.write(a,b,c,d,e,f);g||(a.position+=b);return b},ed(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.uc(2);if(1===(a.flags&2097155))throw new FS.uc(2);if(!a.xc.ed)throw new FS.uc(43);if(!b)throw new FS.uc(28);return a.xc.ed(a,b,c,d,e)},gd(a,b,c,d,e){return a.xc.gd?a.xc.gd(a,b,c,d,e):0},zd(a,b,c){if(!a.xc.zd)throw new FS.uc(59);
return a.xc.zd(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&F(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=nb(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(rb(b)));ArrayBuffer.isView(b)?FS.write(a,b,0,b.byteLength,void 0,c.Ve):F("Unsupported data type");
FS.close(a)},cwd:()=>FS.Jd,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.uc(44);if(!FS.isDir(a.node.mode))throw new FS.uc(54);var b=Ib(a.node,"x");if(b)throw new FS.uc(b);FS.Jd=a.path},init(a,b,c){FS.yd=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",
0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ye(a,b){a=FS.analyzePath(a,b);return a.Nd?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={jd:!1,Nd:!1,error:0,name:null,path:null,object:null,Ce:!1,Ee:null,De:null};try{c=FS.lookupPath(a,{parent:!0}),d.Ce=!0,d.Ee=c.path,d.De=c.node,d.name=hb(a),c=FS.lookupPath(a,{follow:!b}),d.Nd=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.jd="/"===c.path}catch(e){d.error=e.Bc}return d},createPath(a,b){a=
"string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fb(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.Bc)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?fb(a+"/"+b):a);a=Ab(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,
b,c,d){a=ib("string"==typeof a?a:FS.getPath(a),b);b=Ab(!!c,!!d);var e;(e=FS.createDevice).Bd??(e.Bd=64);e=FS.makedev(FS.createDevice.Bd++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,l){for(var k=0,m=0;m<l;m++){try{var p=c()}catch(q){throw new FS.uc(29);}if(void 0===p&&0===k)throw new FS.uc(6);if(null===p||void 0===p)break;k++;g[h+m]=p}k&&(f.node.Vc=Date.now());return k},write(f,g,h,l){for(var k=0;k<l;k++)try{d(g[h+k])}catch(m){throw new FS.uc(29);}l&&
(f.node.Mc=f.node.Lc=Date.now());return k}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(p,q,r,u,A){p=p.node.zc;if(A>=p.length)return 0;u=Math.min(p.length-A,u);if(p.slice)for(var E=0;E<u;E++)q[r+E]=p[A+E];else for(E=0;E<u;E++)q[r+E]=p.get(A+E);return u}class g{Fd=!1;Zc=[];hd=void 0;Xd=0;Wd=0;get(p){if(!(p>this.length-1||0>p)){var q=p%this.Zd;return this.hd(p/this.Zd|0)[q]}}$d(p){this.hd=p}Yd(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);200<=p.status&&300>p.status||
304===p.status||F("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),r,u=(r=p.getResponseHeader("Accept-Ranges"))&&"bytes"===r;p=(r=p.getResponseHeader("Content-Encoding"))&&"gzip"===r;var A=1048576;u||(A=q);var E=this;E.$d(I=>{var H=I*A,M=(I+1)*A-1;M=Math.min(M,q-1);if("undefined"==typeof E.Zc[I]){var Ea=E.Zc;H>M&&F("invalid range ("+H+", "+M+") or no bytes requested!");M>q-1&&F("only "+q+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",
c,!1);q!==A&&L.setRequestHeader("Range","bytes="+H+"-"+M);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);200<=L.status&&300>L.status||304===L.status||F("Couldn't load "+c+". Status: "+L.status);H=void 0!==L.response?new Uint8Array(L.response||[]):rb(L.responseText||"");Ea[I]=H}"undefined"==typeof E.Zc[I]&&F("doXHR failed!");return E.Zc[I]});if(p||!q)A=q=1,A=q=this.hd(0).length,ha("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Xd=q;this.Wd=A;this.Fd=!0}get length(){this.Fd||this.Yd();return this.Xd}get Zd(){this.Fd||this.Yd();return this.Wd}}if("undefined"!=typeof XMLHttpRequest){ba||F("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var l=void 0}else l=c,h=void 0;var k=Wb(a,b,d,e);h?k.zc=h:l&&(k.zc=null,k.url=l);Object.defineProperties(k,{Gc:{get:function(){return this.zc.length}}});var m={};Object.keys(k.xc).forEach(p=>{var q=k.xc[p];
m[p]=(...r)=>{Xb(k);return q(...r)}});m.read=(p,q,r,u,A)=>{Xb(k);return f(p,q,r,u,A)};m.ed=(p,q,r)=>{Xb(k);var u=yb(q);if(!u)throw new FS.uc(48);f(p,w,u,q,r);return{yc:u,Gd:!0}};k.xc=m;return k}};function Yb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():O(a).path;if(0==b.length){if(!c)throw new FS.uc(44);return a}return a+"/"+b}
function Zb(a,b){C[a>>2]=b.ge;C[a+4>>2]=b.mode;C[a+8>>2]=b.ze;C[a+12>>2]=b.uid;C[a+16>>2]=b.re;C[a+20>>2]=b.md;D[a+24>>3]=BigInt(b.size);B[a+32>>2]=4096;B[a+36>>2]=b.Hd;var c=b.Vc.getTime(),d=b.Mc.getTime(),e=b.Lc.getTime();D[a+40>>3]=BigInt(Math.floor(c/1E3));C[a+48>>2]=c%1E3*1E6;D[a+56>>3]=BigInt(Math.floor(d/1E3));C[a+64>>2]=d%1E3*1E6;D[a+72>>3]=BigInt(Math.floor(e/1E3));C[a+80>>2]=e%1E3*1E6;D[a+88>>3]=BigInt(b.te);return 0}
var $b=void 0,ac=()=>{var a=B[+$b>>2];$b+=4;return a},bc={},cc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function dc(a){return this.Cc(C[a>>2])}
var ec={},fc={},gc={},hc=class extends Error{constructor(a){super(a);this.name="InternalError"}},Q=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new hc("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],h[l])}a.forEach(h=>gc[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{fc.hasOwnProperty(h)?e[l]=fc[h]:(f.push(h),ec.hasOwnProperty(h)||(ec[h]=[]),ec[h].push(()=>{e[l]=fc[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},R=a=>{for(var b="";;){var c=x[a++];if(!c)return b;
b+=String.fromCharCode(c)}},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},ic=a=>{throw new S(a);};function jc(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(fc.hasOwnProperty(a)){if(c.se)return;throw new S(`Cannot register type '${d}' twice`);}fc[a]=b;delete gc[a];ec.hasOwnProperty(a)&&(b=ec[a],delete ec[a],b.forEach(e=>e()))}function P(a,b,c={}){return jc(a,b,c)}
var kc=(a,b,c)=>{switch(b){case 1:return c?d=>w[d]:d=>x[d];case 2:return c?d=>y[d>>1]:d=>z[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];case 8:return c?d=>D[d>>3]:d=>ta[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},lc=a=>{throw new S(a.vc.Ec.Ac.name+" instance already deleted");},mc=!1,nc=!1,oc=()=>{},pc=a=>{if(mc)return pc=b=>b.deleteLater(),pc(a);if("undefined"===typeof FinalizationRegistry)return pc=b=>b,a;nc=new FinalizationRegistry(b=>{b=b.vc;--b.count.value;0===b.count.value&&
(b.Ic?b.Oc.Uc(b.Ic):b.Ec.Ac.Uc(b.yc))});pc=b=>{var c=b.vc;c.Ic&&nc.register(b,{vc:c},b);return b};oc=b=>{nc.unregister(b)};return pc(a)},qc=[],rc=()=>{for(;qc.length;){var a=qc.pop();a.vc.cd=!1;a["delete"]()}},sc;function tc(){}
var uc=(a,b)=>Object.defineProperty(b,"name",{value:a}),vc={},wc=(a,b,c)=>{if(void 0===a[b].Fc){var d=a[b];a[b]=function(...e){if(!a[b].Fc.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Fc})!`);return a[b].Fc[e.length].apply(this,e)};a[b].Fc=[];a[b].Fc[d.ad]=d}},xc=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].Fc&&void 0!==n[a].Fc[c])throw new S(`Cannot register public name '${a}' twice`);wc(n,
a,a);if(n[a].Fc.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].Fc[c]=b}else n[a]=b,n[a].ad=c},yc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function zc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.$c=c;this.Uc=d;this.Kc=e;this.le=f;this.od=g;this.he=h;this.Ge=[]}
var Ac=(a,b,c)=>{for(;b!==c;){if(!b.od)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.od(a);b=b.Kc}return a},Bc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Cc(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.vc)throw new S(`Cannot pass "${Bc(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ac(b.vc.yc,b.vc.Ec.Ac,this.Ac)}
function Dc(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);if(this.ud){var c=this.Ed();null!==a&&a.push(this.Uc,c);return c}return 0}if(!b||!b.vc)throw new S(`Cannot pass "${Bc(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.td&&b.vc.Ec.td)throw new S(`Cannot convert argument of type ${b.vc.Oc?b.vc.Oc.name:b.vc.Ec.name} to parameter type ${this.name}`);c=Ac(b.vc.yc,b.vc.Ec.Ac,this.Ac);if(this.ud){if(void 0===
b.vc.Ic)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Le){case 0:if(b.vc.Oc===this)c=b.vc.Ic;else throw new S(`Cannot convert argument of type ${b.vc.Oc?b.vc.Oc.name:b.vc.Ec.name} to parameter type ${this.name}`);break;case 1:c=b.vc.Ic;break;case 2:if(b.vc.Oc===this)c=b.vc.Ic;else{var d=b.clone();c=this.He(c,T(()=>d["delete"]()));null!==a&&a.push(this.Uc,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Ec(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.vc)throw new S(`Cannot pass "${Bc(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.vc.Ec.td)throw new S(`Cannot convert argument of type ${b.vc.Ec.name} to parameter type ${this.name}`);return Ac(b.vc.yc,b.vc.Ec.Ac,this.Ac)}
var Fc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Kc)return null;a=Fc(a,b,c.Kc);return null===a?null:c.he(a)},Gc={},Hc=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.Kc;)b=a.od(b),a=a.Kc;return Gc[b]},Ic=(a,b)=>{if(!b.Ec||!b.yc)throw new hc("makeClassHandle requires ptr and ptrType");if(!!b.Oc!==!!b.Ic)throw new hc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return pc(Object.create(a,{vc:{value:b,writable:!0}}))};
function Jc(a,b,c,d,e,f,g,h,l,k,m){this.name=a;this.Ac=b;this.Ad=c;this.td=d;this.ud=e;this.Fe=f;this.Le=g;this.Td=h;this.Ed=l;this.He=k;this.Uc=m;e||void 0!==b.Kc?this.Hc=Dc:(this.Hc=d?Cc:Ec,this.Jc=null)}var Kc=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new hc("Replacing nonexistent public symbol");void 0!==n[a].Fc&&void 0!==c?n[a].Fc[c]=b:(n[a]=b,n[a].ad=c)},U=(a,b)=>{a=R(a);var c=J(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};
class Lc extends Error{}var Nc=a=>{a=Mc(a);var b=R(a);V(a);return b},Oc=(a,b)=>{function c(f){e[f]||fc[f]||(gc[f]?gc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Lc(`${a}: `+d.map(Nc).join([", "]));};function Pc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Jc)return!0;return!1}
function Qc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=Pc(b);c=!b[0].Rd;var k=b[0],m=b[1];d=[a,ic,d,e,cc,k.Cc.bind(k),m?.Hc.bind(m)];for(e=2;e<g;++e)k=b[e],d.push(k.Hc.bind(k));if(!l)for(e=h?1:2;e<b.length;++e)null!==b[e].Jc&&d.push(b[e].Jc);l=Pc(b);e=b.length-2;m=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),k.push(`arg${g}Wired`);m=m.join(",");k=k.join(",");
m=`return function (${m}) {\n`;l&&(m+="var destructors = [];\n");var p=l?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${p}, this);\n`);for(g=0;g<e;++g){var r=`toArg${g}Wire`;m+=`var arg${g}Wired = ${r}(${p}, arg${g});\n`;q.push(r)}m+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].Jc&&(m+=`${f}_dtor(${f});\n`,q.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(q,m+"}\n"))(...d);return uc(a,b)}
var Rc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},Sc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Tc=(a,b,c)=>{if(!(a instanceof Object))throw new S(`${c} with invalid "this": ${a}`);if(!(a instanceof b.Ac.constructor))throw new S(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.vc.yc)throw new S(`cannot call emscripten binding method ${c} on deleted object`);return Ac(a.vc.yc,a.vc.Ec.Ac,b.Ac)},Uc=[],Vc=[0,1,,1,null,1,!0,1,!1,1],Wc=a=>
{9<a&&0===--Vc[a+1]&&(Vc[a]=void 0,Uc.push(a))},W=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return Vc[a]},T=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Uc.pop()||Vc.length;Vc[b]=a;Vc[b+1]=1;return b}},Xc={name:"emscripten::val",Cc:a=>{var b=W(a);Wc(a);return b},Hc:(a,b)=>T(b),Nc:dc,Jc:null},Yc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.Cc(w[d])}:function(d){return this.Cc(x[d])};case 2:return c?function(d){return this.Cc(y[d>>
1])}:function(d){return this.Cc(z[d>>1])};case 4:return c?function(d){return this.Cc(B[d>>2])}:function(d){return this.Cc(C[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Zc=(a,b)=>{var c=fc[a];if(void 0===c)throw a=`${b} has unknown type ${Nc(a)}`,new S(a);return c},$c=(a,b)=>{switch(b){case 4:return function(c){return this.Cc(ra[c>>2])};case 8:return function(c){return this.Cc(sa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ad=new TextDecoder("utf-16le"),
bd=(a,b,c)=>{a>>=1;return ad.decode(z.subarray(a,Va(z,a,b/2,c)))},cd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},dd=a=>2*a.length,ed=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=C[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},fd=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;B[b>>2]=f;b+=4;if(b+
4>c)break}B[b>>2]=0;return b-d},gd=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},hd=[],jd=a=>{var b=hd.length;hd.push(a);return b},kd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Zc(C[b+4*d>>2],`parameter ${d}`);return c},ld=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(C[b>>2]=T(d));return a},md={},nd=a=>{var b=md[a];return void 0===b?R(a):b},od=globalThis,pd=[0,31,60,91,121,152,182,213,244,274,305,335],qd=[0,31,59,90,120,151,181,212,243,273,304,334],rd={},td=()=>{if(!sd){var a=
{USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in rd)void 0===rd[b]?delete a[b]:a[b]=rd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);sd=c}return sd},sd,ud=[],vd=a=>{const b=a.length;return[b%128|128,b>>7,...a]},wd={i:127,p:127,j:126,f:125,d:124,e:111},xd=a=>vd(Array.from(a,b=>wd[b])),yd=[],zd,na=a=>{var b=X(),c=Ad(4),d=Ad(4);Bd(a,c,d);a=C[c>>2];d=C[d>>2];
c=G(a);V(a);if(d){var e=G(d);V(d)}Y(b);return[c,e]};FS.createPreloadedFile=(a,b,c,d,e,f,g,h,l,k)=>{Hb(a,b,c,d,e,h,l,k).then(f).catch(g)};FS.ef=Hb;FS.Sc=Array(4096);FS.mount(K,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));tb(FS.makedev(5,0),vb);tb(FS.makedev(6,0),wb);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(kb(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.xc={llseek:K.xc.llseek};b.wc={dd(c,d){c=+d;var e=O(c);c={parent:null,mount:{Sd:"fake"},wc:{readlink:()=>e.path},id:c+1};return c.parent=c},nd(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.ke={MEMFS:K};
(()=>{let a=tc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof tc&&c instanceof tc))return!1;var d=this.vc.Ec.Ac,e=this.vc.yc;c.vc=c.vc;var f=c.vc.Ec.Ac;for(c=c.vc.yc;d.Kc;)e=d.od(e),d=d.Kc;for(;f.Kc;)c=f.od(c),f=f.Kc;return d===f&&e===c},clone:function(){this.vc.yc||lc(this);if(this.vc.ld)return this.vc.count.value+=1,this;var c=pc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.vc;c=c(e.call(d,f,{vc:{value:{count:g.count,cd:g.cd,ld:g.ld,yc:g.yc,Ec:g.Ec,Ic:g.Ic,Oc:g.Oc}}}));
c.vc.count.value+=1;c.vc.cd=!1;return c},["delete"](){this.vc.yc||lc(this);if(this.vc.cd&&!this.vc.ld)throw new S("Object already scheduled for deletion");oc(this);var c=this.vc;--c.count.value;0===c.count.value&&(c.Ic?c.Oc.Uc(c.Ic):c.Ec.Ac.Uc(c.yc));this.vc.ld||(this.vc.Ic=void 0,this.vc.yc=void 0)},isDeleted:function(){return!this.vc.yc},deleteLater:function(){this.vc.yc||lc(this);if(this.vc.cd&&!this.vc.ld)throw new S("Object already scheduled for deletion");qc.push(this);1===qc.length&&sc&&sc(rc);
this.vc.cd=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Jc.prototype,{ne(a){this.Td&&(a=this.Td(a));return a},Kd(a){this.Uc?.(a)},Nc:dc,Cc:function(a){function b(){return this.ud?Ic(this.Ac.$c,{Ec:this.Fe,yc:c,Oc:this,Ic:a}):Ic(this.Ac.$c,{Ec:this,yc:a})}var c=this.ne(a);if(!c)return this.Kd(a),null;var d=Hc(this.Ac,c);if(void 0!==d){if(0===d.vc.count.value)return d.vc.yc=c,d.vc.Ic=a,d.clone();d=d.clone();this.Kd(a);return d}d=this.Ac.le(c);d=vc[d];if(!d)return b.call(this);d=this.td?d.fe:d.pointerType;var e=Fc(c,this.Ac,d.Ac);return null===
e?b.call(this):this.ud?Ic(d.Ac.$c,{Ec:d,yc:e,Oc:this,Ic:a}):Ic(d.Ac.$c,{Ec:d,yc:e})}});Ta.push(()=>{rd.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;rd.VIPS_CONCURRENCY=1});
yd.push(()=>{const a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>T(c(d)))}});const b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(W(d)))}})});Object.assign(tc.prototype,{preventAutoDelete:function(){const a=qc.indexOf(this);-1<a&&qc.splice(a,1);this.vc.cd=!1;return this}});
n.preloadPlugins&&(La=n.preloadPlugins);n.noExitRuntime&&(Fa=n.noExitRuntime);n.print&&(ha=n.print);n.printErr&&(t=n.printErr);n.wasmBinary&&(ia=n.wasmBinary);n.thisProgram&&(ca=n.thisProgram);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();n.ENV=rd;n.addRunDependency=Fb;n.removeRunDependency=Eb;
n.addFunction=(a,b)=>{if(!zd){zd=new WeakMap;var c=Xa.length;if(zd)for(var d=0;d<0+c;d++){var e=J(d);e&&zd.set(e,d)}}if(c=zd.get(a)||0)return c;c=ud.length?ud.pop():Xa.grow(1);try{Xa.set(c,a),Wa[c]=Xa.get(c)}catch(f){if(!(f instanceof TypeError))throw f;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...vd([1,96,...xd(b.slice(1)),...xd("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;Xa.set(c,b);Wa[c]=Xa.get(c)}zd.set(a,
c);return c};n.FS_preloadFile=Hb;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{mc=a};n.deletionQueue=qc;n.setDelayFunction=a=>{sc=a;qc.length&&sc&&sc(rc)};n.incrementExceptionRefcount=a=>Cd(a);n.decrementExceptionRefcount=a=>Dd(a);n.getExceptionMessage=a=>na(a);
function Ed(a){for(var b=z[a+6>>1];13===b&&!(16<C[a>>2]);){var c=C[a+8>>2],d=C[c>>2];if(0===d){b=0;break}else if(0===C[(c>>2)+1])a=d,b=z[d+6>>1];else break}return[a,b]}
var Mc,Fd,Gd,V,Ia,Dd,Cd,Ha,xb,Z,bb,Y,Ad,X,Bd,cb,Hd,Qe={j:(a,b,c,d)=>F(`Assertion failed: ${G(a)}, at: `+[b?G(b):"unknown filename",c,d?G(d):"unknown function"]),qb:(a,b)=>J(a)(b),E:a=>{var b=new ab(a);0==w[b.yc+12]&&(w[b.yc+12]=1,Za--);w[b.yc+13]=0;Ya.push(b);Cd(a);return Hd(a)},I:()=>{Z(0,0);var a=Ya.pop();Dd(a.qd);$a=0},a:()=>db([]),g:a=>db([a]),Xa:()=>{var a=Ya.pop();a||F("no exception to throw");var b=a.qd;0==w[a.yc+13]&&(Ya.push(a),w[a.yc+13]=1,w[a.yc+12]=0,Za++);$a=new ma(b);throw $a;},J:(a,
b,c)=>{(new ab(a)).init(b,c);$a=new ma(a);Za++;throw $a;},ya:()=>Za,e:a=>{$a||=new ma(a);throw $a;},Eb:function(a){try{var b=O(a);return Qb(b).Wc}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}},Gb:function(a,b,c){try{b=G(b);b=Yb(a,b);if(c&-8)return-28;var d=FS.lookupPath(b,{follow:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Ib(d,a)?-2:0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.Bc}},ua:function(a,
b,c){$b=c;try{var d=O(a);switch(b){case 0:var e=ac();if(0>e)break;for(;FS.streams[e];)e++;return Qb(d,e).Wc;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ac(),d.flags|=e,0;case 12:return e=ac(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}},Db:function(a,b){try{var c=O(a),d=c.node,e=c.xc.Pc;a=e?c:d;e??=d.wc.Pc;Ob(e,63);var f=e(a);return Zb(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;
return-g.Bc}},zb:function(a,b){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}},yb:function(a,b){try{if(0===b)return-28;var c=FS.cwd(),d=pb(c)+1;if(b<d)return-68;qb(c,x,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.Bc}},Ra:function(a,b,c){$b=c;try{var d=O(a);switch(b){case 21509:return d.Dc?0:-59;case 21505:if(!d.Dc)return-59;
if(d.Dc.Yc.ue){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=ac();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Dc?0:-59;case 21506:case 21507:case 21508:if(!d.Dc)return-59;if(d.Dc.Yc.ve)for(e=ac(),a=[],f=0;32>f;f++)a.push(w[e+f+17]);return 0;case 21519:if(!d.Dc)return-59;e=ac();return B[e>>2]=0;case 21520:return d.Dc?-28:-59;case 21537:case 21531:return e=ac(),
FS.zd(d,b,e);case 21523:if(!d.Dc)return-59;d.Dc.Yc.we&&(f=[24,80],e=ac(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.Dc?0:-59;case 21515:return d.Dc?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.Bc}},Ab:function(a,b){try{return a=G(a),Zb(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}},Bb:function(a,b,c,d){try{b=G(b);var e=d&256;b=Yb(a,b,d&4096);return Zb(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==
typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}},sa:function(a,b,c,d){$b=d;try{b=G(b);b=Yb(a,b);var e=d?ac():0;return FS.open(b,c,e).Wc}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}},pb:function(a){try{return a=G(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.Bc}},Cb:function(a,b){try{return a=G(a),Zb(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}},Oa:function(a,b,c){try{b=
G(b);b=Yb(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.Bc}},Hb:()=>F(""),ab:a=>{var b=bc[a];delete bc[a];var c=b.Ed,d=b.Uc,e=b.Od,f=e.map(g=>g.qe).concat(e.map(g=>g.Je));Q([a],f,g=>{var h={};e.forEach((l,k)=>{var m=g[k],p=l.hd,q=l.pe,r=g[k+e.length],u=l.Ie,A=l.Ke;h[l.je]={read:E=>m.Cc(p(q,E)),write:(E,I)=>{var H=[];u(A,E,r.Hc(H,I));cc(H)},optional:g[k].optional}});return[{name:b.name,Cc:l=>{var k=
{},m;for(m in h)k[m]=h[m].read(l);d(l);return k},Hc:(l,k)=>{for(var m in h)if(!(m in k||h[m].optional))throw new TypeError(`Missing field: "${m}"`);var p=c();for(m in h)h[m].write(p,k[m]);null!==l&&l.push(d,p);return p},Nc:dc,Jc:d}]})},Ga:(a,b,c,d,e)=>{b=R(b);if(d)a:switch(c){case 4:d=ra;break a;case 8:d=sa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?w:x;break a;case 2:d=e?y:z;break a;case 4:d=e?B:C;break a;case 8:d=e?D:ta;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);
}var f=d,g=Math.log2(c);P(a,{name:b,Cc:h=>{var l=h+Math.max(4,c)>>g;l=Array.from(f.subarray(l,l+C[h>>2]));V(h);return l},Hc:(h,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new S(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var k=l.length,m=Math.max(4,c),p=Fd(m+k*c);m=p+m>>g;C[p>>2]=k;f.set(l,m);null!==h&&h.push(V,p);return p},Nc:dc,Jc(h){V(h)}})},Ba:(a,b,c,d,e)=>{b=R(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}P(a,
{name:b,Cc:f,Hc:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},Nc:kc(b,c,!d),Jc:null})},_a:(a,b,c,d)=>{b=R(b);P(a,{name:b,Cc:function(e){return!!e},Hc:function(e,f){return f?c:d},Nc:function(e){return this.Cc(x[e])},Jc:null})},H:(a,b,c,d,e,f,g,h,l,k,m,p,q)=>{m=R(m);f=U(e,f);h&&=U(g,h);k&&=U(l,k);q=U(p,q);var r=yc(m);xc(r,function(){Oc(`Cannot construct ${m} due to unbound types`,[d])});Q([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var A=u.Ac;var E=A.$c}else E=tc.prototype;u=uc(m,function(...Ea){if(Object.getPrototypeOf(this)!==
I)throw new S(`Use 'new' to construct ${m}`);if(void 0===H.bd)throw new S(`${m} has no accessible constructor`);var L=H.bd[Ea.length];if(void 0===L)throw new S(`Tried to invoke ctor of ${m} with invalid number of parameters (${Ea.length}) - expected (${Object.keys(H.bd).toString()}) parameters instead!`);return L.apply(this,Ea)});var I=Object.create(E,{constructor:{value:u}});u.prototype=I;var H=new zc(m,u,I,q,A,f,h,k);if(H.Kc){var M;(M=H.Kc).pd??(M.pd=[]);H.Kc.pd.push(H)}A=new Jc(m,H,!0,!1,!1);M=
new Jc(m+"*",H,!1,!1,!1);E=new Jc(m+" const*",H,!1,!0,!1);vc[a]={pointerType:M,fe:E};Kc(r,u);return[A,M,E]})},p:(a,b,c,d,e,f,g,h)=>{var l=Rc(c,d);b=R(b);b=Sc(b);f=U(e,f);Q([],[a],k=>{function m(){Oc(`Cannot call ${p} due to unbound types`,l)}k=k[0];var p=`${k.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=k.Ac.constructor;void 0===q[b]?(m.ad=c-1,q[b]=m):(wc(q,b,p),q[b].Fc[c-1]=m);Q([],l,r=>{r=Qc(p,[r[0],null].concat(r.slice(1)),null,f,g,h);void 0===q[b].Fc?(r.ad=c-1,q[b]=r):q[b].Fc[c-
1]=r;if(k.Ac.pd)for(const u of k.Ac.pd)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})},K:(a,b,c,d,e,f)=>{var g=Rc(b,c);e=U(d,e);Q([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.Ac.bd&&(h.Ac.bd=[]);if(void 0!==h.Ac.bd[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.Ac.bd[b-1]=()=>{Oc(`Cannot construct ${h.name} due to unbound types`,
g)};Q([],g,k=>{k.splice(1,0,null);h.Ac.bd[b-1]=Qc(l,k,null,e,f);return[]});return[]})},l:(a,b,c,d,e,f,g,h,l)=>{var k=Rc(c,d);b=R(b);b=Sc(b);f=U(e,f);Q([],[a],m=>{function p(){Oc(`Cannot call ${q} due to unbound types`,k)}m=m[0];var q=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.Ac.Ge.push(b);var r=m.Ac.$c,u=r[b];void 0===u||void 0===u.Fc&&u.className!==m.name&&u.ad===c-2?(p.ad=c-2,p.className=m.name,r[b]=p):(wc(r,b,q),r[b].Fc[c-2]=p);Q([],k,A=>{A=Qc(q,A,m,f,g,l);void 0===r[b].Fc?
(A.ad=c-2,r[b]=A):r[b].Fc[c-2]=A;return[]});return[]})},C:(a,b,c,d,e,f,g,h,l,k)=>{b=R(b);e=U(d,e);Q([],[a],m=>{m=m[0];var p=`${m.name}.${b}`,q={get(){Oc(`Cannot access ${p} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};q.set=l?()=>Oc(`Cannot access ${p} due to unbound types`,[c,g]):()=>{throw new S(p+" is a read-only property");};Object.defineProperty(m.Ac.$c,b,q);Q([],l?[c,g]:[c],r=>{var u=r[0],A={get(){var I=Tc(this,m,p+" getter");return u.Cc(e(f,I))},enumerable:!0};if(l){l=U(h,l);
var E=r[1];A.set=function(I){var H=Tc(this,m,p+" setter"),M=[];l(k,H,E.Hc(M,I));cc(M)}}Object.defineProperty(m.Ac.$c,b,A);return[]});return[]})},Ya:a=>P(a,Xc),w:(a,b,c,d)=>{function e(){}b=R(b);e.values={};P(a,{name:b,constructor:e,Cc:function(f){return this.constructor.values[f]},Hc:(f,g)=>g.value,Nc:Yc(b,c,d),Jc:null});xc(b,e)},o:(a,b,c)=>{var d=Zc(a,"enum");b=R(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:uc(`${d.name}_${b}`,function(){})}});a.values[c]=
d;a[b]=d},Aa:(a,b,c)=>{b=R(b);P(a,{name:b,Cc:d=>d,Hc:(d,e)=>e,Nc:$c(b,c),Jc:null})},Q:(a,b,c,d,e,f,g)=>{var h=Rc(b,c);a=R(a);a=Sc(a);e=U(d,e);xc(a,function(){Oc(`Cannot call ${a} due to unbound types`,h)},b-1);Q([],h,l=>{Kc(a,Qc(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})},P:(a,b,c,d,e)=>{b=R(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}P(a,{name:b,Cc:f,Hc:(h,l)=>l,Nc:kc(b,c,0!==d),Jc:null})},D:(a,b,c)=>{function d(f){return new e(w.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,
Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);P(a,{name:c,Cc:d,Nc:d},{se:!0})},Za:(a,b)=>{b=R(b);P(a,{name:b,Cc(c){var d=G(c+4,C[c>>2],!0);V(c);return d},Hc(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var f=e?pb(d):d.length;var g=Fd(4+f+1),h=g+4;C[g>>2]=f;e?qb(d,x,h,f+1):x.set(d,h);
null!==c&&c.push(V,g);return g},Nc:dc,Jc(c){V(c)}})},ia:(a,b,c)=>{c=R(c);if(2===b){var d=bd;var e=cd;var f=dd}else d=ed,e=fd,f=gd;P(a,{name:c,Cc:g=>{var h=d(g+4,C[g>>2]*b,!0);V(g);return h},Hc:(g,h)=>{if("string"!=typeof h)throw new S(`Cannot pass non-string to C++ string type ${c}`);var l=f(h),k=Fd(4+l+b);C[k>>2]=l/b;e(h,k+4,l+b);null!==g&&g.push(V,k);return k},Nc:dc,Jc(g){V(g)}})},Ha:(a,b,c,d,e,f)=>{bc[a]={name:R(b),Ed:U(c,d),Uc:U(e,f),Od:[]}},bb:(a,b,c,d,e,f,g,h,l,k)=>{bc[a].Od.push({je:R(b),qe:c,
hd:U(d,e),pe:f,Je:g,Ie:U(h,l),Ke:k})},$a:(a,b)=>{b=R(b);P(a,{Rd:!0,name:b,Cc:()=>{},Hc:()=>{}})},rb:()=>{Fa=!1;Da=0},lb:()=>{throw new la;},A:(a,b,c)=>{var [d,...e]=kd(a,b);b=d.Hc.bind(d);var f=e.map(l=>l.Nc.bind(l));a--;var g={toValue:W};a=f.map((l,k)=>{var m=`argFromPtr${k}`;g[m]=l;return`${m}(args${k?"+"+8*k:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=nd,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;d.Rd||(g.toReturnWire=b,g.emval_returnValue=ld,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return jd(uc(h,c))},Kb:Wc,F:a=>{if(!a)return T(od);a=nd(a);return T(od[a])},X:a=>{a=nd(a);return T(n[a])},gb:(a,b)=>{a=W(a);b=W(b);return T(a[b])},N:a=>{9<a&&(Vc[a+1]+=1)},fb:(a,b)=>{a=W(a);b=
W(b);return a instanceof b},z:(a,b,c,d,e)=>hd[a](b,c,d,e),pa:a=>{a=W(a);return"number"==typeof a},da:a=>{a=W(a);return"string"==typeof a},R:a=>T(nd(a)),hb:a=>{var b=W(a);cc(b);Wc(a)},db:(a,b,c)=>{a=W(a);b=W(b);c=W(c);a[b]=c},Ja:a=>{a=W(a);return T(typeof a)},ub:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getUTCSeconds();B[b+4>>2]=a.getUTCMinutes();B[b+8>>2]=a.getUTCHours();B[b+12>>2]=a.getUTCDate();B[b+16>>2]=a.getUTCMonth();B[b+20>>2]=a.getUTCFullYear()-
1900;B[b+24>>2]=a.getUTCDay();B[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},vb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=a.getFullYear();B[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?qd:pd)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());
c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},sb:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=O(d),l=FS.ed(h,a,e,b,c),k=l.yc;B[f>>2]=l.Gd;C[g>>2]=k;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.Bc}},tb:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=O(e);
if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.uc(43);d&2||FS.gd(g,x.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.Bc}},Jb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();C[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(qb(a,x,c,
17),qb(b,x,d,17)):(qb(a,x,d,17),qb(b,x,c,17))},Fb:function(a,b,c){if(!(0<=a&&3>=a))return 28;D[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},O:()=>Date.now(),Na:a=>t(G(a)),cb:()=>{Da+=1;throw"unwind";},ob:()=>2147483648,Pa:()=>performance.now(),mb:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);
wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Sa:(a,b)=>{var c=0,d=0,e;for(e of td()){var f=b+c;C[a+d>>2]=f;c+=qb(e,x,f,Infinity)+1;d+=4}return 0},Ta:(a,b)=>{var c=td();C[a>>2]=c.length;a=0;for(var d of c)a+=pb(d)+1;C[b>>2]=a;return 0},M:Ja,ga:function(a){try{var b=O(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.Bc}},xb:function(a,b){try{var c=O(a),d=c.Dc?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;w[b]=d;y[b+2>>1]=0;D[b+8>>3]=
BigInt(0);D[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.Bc}},Qa:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],l=C[a+4>>2];a+=8;var k=FS.read(e,w,h,l,f);if(0>k){var m=-1;break a}b+=k;if(k<l)break;"undefined"!=typeof f&&(f+=k)}m=b}C[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.Bc}},wb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=O(a);FS.llseek(e,b,c);D[d>>3]=BigInt(e.position);e.xd&&0===b&&0===c&&(e.xd=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.Bc}},ta:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],l=C[a+4>>2];a+=8;var k=FS.write(e,w,h,l,f);if(0>k){var m=-1;break a}b+=k;if(k<l)break;"undefined"!=typeof f&&(f+=k)}m=b}C[d>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return p.Bc}},za:function(a,b,c,d){var e=
C[(a>>2)+1],f=C[(a>>2)+6],g=C[(a>>2)+2],h=C[(a>>2)+5];a=Ed(C[(a>>2)+3])[1];var l=X(),k=l,m=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),p=!0;for(var q=0;q<f;q++){var r=C[(d>>2)+q],u=Ed(C[(g>>2)+q]),A=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(C[r>>2]);break;case 2:m.push(ra[r>>2]);break;case 3:m.push(sa[r>>3]);break;case 5:m.push(x[r]);break;case 6:m.push(w[r]);break;case 7:m.push(z[r>>1]);break;case 8:m.push(y[r>>
1]);break;case 11:case 12:m.push(ta[r>>3]);break;case 4:m.push(ta[r>>3]);m.push(ta[(r>>3)+1]);break;case 13:u=C[A>>2];A=z[A+4>>1];k-=u;k&=~(A-1);w.subarray(k,k+u).set(w.subarray(r,r+u));m.push(k);break;case 14:m.push(C[r>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(q=e-1;q>=f;q--)switch(r=C[(d>>2)+q],u=Ed(C[(g>>2)+q]),A=u[0],u=u[1],u){case 5:case 6:--k;k&=-1;x[k]=x[r];break;case 7:case 8:k-=2;k&=-2;z[k>>1]=z[r>>1];break;case 1:case 9:case 10:case 2:k-=
4;k&=-4;C[k>>2]=C[r>>2];break;case 3:case 11:case 12:k-=8;k&=-8;C[k>>2]=C[r>>2];C[(k>>2)+1]=C[(r>>2)+1];break;case 4:k-=16;k&=-8;C[k>>2]=C[r>>2];C[(k>>2)+1]=C[(r>>2)+1];C[(k>>2)+2]=C[(r>>2)+2];C[(k>>2)+3]=C[(r>>2)+3];break;case 13:k-=4;k&=-4;h.push([k,r,C[A>>2],z[A+4>>1]]);break;case 14:k-=4;k&=-4;C[k>>2]=C[r>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(k);for(q=0;q<h.length;q++)e=h[q],d=e[0],r=e[1],u=e[2],A=e[3],k-=u,k&=~(A-1),
w.subarray(k,k+u).set(w.subarray(r,r+u)),C[d>>2]=k}Y(k);Ad(0);b=J(b).apply(null,m);Y(l);if(!p)switch(a){case 0:break;case 1:case 9:case 10:C[c>>2]=b;break;case 2:ra[c>>2]=b;break;case 3:sa[c>>3]=b;break;case 5:case 6:x[c+0]=b;break;case 7:case 8:z[c>>1]=b;break;case 11:case 12:ta[c>>3]=b;break;case 14:C[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}},Ia:Id,ca:Jd,qa:Kd,T:Ld,wa:Md,r:Nd,d:Od,x:Pd,Ka:Qd,h:Rd,v:Sd,c:Td,t:Ud,Va:Vd,s:Wd,B:Xd,
ha:Yd,xa:Zd,Y:$d,Ua:ae,kb:be,Wa:ce,jb:de,ib:ee,u:fe,V:ge,va:he,aa:ie,Ma:je,fa:ke,k:le,b:me,eb:ne,oa:oe,i:pe,ea:qe,U:re,ja:se,S:te,f:ue,Fa:ve,Ea:we,na:xe,ba:ye,la:ze,ma:Ae,n:Be,m:Ce,y:De,q:Ee,W:Fe,G:Ge,L:He,Da:Ie,ka:Je,Ca:Ke,$:Le,La:Me,_:Ne,ra:Oe,Z:Pe,Ib:Ga,nb:function(a,b){try{return kb(x.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.Bc}}};function me(a,b){var c=X();try{J(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0)}}
function ue(a,b,c,d){var e=X();try{J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function Rd(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function le(a){var b=X();try{J(a)()}catch(c){Y(b);if(!(c instanceof v))throw c;Z(1,0)}}function Od(a,b){var c=X();try{return J(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0)}}function Nd(a){var b=X();try{return J(a)()}catch(c){Y(b);if(!(c instanceof v))throw c;Z(1,0)}}
function Ce(a,b,c,d,e,f){var g=X();try{J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function Td(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function Be(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Wd(a,b,c,d,e,f){var g=X();try{return J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function pe(a,b,c){var d=X();try{J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function Xd(a,b,c,d,e,f,g){var h=X();try{return J(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}function Ud(a,b,c,d,e){var f=X();try{return J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Ld(a,b,c,d,e,f){var g=X();try{return J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function Kd(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function qe(a,b,c,d){var e=X();try{J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}function re(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function Sd(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}
function ne(a,b,c){var d=X();try{J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function Id(a,b){var c=X();try{return J(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0)}}function He(a,b,c,d,e,f,g,h,l,k,m){var p=X();try{J(a)(b,c,d,e,f,g,h,l,k,m)}catch(q){Y(p);if(!(q instanceof v))throw q;Z(1,0)}}function De(a,b,c,d,e,f,g){var h=X();try{J(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}
function Ee(a,b,c,d,e,f,g,h){var l=X();try{J(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}function Jd(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function te(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function ve(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}
function oe(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function ye(a,b,c,d,e,f,g,h){var l=X();try{J(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}function we(a,b,c,d,e,f,g,h,l,k){var m=X();try{J(a)(b,c,d,e,f,g,h,l,k)}catch(p){Y(m);if(!(p instanceof v))throw p;Z(1,0)}}function xe(a,b,c,d,e,f,g,h,l){var k=X();try{J(a)(b,c,d,e,f,g,h,l)}catch(m){Y(k);if(!(m instanceof v))throw m;Z(1,0)}}
function Ae(a,b,c,d,e,f){var g=X();try{J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function ze(a,b,c,d,e,f,g){var h=X();try{J(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}function Je(a,b,c,d,e,f,g,h,l,k,m,p,q){var r=X();try{J(a)(b,c,d,e,f,g,h,l,k,m,p,q)}catch(u){Y(r);if(!(u instanceof v))throw u;Z(1,0)}}function Ie(a,b,c,d,e,f,g,h,l,k,m,p){var q=X();try{J(a)(b,c,d,e,f,g,h,l,k,m,p)}catch(r){Y(q);if(!(r instanceof v))throw r;Z(1,0)}}
function Ge(a,b,c,d,e,f,g,h,l,k){var m=X();try{J(a)(b,c,d,e,f,g,h,l,k)}catch(p){Y(m);if(!(p instanceof v))throw p;Z(1,0)}}function Fe(a,b,c,d,e,f,g,h,l){var k=X();try{J(a)(b,c,d,e,f,g,h,l)}catch(m){Y(k);if(!(m instanceof v))throw m;Z(1,0)}}function Ke(a,b,c,d,e,f,g,h,l,k,m,p,q,r){var u=X();try{J(a)(b,c,d,e,f,g,h,l,k,m,p,q,r)}catch(A){Y(u);if(!(A instanceof v))throw A;Z(1,0)}}function se(a,b,c,d,e,f){var g=X();try{J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function ce(a,b,c,d,e,f){var g=X();try{return J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function Vd(a,b,c,d,e,f){var g=X();try{return J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}function Yd(a,b,c,d,e,f,g,h){var l=X();try{return J(a)(b,c,d,e,f,g,h)}catch(k){Y(l);if(!(k instanceof v))throw k;Z(1,0)}}function Zd(a,b,c,d,e,f,g,h,l,k,m){var p=X();try{return J(a)(b,c,d,e,f,g,h,l,k,m)}catch(q){Y(p);if(!(q instanceof v))throw q;Z(1,0)}}
function ie(a,b,c,d,e){var f=X();try{return J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0);return 0n}}function ae(a,b,c,d,e,f,g,h,l,k,m,p,q){var r=X();try{return J(a)(b,c,d,e,f,g,h,l,k,m,p,q)}catch(u){Y(r);if(!(u instanceof v))throw u;Z(1,0)}}function Md(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0)}}
function $d(a,b,c,d,e,f,g,h,l,k,m,p){var q=X();try{return J(a)(b,c,d,e,f,g,h,l,k,m,p)}catch(r){Y(q);if(!(r instanceof v))throw r;Z(1,0)}}function Le(a,b,c,d,e,f,g,h,l,k,m,p,q,r,u,A){var E=X();try{J(a)(b,c,d,e,f,g,h,l,k,m,p,q,r,u,A)}catch(I){Y(E);if(!(I instanceof v))throw I;Z(1,0)}}function ge(a,b){var c=X();try{return J(a)(b)}catch(d){Y(c);if(!(d instanceof v))throw d;Z(1,0);return 0n}}
function he(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0);return 0n}}function je(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0);return 0n}}function fe(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function Oe(a,b,c){var d=X();try{J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}
function Pd(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function ke(a,b,c,d){var e=X();try{return J(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof v))throw f;Z(1,0);return 0n}}function Me(a,b,c,d,e,f,g,h,l,k,m){var p=X();try{J(a)(b,c,d,e,f,g,h,l,k,m)}catch(q){Y(p);if(!(q instanceof v))throw q;Z(1,0)}}function Ne(a,b,c,d,e,f,g){var h=X();try{J(a)(b,c,d,e,f,g)}catch(l){Y(h);if(!(l instanceof v))throw l;Z(1,0)}}
function Pe(a,b,c,d,e){var f=X();try{J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}function be(a,b,c,d,e,f,g,h,l,k,m,p,q,r,u,A,E){var I=X();try{return J(a)(b,c,d,e,f,g,h,l,k,m,p,q,r,u,A,E)}catch(H){Y(I);if(!(H instanceof v))throw H;Z(1,0)}}function Qd(a,b,c){var d=X();try{return J(a)(b,c)}catch(e){Y(d);if(!(e instanceof v))throw e;Z(1,0)}}function de(a,b,c,d,e){var f=X();try{return J(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof v))throw g;Z(1,0)}}
function ee(a,b,c,d,e,f){var g=X();try{return J(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof v))throw h;Z(1,0)}}
function Re(){function a(){n.calledRun=!0;if(!ja){ua=!0;n.noFSInit||FS.yd||FS.init();Se.Mb();Ra(yd);FS.Qd=!1;oa?.(n);n.onRuntimeInitialized?.();if(!n.noInitialRun){var b=Gd;try{var c=b(0,0);Ja(c,!0)}catch(d){Ca(d)}}if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)b=n.postRun.shift(),Sa.push(b);Ra(Sa)}}if(0<Cb)Db=Re;else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Ta.push(n.preRun.shift());Ra(Ta);0<Cb?Db=Re:n.setStatus?
(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);a()},1)):a()}}var Se;
Se=await (async function(){function a(c){Se=c.exports;qa=Se.Lb;wa();Xa=Se.Ob;c=Se;Mc=c.Nb;Fd=c.Pb;n._main=Gd=c.Qb;V=c.Rb;Ia=c.Sb;n._calloc=c.Tb;Dd=c.Ub;Cd=c.Vb;n._emscripten_builtin_malloc=c.Wb;Ha=c.Xb;n.___libc_calloc=c.Yb;n.___libc_free=c.Zb;n.___libc_malloc=c._b;n._emscripten_builtin_free=c.$b;xb=c.ac;n._strndup=c.bc;n.__Znaj=c.cc;n.__ZnajSt11align_val_t=c.dc;n.__Znwj=c.ec;n.__ZnwjSt11align_val_t=c.fc;n.___libc_realloc=c.gc;n._emscripten_builtin_calloc=c.hc;n._emscripten_builtin_realloc=
c.ic;n._malloc_size=c.jc;n._malloc_usable_size=c.kc;n._reallocf=c.lc;Z=c.mc;bb=c.nc;Y=c.oc;Ad=c.pc;X=c.qc;Bd=c.rc;cb=c.sc;Hd=c.tc;return Se}var b={a:Qe};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(b,(d,e)=>{c(a(d,e))})});xa??=n.locateFile?n.locateFile("vips.wasm",da):da+"vips.wasm";return a((await Aa(b)).instance)}());Re();ua?moduleRtn=n:moduleRtn=new Promise((a,b)=>{oa=a;pa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);
