var Vips=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var p=moduleArg;p.workaroundCors&&(p.mainScriptUrlOrBlob=p.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var aa="./this.program",ba="",ca;try{ba=(new URL(".",_scriptName)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),q=console.error.bind(console),ea,fa=!1,ha;class t extends Error{}
class ia extends t{}class ja extends t{constructor(a){super(a);this.ge=a;a=ka(a);this.name=a[0];this.message=a[1]}}var la,ma,u,v,w,y,B,C,na,oa,D,pa,qa=!1,ra=!1;function sa(){var a=ta.buffer;u=new Int8Array(a);w=new Int16Array(a);v=new Uint8Array(a);y=new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);D=new BigInt64Array(a);pa=new BigUint64Array(a)}
function G(a){p.onAbort?.(a);a="Aborted("+a+")";q(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var ua;async function va(a){if(!ea)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==ua&&ea)a=new Uint8Array(ea);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),G(d)}}
async function xa(a){var b=ua;if(!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return wa(b,a)}var za=a=>{if(!(a instanceof ya||"unwind"==a))throw a;};class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=0,Ca=a=>{ha=a;Ba||0<Aa||(p.onExit?.(a),fa=!0);throw new ya(a);},Fa=a=>{ha=a;if(!(Ba||0<Aa)){Da();FS.oe=!1;Ea(0);for(var b of FS.streams)b&&FS.close(b);ra=!0}Ca(a)},Ga=a=>{if(!ra&&!fa)try{if(a(),!(ra||Ba||0<Aa))try{Fa(ha)}catch(b){za(b)}}catch(b){za(b)}},Ha=a=>{Aa+=1;setTimeout(()=>{--Aa;Ga(a)},1E4)},Ia=[],Ja=!1;
function Ka(){function a(){Ja=document.pointerLockElement===p.canvas}if(!La){La=!0;Ia.push({canHandle:function(c){return!p.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Ma(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Ma(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,
0,0);URL.revokeObjectURL(f);g(c)};k.onerror=()=>{q(`Image ${f} could not be decoded`);h()};k.src=f})}});Ia.push({canHandle:function(c){return!p.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:Ma(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){q(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="",m=0,n=0,r=0;r<c.length;r++)for(m=m<<8|c[r],n+=8;6<=n;){var x=m>>n-6&63;n-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==n?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],l+="=="):4==n&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;Ha(()=>{f(k)})})}});var b=p.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),p.elementPointerLock&&b.addEventListener("click",c=>{!Ja&&p.canvas.requestPointerLock&&(p.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Ma(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Na={},La,Oa=a=>{for(;0<a.length;)a.shift()(p)},Pa=[],Qa=[],Ba=!1,Ra=new TextDecoder,Sa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},H=(a,b,c)=>a?Ra.decode(v.subarray(a,Sa(v,a,b,c))):"",Ta=[],Ua=0,Va=0;class Wa{constructor(a){this.ge=a;this.pd=a-24}init(a,b){C[this.pd+16>>2]=0;C[this.pd+4>>2]=a;C[this.pd+8>>2]=b}}
var Za=a=>{var b=Va?.ge;if(!b)return Xa(0),0;var c=new Wa(b);C[c.pd+16>>2]=b;var d=C[c.pd+4>>2];if(!d)return Xa(0),b;for(var e of a){if(0===e||e===d)break;if(Ya(e,d,c.pd+16))return Xa(e),b}Xa(d);return b},$a=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ab=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=$a(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");
return(b?"/":"")+a},bb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},cb=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],db=(a,b)=>ab(a+"/"+b),eb=()=>a=>crypto.getRandomValues(a),fb=a=>{(fb=eb())(a)},gb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
$a(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},hb=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=gb(a).slice(1);b=gb(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},ib=a=>{var b=Sa(a,0);return Ra.decode(a.buffer?a.subarray(0,
b):new Uint8Array(a.slice(0,b)))},jb=[],kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},lb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=
128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},mb=a=>{var b=Array(kb(a)+1);a=lb(a,b,0,b.length);b.length=a;return b},nb=[];function ob(a,b){nb[a]={input:[],output:[],Qd:b};FS.registerDevice(a,pb)}
var pb={open(a){var b=nb[a.node.ce];if(!b)throw new FS.ld(43);a.ud=b;a.seekable=!1},close(a){a.ud.Qd.ie(a.ud)},ie(a){a.ud.Qd.ie(a.ud)},read(a,b,c,d){if(!a.ud||!a.ud.Qd.Fe)throw new FS.ld(60);for(var e=0,f=0;f<d;f++){try{var g=a.ud.Qd.Fe(a.ud)}catch(h){throw new FS.ld(29);}if(void 0===g&&0===e)throw new FS.ld(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Ld=Date.now());return e},write(a,b,c,d){if(!a.ud||!a.ud.Qd.ue)throw new FS.ld(60);try{for(var e=0;e<d;e++)a.ud.Qd.ue(a.ud,b[c+e])}catch(f){throw new FS.ld(29);
}d&&(a.node.Dd=a.node.Cd=Date.now());return e}},qb={Fe(){a:{if(!jb.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}jb=mb(a)}a=jb.shift()}return a},ue(a,b){null===b||10===b?(da(ib(a.output)),a.output=[]):0!=b&&a.output.push(b)},ie(a){0<a.output?.length&&(da(ib(a.output)),a.output=[])},kf(){return{Kf:25856,Mf:5,Jf:191,Lf:35387,If:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},lf(){return 0},mf(){return[24,
80]}},rb={ue(a,b){null===b||10===b?(q(ib(a.output)),a.output=[]):0!=b&&a.output.push(b)},ie(a){0<a.output?.length&&(q(ib(a.output)),a.output=[])}},tb=a=>{a=65536*Math.ceil(a/65536);var b=sb(65536,a);b&&v.fill(0,b,b+a);return b},J={Jd:null,mount(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.ld(63);J.Jd||(J.Jd={dir:{node:{Gd:J.nd.Gd,Id:J.nd.Id,Vd:J.nd.Vd,Od:J.nd.Od,rename:J.nd.rename,unlink:J.nd.unlink,rmdir:J.nd.rmdir,
de:J.nd.de,symlink:J.nd.symlink},stream:{llseek:J.od.llseek}},file:{node:{Gd:J.nd.Gd,Id:J.nd.Id},stream:{llseek:J.od.llseek,read:J.od.read,write:J.od.write,Wd:J.od.Wd,Yd:J.od.Yd}},link:{node:{Gd:J.nd.Gd,Id:J.nd.Id,readlink:J.nd.readlink},stream:{}},ye:{node:{Gd:J.nd.Gd,Id:J.nd.Id},stream:FS.Ue}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.nd=J.Jd.dir.node,c.od=J.Jd.dir.stream,c.qd={}):FS.isFile(c.mode)?(c.nd=J.Jd.file.node,c.od=J.Jd.file.stream,c.xd=0,c.qd=null):FS.isLink(c.mode)?(c.nd=J.Jd.link.node,
c.od=J.Jd.link.stream):FS.isChrdev(c.mode)&&(c.nd=J.Jd.ye.node,c.od=J.Jd.ye.stream);c.Ld=c.Dd=c.Cd=Date.now();a&&(a.qd[b]=c,a.Ld=a.Dd=a.Cd=c.Ld);return c},Tf(a){return a.qd?a.qd.subarray?a.qd.subarray(0,a.xd):new Uint8Array(a.qd):new Uint8Array(0)},nd:{Gd(a){var b={};b.We=FS.isChrdev(a.mode)?a.id:1;b.jf=a.id;b.mode=a.mode;b.qf=1;b.uid=0;b.gf=0;b.ce=a.ce;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.xd:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.Ld=new Date(a.Ld);b.Dd=new Date(a.Dd);
b.Cd=new Date(a.Cd);b.Te=4096;b.xe=Math.ceil(b.size/b.Te);return b},Id(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.xd!=b&&(0==b?(a.qd=null,a.xd=0):(c=a.qd,a.qd=new Uint8Array(b),c&&a.qd.set(c.subarray(0,Math.min(b,a.xd))),a.xd=b)))},Vd(){J.me||(J.me=new FS.ld(44),J.me.stack="<generic error, no stack>");throw J.me;},Od(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.qd)throw new FS.ld(55);
ub(d)}delete a.parent.qd[a.name];b.qd[c]=a;a.name=c;b.Cd=b.Dd=a.parent.Cd=a.parent.Dd=Date.now()},unlink(a,b){delete a.qd[b];a.Cd=a.Dd=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.qd)throw new FS.ld(55);delete a.qd[b];a.Cd=a.Dd=Date.now()},de(a){return[".","..",...Object.keys(a.qd)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.ld(28);return a.link}},od:{read(a,b,c,d,e){var f=a.node.qd;if(e>=a.node.xd)return 0;a=Math.min(a.node.xd-
e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.Dd=a.Cd=Date.now();if(b.subarray&&(!a.qd||a.qd.subarray)){if(f)return a.qd=b.subarray(c,c+d),a.xd=d;if(0===a.xd&&0===e)return a.qd=b.slice(c,c+d),a.xd=d;if(e+d<=a.xd)return a.qd.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.qd?a.qd.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.qd,a.qd=new Uint8Array(f),
0<a.xd&&a.qd.set(g.subarray(0,a.xd),0));if(a.qd.subarray&&b.subarray)a.qd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.qd[e+f]=b[c+f];a.xd=Math.max(a.xd,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.xd);if(0>b)throw new FS.ld(28);return b},Wd(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.ld(43);a=a.node.qd;if(e&2||!a||a.buffer!==u.buffer){d=!0;e=tb(b);if(!e)throw new FS.ld(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{pd:e,we:d}},Yd(a,b,c,d){J.od.write(a,b,0,d,c,!1);return 0}}},vb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},wb=async a=>{a=await ca(a);return new Uint8Array(a)},xb=0,yb=null,zb=()=>{xb--;p.monitorRunDependencies?.(xb);if(0==xb&&yb){var a=yb;yb=null;a()}},Ab=()=>{xb++;p.monitorRunDependencies?.(xb)},Bb=async(a,b)=>{"undefined"!=typeof Na&&Ka();for(var c of Ia)if(c.canHandle(b))return c.handle(a,b);return a},Cb=async(a,b,c,d,e,f,g,h)=>{var k=
b?gb(ab(a+"/"+b)):a,l=`cp ${k}`;Ab(l);try{var m=c;"string"==typeof c&&(m=await wb(c));m=await Bb(m,k);h?.();f||FS.createDataFile(a,b,m,d,e,g)}finally{zb(l)}};function L(a,b){var c=FS.isDir(a.mode)?(c=Db(a,"x"))?c:a.nd.Vd?0:2:54;if(c)throw new FS.ld(c);for(c=FS.Pd[Eb(a.id,b)];c;c=c.Xd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.Vd(a,b)}function ub(a){var b=Eb(a.parent.id,a.name);if(FS.Pd[b]===a)FS.Pd[b]=a.Xd;else for(b=FS.Pd[b];b;){if(b.Xd===a){b.Xd=a.Xd;break}b=b.Xd}}
function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.Pd.length}function Fb(a){var b=Eb(a.parent.id,a.name);a.Xd=FS.Pd[b];FS.Pd[b]=a}function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Db(a,b){if(FS.Ge)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Hb(a,b){if(!FS.isDir(a.mode))return 54;try{return L(a,b),20}catch(c){}return Db(a,"wx")}function Ib(a,b,c){try{var d=L(a,b)}catch(e){return e.sd}if(a=Db(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.$d(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function Jb(a,b){if(!a)throw new FS.ld(b);return a}function M(a){a=FS.df(a);if(!a)throw new FS.ld(8);return a}
function Kb(a,b=-1){a=Object.assign(new FS.Re,a);if(-1==b)a:{for(b=0;b<=FS.Se;b++)if(!FS.streams[b])break a;throw new FS.ld(33);}a.Md=b;return FS.streams[b]=a}function Lb(a,b=-1){a=Kb(a,b);a.od?.Of?.(a);return a}function Mb(a,b,c){var d=a?.od.Id;a=d?a:b;d??=b.nd.Id;Jb(d,63);d(a,c)}function Nb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.ae)}return b}
function Ob(a){var b={Hf:4096,Rf:4096,xe:1E6,Gf:5E5,Ff:5E5,files:FS.te,Pf:FS.te-1,Sf:42,flags:2,Wf:255};a.nd.Pe&&Object.assign(b,a.nd.Pe(a.mount.sf.root));return b}function Pb(a,b,c,d){Mb(a,b,{mode:c&4095|b.mode&-4096,Cd:Date.now(),Ce:d})}function Qb(a,b,c){if(FS.isDir(b.mode))throw new FS.ld(31);if(!FS.isFile(b.mode))throw new FS.ld(28);var d=Db(b,"w");if(d)throw new FS.ld(d);Mb(a,b,{size:c,timestamp:Date.now()})}
function Rb(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=ab(a+"/"+b);return FS.create(b,vb(c,d))}function Sb(a){if(!(a.nf||a.pf||a.link||a.qd))if(globalThis.XMLHttpRequest)G("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.qd=(void 0)(a.url)}catch(b){throw new FS.ld(29);}}
var FS={root:null,ae:[],Be:{},streams:[],te:1,Pd:null,ze:"/",oe:!1,Ge:!0,$e:null,le:0,Oe:{},ld:class{name="ErrnoError";constructor(a){this.sd=a}},Re:class{Nd={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Nd.flags}set flags(a){this.Nd.flags=a}get position(){return this.Nd.position}set position(a){this.Nd.position=a}},Qe:class{nd={};od={};Hd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.te++;this.name=b;this.mode=c;this.ce=
d;this.Ld=this.Dd=this.Cd=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get pf(){return FS.isDir(this.mode)}get nf(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.ld(44);b.he??(b.he=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-
1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=bb(e),FS.$d(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=ab(e+"/"+a[f]);try{d=L(d,a[f])}catch(h){if(44===h?.sd&&g&&b.rf)return{path:e};throw h;}!d.Hd||g&&!b.he||(d=d.Hd.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.nd.readlink)throw new FS.ld(52);d=d.nd.readlink(d);"/"===d.charAt(0)||(d=bb(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.ld(32);},getPath(a){for(var b;;){if(FS.$d(a))return a=
a.mount.Ie,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.Qe(a,b,c,d);Fb(a);return a},$d(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},Se:4096,df:a=>FS.streams[a],Ue:{open(a){a.od=FS.bf(a.node.ce).od;a.od.open?.(a)},llseek(){throw new FS.ld(70);
}},re:a=>a>>8,Uf:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Be[a]={od:b}},bf:a=>FS.Be[a],syncfs(a,b){function c(h){FS.le--;return b(h)}function d(h){if(h){if(!d.Ye)return d.Ye=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.le++;1<FS.le&&q(`warning: ${FS.le} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Nb(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.ld(10);
if(!d&&c){var e=FS.lookupPath(c,{he:!1});c=e.path;e=e.node;if(e.Hd)throw new FS.ld(10);if(!FS.isDir(e.mode))throw new FS.ld(54);}b={type:a,sf:b,Ie:c,ae:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.Hd=b,e.mount&&e.mount.ae.push(b));return a},unmount(a){a=FS.lookupPath(a,{he:!1});if(!a.node.Hd)throw new FS.ld(28);a=a.node;var b=a.Hd,c=Nb(b);for([,e]of Object.entries(FS.Pd))for(;e;){var d=e.Xd;c.includes(e.mount)&&ub(e);var e=d}a.Hd=null;a.mount.ae.splice(a.mount.ae.indexOf(b),1)},Vd(a,b){return a.nd.Vd(a,
b)},Od(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=cb(a);if(!a)throw new FS.ld(28);if("."===a||".."===a)throw new FS.ld(20);var e=Hb(d,a);if(e)throw new FS.ld(e);if(!d.nd.Od)throw new FS.ld(63);return d.nd.Od(d,a,b,c)},Pe(a){return Ob(FS.lookupPath(a,{follow:!0}).node)},Yf(a){return Ob(a.node)},create(a,b=438){return FS.Od(a,b&4095|32768,0)},mkdir(a,b=511){return FS.Od(a,b&1023|16384,0)},Vf(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.sd)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.Od(a,b|8192,c)},symlink(a,b){if(!gb(a))throw new FS.ld(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.ld(44);b=cb(b);var d=Hb(c,b);if(d)throw new FS.ld(d);if(!c.nd.symlink)throw new FS.ld(63);return c.nd.symlink(c,b,a)},rename(a,b){var c=bb(a),d=bb(b),e=cb(a),f=cb(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.ld(44);if(h.mount!==g.mount)throw new FS.ld(75);
var k=L(h,e);a=hb(a,d);if("."!==a.charAt(0))throw new FS.ld(28);a=hb(b,c);if("."!==a.charAt(0))throw new FS.ld(55);try{var l=L(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=Ib(h,e,b))throw new FS.ld(e);if(e=l?Ib(g,f,b):Hb(g,f))throw new FS.ld(e);if(!h.nd.rename)throw new FS.ld(63);if(k.Hd||l&&l.Hd)throw new FS.ld(10);if(g!==h&&(e=Db(h,"w")))throw new FS.ld(e);ub(k);try{h.nd.rename(k,g,f),k.parent=g}catch(m){throw m;}finally{Fb(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=cb(a);var c=
L(b,a),d=Ib(b,a,!0);if(d)throw new FS.ld(d);if(!b.nd.rmdir)throw new FS.ld(63);if(c.Hd)throw new FS.ld(10);b.nd.rmdir(b,a);ub(c)},de(a){a=FS.lookupPath(a,{follow:!0}).node;return Jb(a.nd.de,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.ld(44);a=cb(a);var c=L(b,a),d=Ib(b,a,!1);if(d)throw new FS.ld(d);if(!b.nd.unlink)throw new FS.ld(63);if(c.Hd)throw new FS.ld(10);b.nd.unlink(b,a);ub(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.ld(44);if(!a.nd.readlink)throw new FS.ld(28);
return a.nd.readlink(a)},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return Jb(a.nd.Gd,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Pb(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=M(a);Pb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;Mb(null,a,{timestamp:Date.now(),Ce:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=M(a);Mb(a,a.node,{timestamp:Date.now(),Ce:!1})},truncate(a,b){if(0>
b)throw new FS.ld(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Qb(null,a,b)},ftruncate(a,b){a=M(a);if(0>b||0===(a.flags&2097155))throw new FS.ld(28);Qb(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;Jb(a.nd.Id,63)(a,{Ld:b,Dd:c})},open(a,b,c=438){if(""===a)throw new FS.ld(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=
a;else{var e=a.endsWith("/");a=FS.lookupPath(a,{follow:!(b&131072),rf:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.ld(20);}else{if(e)throw new FS.ld(31);d=FS.Od(a,c|511,0);f=!0}if(!d)throw new FS.ld(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.ld(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==Gb(g)||g&576)?31:Db(e,Gb(g)):44)throw new FS.ld(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=Kb({node:d,path:FS.getPath(d),
flags:b,seekable:!0,position:0,od:d.od,Ef:[],error:!1});e.od.open&&e.od.open(e);f&&FS.chmod(d,c&511);!p.logReadFiles||b&1||a in FS.Oe||(FS.Oe[a]=1);return e},close(a){if(null===a.Md)throw new FS.ld(8);a.ne&&(a.ne=null);try{a.od.close&&a.od.close(a)}catch(b){throw b;}finally{FS.streams[a.Md]=null}a.Md=null},llseek(a,b,c){if(null===a.Md)throw new FS.ld(8);if(!a.seekable||!a.od.llseek)throw new FS.ld(70);if(0!=c&&1!=c&&2!=c)throw new FS.ld(28);a.position=a.od.llseek(a,b,c);a.Ef=[];return a.position},
read(a,b,c,d,e){if(0>d||0>e)throw new FS.ld(28);if(null===a.Md)throw new FS.ld(8);if(1===(a.flags&2097155))throw new FS.ld(8);if(FS.isDir(a.node.mode))throw new FS.ld(31);if(!a.od.read)throw new FS.ld(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.ld(70);b=a.od.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.ld(28);if(null===a.Md)throw new FS.ld(8);if(0===(a.flags&2097155))throw new FS.ld(8);if(FS.isDir(a.node.mode))throw new FS.ld(31);
if(!a.od.write)throw new FS.ld(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.ld(70);b=a.od.write(a,b,c,d,e,f);g||(a.position+=b);return b},Wd(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.ld(2);if(1===(a.flags&2097155))throw new FS.ld(2);if(!a.od.Wd)throw new FS.ld(43);if(!b)throw new FS.ld(28);return a.od.Wd(a,b,c,d,e)},Yd(a,b,c,d,e){return a.od.Yd?a.od.Yd(a,b,c,d,e):0},pe(a,b,c){if(!a.od.pe)throw new FS.ld(59);
return a.od.pe(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&G(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=ib(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(mb(b)));ArrayBuffer.isView(b)?FS.write(a,b,0,b.byteLength,void 0,c.Nf):G("Unsupported data type");
FS.close(a)},cwd:()=>FS.ze,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.ld(44);if(!FS.isDir(a.node.mode))throw new FS.ld(54);var b=Db(a.node,"x");if(b)throw new FS.ld(b);FS.ze=a.path},init(a,b,c){FS.oe=!0;a??=p.stdin;b??=p.stdout;c??=p.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",
0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Qf(a,b){a=FS.analyzePath(a,b);return a.De?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={$d:!1,De:!1,error:0,name:null,path:null,object:null,tf:!1,vf:null,uf:null};try{c=FS.lookupPath(a,{parent:!0}),d.tf=!0,d.vf=c.path,d.uf=c.node,d.name=cb(a),c=FS.lookupPath(a,{follow:!b}),d.De=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.$d="/"===c.path}catch(e){d.error=e.sd}return d},createPath(a,b){a=
"string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=ab(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.sd)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?ab(a+"/"+b):a);a=vb(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,
b,c,d){a=db("string"==typeof a?a:FS.getPath(a),b);b=vb(!!c,!!d);var e;(e=FS.createDevice).re??(e.re=64);e=FS.makedev(FS.createDevice.re++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=0,m=0;m<k;m++){try{var n=c()}catch(r){throw new FS.ld(29);}if(void 0===n&&0===l)throw new FS.ld(6);if(null===n||void 0===n)break;l++;g[h+m]=n}l&&(f.node.Ld=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.ld(29);}k&&
(f.node.Dd=f.node.Cd=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,n,r,x,z){m=m.node.qd;if(z>=m.length)return 0;x=Math.min(m.length-z,x);if(m.slice)for(var A=0;A<x;A++)n[r+A]=m[z+A];else for(A=0;A<x;A++)n[r+A]=m.get(z+A);return x}class g{se=!1;Nd=[];Zd=void 0;Ke=0;Je=0;get(m){if(!(m>this.length-1||0>m)){var n=m%this.Me;return this.Zd(m/this.Me|0)[n]}}zf(m){this.Zd=m}Le(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=m.status&&300>m.status||
304===m.status||G("Couldn't load "+c+". Status: "+m.status);var n=Number(m.getResponseHeader("Content-length")),r,x=(r=m.getResponseHeader("Accept-Ranges"))&&"bytes"===r;m=(r=m.getResponseHeader("Content-Encoding"))&&"gzip"===r;var z=1048576;x||(z=n);var A=this;A.zf(E=>{var I=E*z,F=(E+1)*z-1;F=Math.min(F,n-1);if("undefined"==typeof A.Nd[E]){var U=A.Nd;I>F&&G("invalid range ("+I+", "+F+") or no bytes requested!");F>n-1&&G("only "+n+" bytes available! programmer error!");var K=new XMLHttpRequest;K.open("GET",
c,!1);n!==z&&K.setRequestHeader("Range","bytes="+I+"-"+F);K.responseType="arraybuffer";K.overrideMimeType&&K.overrideMimeType("text/plain; charset=x-user-defined");K.send(null);200<=K.status&&300>K.status||304===K.status||G("Couldn't load "+c+". Status: "+K.status);I=void 0!==K.response?new Uint8Array(K.response||[]):mb(K.responseText||"");U[E]=I}"undefined"==typeof A.Nd[E]&&G("doXHR failed!");return A.Nd[E]});if(m||!n)z=n=1,z=n=this.Zd(0).length,da("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Ke=n;this.Je=z;this.se=!0}get length(){this.se||this.Le();return this.Ke}get Me(){this.se||this.Le();return this.Je}}if(globalThis.XMLHttpRequest){G("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var k=void 0}else k=c,h=void 0;var l=Rb(a,b,d,e);h?l.qd=h:k&&(l.qd=null,l.url=k);Object.defineProperties(l,{xd:{get:function(){return this.qd.length}}});a={};for(const [m,n]of Object.entries(l.od))a[m]=(...r)=>{Sb(l);
return n(...r)};a.read=(m,n,r,x,z)=>{Sb(l);return f(m,n,r,x,z)};a.Wd=(m,n,r)=>{Sb(l);var x=tb(n);if(!x)throw new FS.ld(48);f(m,u,x,n,r);return{pd:x,we:!0}};l.od=a;return l}};function Tb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():M(a).path;if(0==b.length){if(!c)throw new FS.ld(44);return a}return a+"/"+b}
function Ub(a,b){C[a>>2]=b.We;C[a+4>>2]=b.mode;C[a+8>>2]=b.qf;C[a+12>>2]=b.uid;C[a+16>>2]=b.gf;C[a+20>>2]=b.ce;D[a+24>>3]=BigInt(b.size);B[a+32>>2]=4096;B[a+36>>2]=b.xe;var c=b.Ld.getTime(),d=b.Dd.getTime(),e=b.Cd.getTime();D[a+40>>3]=BigInt(Math.floor(c/1E3));C[a+48>>2]=c%1E3*1E6;D[a+56>>3]=BigInt(Math.floor(d/1E3));C[a+64>>2]=d%1E3*1E6;D[a+72>>3]=BigInt(Math.floor(e/1E3));C[a+80>>2]=e%1E3*1E6;D[a+88>>3]=BigInt(b.jf);return 0}
var Vb=void 0,Wb=()=>{var a=B[+Vb>>2];Vb+=4;return a},Xb={},Yb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Zb(a){return this.td(C[a>>2])}
var $b={},ac={},bc={},cc=class extends Error{constructor(a){super(a);this.name="InternalError"}},O=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new cc("Mismatched type converter count");for(var k=0;k<a.length;++k)N(a[k],h[k])}a.forEach(h=>bc[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())ac.hasOwnProperty(k)?e[h]=ac[k]:(f.push(k),$b.hasOwnProperty(k)||($b[k]=[]),$b[k].push(()=>{e[h]=ac[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},P=a=>{for(var b="";;){var c=v[a++];
if(!c)return b;b+=String.fromCharCode(c)}},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},dc=a=>{throw new Q(a);};function ec(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(ac.hasOwnProperty(a)){if(c.hf)return;throw new Q(`Cannot register type '${d}' twice`);}ac[a]=b;delete bc[a];$b.hasOwnProperty(a)&&(b=$b[a],delete $b[a],b.forEach(e=>e()))}function N(a,b,c={}){return ec(a,b,c)}
var fc=(a,b,c)=>{switch(b){case 1:return c?d=>u[d]:d=>v[d];case 2:return c?d=>w[d>>1]:d=>y[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];case 8:return c?d=>D[d>>3]:d=>pa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},gc=a=>{throw new Q(a.md.vd.rd.name+" instance already deleted");},hc=!1,ic=!1,jc=()=>{},kc=a=>{if(hc)return kc=b=>b.deleteLater(),kc(a);if(!globalThis.FinalizationRegistry)return kc=b=>b,a;ic=new FinalizationRegistry(b=>{b=b.md;--b.count.value;0===b.count.value&&
(b.zd?b.Fd.Kd(b.zd):b.vd.rd.Kd(b.pd))});kc=b=>{var c=b.md;c.zd&&ic.register(b,{md:c},b);return b};jc=b=>{ic.unregister(b)};return kc(a)},lc=[],mc=()=>{for(;lc.length;){var a=lc.pop();a.md.Ud=!1;a["delete"]()}},nc;function oc(){}
var pc=(a,b)=>Object.defineProperty(b,"name",{value:a}),qc={},rc=(a,b,c)=>{if(void 0===a[b].wd){var d=a[b];a[b]=function(...e){if(!a[b].wd.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].wd})!`);return a[b].wd[e.length].apply(this,e)};a[b].wd=[];a[b].wd[d.Sd]=d}},sc=(a,b,c)=>{if(p.hasOwnProperty(a)){if(void 0===c||void 0!==p[a].wd&&void 0!==p[a].wd[c])throw new Q(`Cannot register public name '${a}' twice`);rc(p,
a,a);if(p[a].wd.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);p[a].wd[c]=b}else p[a]=b,p[a].Sd=c},tc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function uc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Rd=c;this.Kd=d;this.Bd=e;this.af=f;this.ee=g;this.Xe=h;this.xf=[]}
var vc=(a,b,c)=>{for(;b!==c;){if(!b.ee)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ee(a);b=b.Bd}return a},wc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function xc(a,b){if(null===b){if(this.qe)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.md)throw new Q(`Cannot pass "${wc(b)}" as a ${this.name}`);if(!b.md.pd)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return vc(b.md.pd,b.md.vd.rd,this.rd)}
function yc(a,b){if(null===b){if(this.qe)throw new Q(`null is not a valid ${this.name}`);if(this.ke){var c=this.ve();null!==a&&a.push(this.Kd,c);return c}return 0}if(!b||!b.md)throw new Q(`Cannot pass "${wc(b)}" as a ${this.name}`);if(!b.md.pd)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.je&&b.md.vd.je)throw new Q(`Cannot convert argument of type ${b.md.Fd?b.md.Fd.name:b.md.vd.name} to parameter type ${this.name}`);c=vc(b.md.pd,b.md.vd.rd,this.rd);if(this.ke){if(void 0===
b.md.zd)throw new Q("Passing raw pointer to smart pointer is illegal");switch(this.Df){case 0:if(b.md.Fd===this)c=b.md.zd;else throw new Q(`Cannot convert argument of type ${b.md.Fd?b.md.Fd.name:b.md.vd.name} to parameter type ${this.name}`);break;case 1:c=b.md.zd;break;case 2:if(b.md.Fd===this)c=b.md.zd;else{var d=b.clone();c=this.yf(c,R(()=>d["delete"]()));null!==a&&a.push(this.Kd,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function zc(a,b){if(null===b){if(this.qe)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.md)throw new Q(`Cannot pass "${wc(b)}" as a ${this.name}`);if(!b.md.pd)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.md.vd.je)throw new Q(`Cannot convert argument of type ${b.md.vd.name} to parameter type ${this.name}`);return vc(b.md.pd,b.md.vd.rd,this.rd)}
var Ac=(a,b,c)=>{if(b===c)return a;if(void 0===c.Bd)return null;a=Ac(a,b,c.Bd);return null===a?null:c.Xe(a)},Bc={},Cc=(a,b)=>{if(void 0===b)throw new Q("ptr should not be undefined");for(;a.Bd;)b=a.ee(b),a=a.Bd;return Bc[b]},Dc=(a,b)=>{if(!b.vd||!b.pd)throw new cc("makeClassHandle requires ptr and ptrType");if(!!b.Fd!==!!b.zd)throw new cc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return kc(Object.create(a,{md:{value:b,writable:!0}}))};
function Ec(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.rd=b;this.qe=c;this.je=d;this.ke=e;this.wf=f;this.Df=g;this.Ne=h;this.ve=k;this.yf=l;this.Kd=m;e||void 0!==b.Bd?this.yd=yc:(this.yd=d?xc:zc,this.Ad=null)}
var Fc=(a,b,c)=>{if(!p.hasOwnProperty(a))throw new cc("Replacing nonexistent public symbol");void 0!==p[a].wd&&void 0!==c?p[a].wd[c]=b:(p[a]=b,p[a].Sd=c)},Gc=[],S=a=>{var b=Gc[a];b||(Gc[a]=b=Hc.get(a));return b},T=(a,b)=>{a=P(a);var c=S(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class Ic extends Error{}
var Kc=a=>{a=Jc(a);var b=P(a);V(a);return b},Lc=(a,b)=>{function c(f){e[f]||ac[f]||(bc[f]?bc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ic(`${a}: `+d.map(Kc).join([", "]));};function Mc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Ad)return!0;return!1}
function Nc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Mc(b);c=!b[0].He;var l=b[0],m=b[1];d=[a,dc,d,e,Yb,l.td.bind(l),m?.yd.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.yd.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].Ad&&d.push(b[e].Ad);k=Mc(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");
m=`return function (${m}) {\n`;k&&(m+="var destructors = [];\n");var n=k?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${n}, this);\n`);for(g=0;g<e;++g){var x=`toArg${g}Wire`;m+=`var arg${g}Wired = ${x}(${n}, arg${g});\n`;r.push(x)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].Ad&&(m+=`${f}_dtor(${f});\n`,r.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(r,m+"}\n"))(...d);return pc(a,b)}
var Oc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},Pc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Qc=(a,b,c)=>{if(!(a instanceof Object))throw new Q(`${c} with invalid "this": ${a}`);if(!(a instanceof b.rd.constructor))throw new Q(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.md.pd)throw new Q(`cannot call emscripten binding method ${c} on deleted object`);return vc(a.md.pd,a.md.vd.rd,b.rd)},Rc=[],Sc=[0,1,,1,null,1,!0,1,!1,1],Uc=a=>
{9<a&&0===--Sc[a+1]&&(Sc[a]=void 0,Rc.push(a))},W=a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);return Sc[a]},R=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Rc.pop()||Sc.length;Sc[b]=a;Sc[b+1]=1;return b}},Vc={name:"emscripten::val",td:a=>{var b=W(a);Uc(a);return b},yd:(a,b)=>R(b),Ed:Zb,Ad:null},Wc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.td(u[d])}:function(d){return this.td(v[d])};case 2:return c?function(d){return this.td(w[d>>
1])}:function(d){return this.td(y[d>>1])};case 4:return c?function(d){return this.td(B[d>>2])}:function(d){return this.td(C[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xc=(a,b)=>{var c=ac[a];if(void 0===c)throw a=`${b} has unknown type ${Kc(a)}`,new Q(a);return c},Yc=(a,b)=>{switch(b){case 4:return function(c){return this.td(na[c>>2])};case 8:return function(c){return this.td(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Zc=Object.assign({optional:!0},
Vc),$c=new TextDecoder("utf-16le"),ad=(a,b,c)=>{a>>=1;return $c.decode(y.subarray(a,Sa(y,a,b/2,c)))},bd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)w[b>>1]=a.charCodeAt(e),b+=2;w[b>>1]=0;return b-d},cd=a=>2*a.length,dd=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=C[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ed=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
65535<f&&e++;B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},fd=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},gd=[],hd=a=>{var b=gd.length;gd.push(a);return b},jd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Xc(C[b+4*d>>2],`parameter ${d}`);return c},kd=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(C[b>>2]=R(d));return a},ld={},md=a=>{var b=ld[a];return void 0===b?P(a):b},nd=[0,31,60,91,121,152,182,213,244,274,305,335],od=[0,31,59,90,120,151,181,212,243,273,304,334],pd=
{},qd={},sd=()=>{if(!rd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in qd)void 0===qd[b]?delete a[b]:a[b]=qd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);rd=c}return rd},rd,td=[],ud=a=>{const b=a.length;return[b%128|128,b>>7,...a]},vd={i:127,p:127,j:126,f:125,d:124,e:111},wd=a=>ud(Array.from(a,b=>vd[b])),xd=[],yd,ka=a=>{var b=X(),c=zd(4),d=zd(4);
Ad(a,c,d);a=C[c>>2];d=C[d>>2];c=H(a);V(a);if(d){var e=H(d);V(d)}Y(b);return[c,e]};FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{Cb(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Xf=Cb;FS.Pd=Array(4096);FS.mount(J,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));ob(FS.makedev(5,0),qb);ob(FS.makedev(6,0),rb);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(fb(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.od={llseek:J.od.llseek};b.nd={Vd(c,d){c=+d;var e=M(c);c={parent:null,mount:{Ie:"fake"},nd:{readlink:()=>e.path},id:c+1};return c.parent=c},de(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.$e={MEMFS:J};
(()=>{let a=oc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof oc&&c instanceof oc))return!1;var d=this.md.vd.rd,e=this.md.pd;c.md=c.md;var f=c.md.vd.rd;for(c=c.md.pd;d.Bd;)e=d.ee(e),d=d.Bd;for(;f.Bd;)c=f.ee(c),f=f.Bd;return d===f&&e===c},clone:function(){this.md.pd||gc(this);if(this.md.be)return this.md.count.value+=1,this;var c=kc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.md;c=c(e.call(d,f,{md:{value:{count:g.count,Ud:g.Ud,be:g.be,pd:g.pd,vd:g.vd,zd:g.zd,Fd:g.Fd}}}));
c.md.count.value+=1;c.md.Ud=!1;return c},["delete"](){this.md.pd||gc(this);if(this.md.Ud&&!this.md.be)throw new Q("Object already scheduled for deletion");jc(this);var c=this.md;--c.count.value;0===c.count.value&&(c.zd?c.Fd.Kd(c.zd):c.vd.rd.Kd(c.pd));this.md.be||(this.md.zd=void 0,this.md.pd=void 0)},isDeleted:function(){return!this.md.pd},deleteLater:function(){this.md.pd||gc(this);if(this.md.Ud&&!this.md.be)throw new Q("Object already scheduled for deletion");lc.push(this);1===lc.length&&nc&&nc(mc);
this.md.Ud=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Ec.prototype,{cf(a){this.Ne&&(a=this.Ne(a));return a},Ae(a){this.Kd?.(a)},Ed:Zb,td:function(a){function b(){return this.ke?Dc(this.rd.Rd,{vd:this.wf,pd:c,Fd:this,zd:a}):Dc(this.rd.Rd,{vd:this,pd:a})}var c=this.cf(a);if(!c)return this.Ae(a),null;var d=Cc(this.rd,c);if(void 0!==d){if(0===d.md.count.value)return d.md.pd=c,d.md.zd=a,d.clone();d=d.clone();this.Ae(a);return d}d=this.rd.af(c);d=qc[d];if(!d)return b.call(this);d=this.je?d.Ve:d.pointerType;var e=Ac(c,this.rd,d.rd);return null===
e?b.call(this):this.ke?Dc(d.rd.Rd,{vd:d,pd:e,Fd:this,zd:a}):Dc(d.rd.Rd,{vd:d,pd:e})}});Qa.push(()=>{qd.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;qd.VIPS_CONCURRENCY=1});
xd.push(()=>{const a=Object.getOwnPropertyDescriptor(p.SourceCustom.prototype,"onRead");Object.defineProperty(p.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>R(c(d)))}});const b=Object.getOwnPropertyDescriptor(p.TargetCustom.prototype,"onWrite");Object.defineProperty(p.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(W(d)))}})});Object.assign(oc.prototype,{preventAutoDelete:function(){const a=lc.indexOf(this);-1<a&&lc.splice(a,1);this.md.Ud=!1;return this}});
p.preloadPlugins&&(Ia=p.preloadPlugins);p.noExitRuntime&&(Ba=p.noExitRuntime);p.print&&(da=p.print);p.printErr&&(q=p.printErr);p.wasmBinary&&(ea=p.wasmBinary);p.thisProgram&&(aa=p.thisProgram);if(p.preInit)for("function"==typeof p.preInit&&(p.preInit=[p.preInit]);0<p.preInit.length;)p.preInit.shift()();p.ENV=qd;p.addRunDependency=Ab;p.removeRunDependency=zb;
p.addFunction=(a,b)=>{if(!yd){yd=new WeakMap;var c=Hc.length;if(yd)for(var d=0;d<0+c;d++){var e=S(d);e&&yd.set(e,d)}}if(c=yd.get(a)||0)return c;c=td.length?td.pop():Hc.grow(1);try{Hc.set(c,a),Gc[c]=Hc.get(c)}catch(f){if(!(f instanceof TypeError))throw f;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...ud([1,96,...wd(b.slice(1)),...wd("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;Hc.set(c,b);Gc[c]=Hc.get(c)}yd.set(a,
c);return c};p.FS_preloadFile=Cb;p.FS_unlink=(...a)=>FS.unlink(...a);p.FS_createPath=(...a)=>FS.createPath(...a);p.FS_createDevice=(...a)=>FS.createDevice(...a);p.FS=FS;p.FS_createDataFile=(...a)=>FS.createDataFile(...a);p.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);p.setAutoDeleteLater=a=>{hc=a};p.deletionQueue=lc;p.setDelayFunction=a=>{nc=a;lc.length&&nc&&nc(mc)};p.incrementExceptionRefcount=a=>Bd(a);p.decrementExceptionRefcount=a=>Cd(a);p.getExceptionMessage=a=>ka(a);
function Dd(a){for(var b=y[a+6>>1];13===b&&!(16<C[a>>2]);){var c=C[a+8>>2],d=C[c>>2];if(0===d){b=0;break}else if(0===C[(c>>2)+1])a=d,b=y[d+6>>1];else break}return[a,b]}
var Ed,Fd,V,Ea,Cd,Bd,Jc,Da,sb,Gd,Z,Xa,Y,zd,X,Ad,Ya,Hd,ta,Hc,Ff={l:(a,b,c,d)=>G(`Assertion failed: ${H(a)}, at: `+[b?H(b):"unknown filename",c,d?H(d):"unknown function"]),I:a=>{var b=new Wa(a);0==u[b.pd+12]&&(u[b.pd+12]=1,Ua--);u[b.pd+13]=0;Ta.push(b);Bd(a);return Hd(a)},U:()=>{Z(0,0);var a=Ta.pop();Cd(a.ge);Va=0},a:()=>Za([]),i:a=>Za([a]),xc:()=>{var a=Ta.pop();a||G("no exception to throw");var b=a.ge;0==u[a.pd+13]&&(Ta.push(a),u[a.pd+13]=1,u[a.pd+12]=0,Ua++);Va=new ja(b);throw Va;},N:(a,b,c)=>{(new Wa(a)).init(b,
c);Va=new ja(a);Ua++;throw Va;},hb:()=>Ua,e:a=>{Va||=new ja(a);throw Va;},hc:function(a){try{var b=M(a);return Lb(b).Md}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.sd}},kc:function(a,b,c){try{b=H(b);b=Tb(a,b);if(c&-8)return-28;var d=FS.lookupPath(b,{follow:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Db(d,a)?-2:0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.sd}},eb:function(a,b,c){Vb=c;try{var d=M(a);
switch(b){case 0:var e=Wb();if(0>e)break;for(;FS.streams[e];)e++;return Lb(d,e).Md;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Wb(),d.flags|=e,0;case 12:return e=Wb(),w[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.sd}},gc:function(a,b){try{var c=M(a),d=c.node,e=c.od.Gd;a=e?c:d;e??=d.nd.Gd;Jb(e,63);var f=e(a);return Ub(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.sd}},cc:function(a,
b){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.sd}},bc:function(a,b){try{if(0===b)return-28;var c=FS.cwd(),d=kb(c)+1;if(b<d)return-68;lb(c,v,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.sd}},oc:function(a,b,c){Vb=c;try{var d=M(a);switch(b){case 21509:return d.ud?0:-59;case 21505:if(!d.ud)return-59;if(d.ud.Qd.kf){a=[3,
28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Wb();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)u[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.ud?0:-59;case 21506:case 21507:case 21508:if(!d.ud)return-59;if(d.ud.Qd.lf)for(e=Wb(),a=[],f=0;32>f;f++)a.push(u[e+f+17]);return 0;case 21519:if(!d.ud)return-59;e=Wb();return B[e>>2]=0;case 21520:return d.ud?-28:-59;case 21537:case 21531:return e=Wb(),FS.pe(d,b,e);case 21523:if(!d.ud)return-59;
d.ud.Qd.mf&&(f=[24,80],e=Wb(),w[e>>1]=f[0],w[e+2>>1]=f[1]);return 0;case 21524:return d.ud?0:-59;case 21515:return d.ud?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.sd}},ec:function(a,b){try{return a=H(a),Ub(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.sd}},dc:function(a,b,c,d){try{b=H(b);var e=d&256;b=Tb(a,b,d&4096);return Ub(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==
f.name)throw f;return-f.sd}},Fa:function(a,b,c,d){Vb=d;try{b=H(b);b=Tb(a,b);var e=d?Wb():0;return FS.open(b,c,e).Md}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.sd}},Ub:function(a){try{return a=H(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.sd}},fc:function(a,b){try{return a=H(a),Ub(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.sd}},bb:function(a,b,c){try{b=H(b);b=Tb(a,b);if(c)if(512===
c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.sd}},lc:()=>G(""),Fb:a=>{var b=Xb[a];delete Xb[a];var c=b.ve,d=b.Kd,e=b.Ee,f=e.map(g=>g.ff).concat(e.map(g=>g.Bf));O([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){const m=g[k],n=l.Zd,r=l.ef,x=g[k+e.length],z=l.Af,A=l.Cf;h[l.Ze]={read:E=>m.td(n(r,E)),write:(E,I)=>{var F=[];z(A,E,x.yd(F,I));Yb(F)},optional:m.optional}}return[{name:b.name,td:m=>{var n={},r;for(r in h)n[r]=
h[r].read(m);d(m);return n},yd:(m,n)=>{for(var r in h)if(!(r in n||h[r].optional))throw new TypeError(`Missing field: "${r}"`);var x=c();for(r in h)h[r].write(x,n[r]);null!==m&&m.push(d,x);return x},Ed:Zb,Ad:d}]})},Ra:(a,b,c,d,e)=>{b=P(b);if(d)a:switch(c){case 4:d=na;break a;case 8:d=oa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?u:v;break a;case 2:d=e?w:y;break a;case 4:d=e?B:C;break a;case 8:d=e?D:pa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);
}var f=d,g=Math.log2(c);N(a,{name:b,td:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+C[h>>2]));V(h);return k},yd:(h,k)=>{"number"==typeof k&&(k=[k]);if(!Array.isArray(k))throw new Q(`Cannot pass non-array to C++ vector type ${b}`);k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),n=Ed(m+l*c);m=n+m>>g;C[n>>2]=l;f.set(k,m);null!==h&&h.push(V,n);return n},Ed:Zb,Ad(h){V(h)}})},gb:(a,b,c,d,e)=>{b=P(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}N(a,
{name:b,td:f,yd:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},Ed:fc(b,c,!d),Ad:null})},uc:(a,b,c,d)=>{b=P(b);N(a,{name:b,td:function(e){return!!e},yd:function(e,f){return f?c:d},Ed:function(e){return this.td(v[e])},Ad:null})},Q:(a,b,c,d,e,f,g,h,k,l,m,n,r)=>{m=P(m);f=T(e,f);h&&=T(g,h);l&&=T(k,l);r=T(n,r);var x=tc(m);sc(x,function(){Lc(`Cannot construct ${m} due to unbound types`,[d])});O([a,b,c],d?[d]:[],z=>{z=z[0];if(d){var A=z.rd;var E=A.Rd}else E=oc.prototype;z=pc(m,function(...K){if(Object.getPrototypeOf(this)!==
I)throw new Q(`Use 'new' to construct ${m}`);if(void 0===F.Td)throw new Q(`${m} has no accessible constructor`);var Tc=F.Td[K.length];if(void 0===Tc)throw new Q(`Tried to invoke ctor of ${m} with invalid number of parameters (${K.length}) - expected (${Object.keys(F.Td).toString()}) parameters instead!`);return Tc.apply(this,K)});var I=Object.create(E,{constructor:{value:z}});z.prototype=I;var F=new uc(m,z,I,r,A,f,h,l);if(F.Bd){var U;(U=F.Bd).fe??(U.fe=[]);F.Bd.fe.push(F)}A=new Ec(m,F,!0,!1,!1);U=
new Ec(m+"*",F,!1,!1,!1);E=new Ec(m+" const*",F,!1,!0,!1);qc[a]={pointerType:U,Ve:E};Fc(x,z);return[A,U,E]})},p:(a,b,c,d,e,f,g,h)=>{var k=Oc(c,d);b=P(b);b=Pc(b);f=T(e,f);O([],[a],l=>{function m(){Lc(`Cannot call ${n} due to unbound types`,k)}l=l[0];var n=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=l.rd.constructor;void 0===r[b]?(m.Sd=c-1,r[b]=m):(rc(r,b,n),r[b].wd[c-1]=m);O([],k,x=>{x=Nc(n,[x[0],null].concat(x.slice(1)),null,f,g,h);void 0===r[b].wd?(x.Sd=c-1,r[b]=x):r[b].wd[c-
1]=x;if(l.rd.fe)for(const z of l.rd.fe)z.constructor.hasOwnProperty(b)||(z.constructor[b]=x);return[]});return[]})},S:(a,b,c,d,e,f)=>{var g=Oc(b,c);e=T(d,e);O([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.rd.Td&&(h.rd.Td=[]);if(void 0!==h.rd.Td[b-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.rd.Td[b-1]=()=>{Lc(`Cannot construct ${h.name} due to unbound types`,
g)};O([],g,l=>{l.splice(1,0,null);h.rd.Td[b-1]=Nc(k,l,null,e,f);return[]});return[]})},n:(a,b,c,d,e,f,g,h,k)=>{var l=Oc(c,d);b=P(b);b=Pc(b);f=T(e,f);O([],[a],m=>{function n(){Lc(`Cannot call ${r} due to unbound types`,l)}m=m[0];var r=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.rd.xf.push(b);var x=m.rd.Rd,z=x[b];void 0===z||void 0===z.wd&&z.className!==m.name&&z.Sd===c-2?(n.Sd=c-2,n.className=m.name,x[b]=n):(rc(x,b,r),x[b].wd[c-2]=n);O([],l,A=>{A=Nc(r,A,m,f,g,k);void 0===x[b].wd?
(A.Sd=c-2,x[b]=A):x[b].wd[c-2]=A;return[]});return[]})},F:(a,b,c,d,e,f,g,h,k,l)=>{b=P(b);e=T(d,e);O([],[a],m=>{m=m[0];var n=`${m.name}.${b}`,r={get(){Lc(`Cannot access ${n} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};r.set=k?()=>Lc(`Cannot access ${n} due to unbound types`,[c,g]):()=>{throw new Q(n+" is a read-only property");};Object.defineProperty(m.rd.Rd,b,r);O([],k?[c,g]:[c],x=>{var z=x[0],A={get(){var I=Qc(this,m,n+" getter");return z.td(e(f,I))},enumerable:!0};if(k){k=T(h,k);
var E=x[1];A.set=function(I){var F=Qc(this,m,n+" setter"),U=[];k(l,F,E.yd(U,I));Yb(U)}}Object.defineProperty(m.rd.Rd,b,A);return[]});return[]})},sc:a=>N(a,Vc),x:(a,b,c,d)=>{function e(){}b=P(b);e.values={};N(a,{name:b,constructor:e,td:function(f){return this.constructor.values[f]},yd:(f,g)=>g.value,Ed:Wc(b,c,d),Ad:null});sc(b,e)},o:(a,b,c)=>{var d=Xc(a,"enum");b=P(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:pc(`${d.name}_${b}`,function(){})}});a.values[c]=
d;a[b]=d},fb:(a,b,c)=>{b=P(b);N(a,{name:b,td:d=>d,yd:(d,e)=>e,Ed:Yc(b,c),Ad:null})},Y:(a,b,c,d,e,f,g)=>{var h=Oc(b,c);a=P(a);a=Pc(a);e=T(d,e);sc(a,function(){Lc(`Cannot call ${a} due to unbound types`,h)},b-1);O([],h,k=>{Fc(a,Nc(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})},Z:(a,b,c,d,e)=>{b=P(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}N(a,{name:b,td:f,yd:(h,k)=>k,Ed:fc(b,c,0!==d),Ad:null})},G:(a,b,c)=>{function d(f){return new e(u.buffer,C[f+4>>2],C[f>>2])}var e=[Int8Array,
Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=P(c);N(a,{name:c,td:d,Ed:d},{hf:!0})},Sa:a=>{N(a,Zc)},tc:(a,b)=>{b=P(b);N(a,{name:b,td(c){var d=H(c+4,C[c>>2],!0);V(c);return d},yd(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var f=e?kb(d):d.length;var g=Ed(4+f+1),h=g+4;C[g>>2]=f;e?lb(d,v,h,
f+1):v.set(d,h);null!==c&&c.push(V,g);return g},Ed:Zb,Ad(c){V(c)}})},Ga:(a,b,c)=>{c=P(c);if(2===b){var d=ad;var e=bd;var f=cd}else d=dd,e=ed,f=fd;N(a,{name:c,td:g=>{var h=d(g+4,C[g>>2]*b,!0);V(g);return h},yd:(g,h)=>{if("string"!=typeof h)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=Ed(4+k+b);C[l>>2]=k/b;e(h,l+4,k+b);null!==g&&g.push(V,l);return l},Ed:Zb,Ad(g){V(g)}})},Ta:(a,b,c,d,e,f)=>{Xb[a]={name:P(b),ve:T(c,d),Kd:T(e,f),Ee:[]}},Gb:(a,b,c,d,e,f,g,h,k,l)=>{Xb[a].Ee.push({Ze:P(b),
ff:c,Zd:T(d,e),ef:f,Bf:g,Af:T(h,k),Cf:l})},wc:(a,b)=>{b=P(b);N(a,{He:!0,name:b,td:()=>{},yd:()=>{}})},Vb:()=>{Ba=!1;Aa=0},Qb:()=>{throw new ia;},ic:(a,b)=>{a=W(a);b=W(b);a.set(b)},B:(a,b,c)=>{var [d,...e]=jd(a,b);b=d.yd.bind(d);var f=e.map(k=>k.Ed.bind(k));a--;var g={toValue:W};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=md,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;d.He||(g.toReturnWire=b,g.emval_returnValue=kd,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return hd(pc(h,c))},Eb:Uc,M:a=>{if(!a)return R(globalThis);a=md(a);return R(globalThis[a])},aa:a=>{a=md(a);return R(p[a])},yb:(a,b)=>{a=W(a);b=W(b);return R(a[b])},R:a=>{9<a&&(Sc[a+1]+=1)},vc:(a,
b)=>{a=W(a);b=W(b);return a instanceof b},A:(a,b,c,d,e)=>gd[a](b,c,d,e),ab:a=>{a=W(a);return"number"==typeof a},pa:a=>{a=W(a);return"string"==typeof a},J:a=>R(md(a)),Qa:a=>R(H(a)),Ac:a=>{var b=W(a);Yb(b);Uc(a)},Pb:(a,b,c)=>{a=W(a);b=W(b);c=W(c);a[b]=c},pc:a=>{a=W(a);return R(typeof a)},Yb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getUTCSeconds();B[b+4>>2]=a.getUTCMinutes();B[b+8>>2]=a.getUTCHours();B[b+12>>2]=a.getUTCDate();B[b+16>>2]=a.getUTCMonth();
B[b+20>>2]=a.getUTCFullYear()-1900;B[b+24>>2]=a.getUTCDay();B[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},Zb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=a.getFullYear();B[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?od:nd)[a.getMonth()]+a.getDate()-1|0;B[b+
36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Wb:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=M(d),k=FS.Wd(h,a,e,b,c),l=k.pd;B[f>>2]=k.we;C[g>>2]=l;return 0}catch(m){if("undefined"==typeof FS||"ErrnoError"!==m.name)throw m;return-m.sd}},Xb:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<
f?NaN:Number(f);try{var g=M(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.ld(43);d&2||FS.Yd(g,v.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.sd}},Rb:(a,b)=>{pd[a]&&(clearTimeout(pd[a].id),delete pd[a]);if(!b)return 0;var c=setTimeout(()=>{delete pd[a];Ga(()=>Gd(a,performance.now()))},b);pd[a]={id:c,Zf:b};return 0},nc:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();
C[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(lb(a,v,c,17),lb(b,v,d,17)):(lb(a,v,d,17),lb(b,v,c,17))},jc:function(a,b,c){if(!(0<=a&&3>=a))return 28;D[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},W:()=>Date.now(),$a:a=>q(H(a)),Ob:()=>{Aa+=1;throw"unwind";},Tb:()=>2147483648,Ea:()=>performance.now(),Sb:a=>{var b=v.length;a>>>=
0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},qc:(a,b)=>{var c=0,d=0,e;for(e of sd()){var f=b+c;C[a+d>>2]=f;c+=lb(e,v,f,Infinity)+1;d+=4}return 0},rc:(a,b)=>{var c=sd();C[a>>2]=c.length;a=0;for(var d of c)a+=kb(d)+1;C[b>>2]=a;return 0},T:Fa,qa:function(a){try{var b=M(a);FS.close(b);
return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.sd}},$b:function(a,b){try{var c=M(a),d=c.ud?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;u[b]=d;w[b+2>>1]=0;D[b+8>>3]=BigInt(0);D[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.sd}},db:function(a,b,c,d){try{a:{var e=M(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],k=C[a+4>>2];a+=8;var l=FS.read(e,u,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&
(f+=l)}m=b}C[d>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.sd}},_b:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=M(a);FS.llseek(e,b,c);D[d>>3]=BigInt(e.position);e.ne&&0===b&&0===c&&(e.ne=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.sd}},cb:function(a,b,c,d){try{a:{var e=M(a);a=b;for(var f,g=b=0;g<c;g++){var h=C[a>>2],k=C[a+4>>2];a+=8;var l=FS.write(e,
u,h,k,f);if(0>l){var m=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}m=b}C[d>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.sd}},ib:function(a,b,c,d){var e=C[(a>>2)+1],f=C[(a>>2)+6],g=C[(a>>2)+2],h=C[(a>>2)+5];a=Dd(C[(a>>2)+3])[1];var k=X(),l=k,m=[],n=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),n=!0;for(var r=0;r<f;r++){var x=C[(d>>2)+r],z=Dd(C[(g>>2)+r]),
A=z[0];z=z[1];switch(z){case 1:case 10:case 9:m.push(C[x>>2]);break;case 2:m.push(na[x>>2]);break;case 3:m.push(oa[x>>3]);break;case 5:m.push(v[x]);break;case 6:m.push(u[x]);break;case 7:m.push(y[x>>1]);break;case 8:m.push(w[x>>1]);break;case 11:case 12:m.push(pa[x>>3]);break;case 4:m.push(pa[x>>3]);m.push(pa[(x>>3)+1]);break;case 13:z=C[A>>2];A=y[A+4>>1];l-=z;l&=~(A-1);u.subarray(l,l+z).set(u.subarray(x,x+z));m.push(l);break;case 14:m.push(C[x>>2]);break;case 15:throw Error("complex marshalling nyi");
default:throw Error("Unexpected type "+z);}}if(h&1){h=[];for(r=e-1;r>=f;r--)switch(x=C[(d>>2)+r],z=Dd(C[(g>>2)+r]),A=z[0],z=z[1],z){case 5:case 6:--l;l&=-1;v[l]=v[x];break;case 7:case 8:l-=2;l&=-2;y[l>>1]=y[x>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;C[l>>2]=C[x>>2];break;case 3:case 11:case 12:l-=8;l&=-8;C[l>>2]=C[x>>2];C[(l>>2)+1]=C[(x>>2)+1];break;case 4:l-=16;l&=-8;C[l>>2]=C[x>>2];C[(l>>2)+1]=C[(x>>2)+1];C[(l>>2)+2]=C[(x>>2)+2];C[(l>>2)+3]=C[(x>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,
x,C[A>>2],y[A+4>>1]]);break;case 14:l-=4;l&=-4;C[l>>2]=C[x>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+z);}m.push(l);for(r=0;r<h.length;r++)e=h[r],d=e[0],x=e[1],z=e[2],A=e[3],l-=z,l&=~(A-1),u.subarray(l,l+z).set(u.subarray(x,x+z)),C[d>>2]=l}Y(l);zd(0);b=S(b).apply(null,m);Y(k);if(!n)switch(a){case 0:break;case 1:case 9:case 10:C[c>>2]=b;break;case 2:na[c>>2]=b;break;case 3:oa[c>>3]=b;break;case 5:case 6:v[c+0]=b;break;case 7:case 8:y[c>>1]=
b;break;case 11:case 12:pa[c>>3]=b;break;case 14:C[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}},sa:Id,oa:Jd,z:Kd,kb:Ld,nb:Md,C:Nd,ra:Od,xb:Pd,zb:Qd,jb:Rd,ua:Sd,H:Td,t:Ud,zc:Vd,yc:Wd,f:Xd,y:Yd,Va:Zd,Ka:$d,va:ae,h:be,w:ce,c:de,v:ee,Hb:fe,s:ge,Mb:he,vb:ie,E:je,ca:ke,Ua:le,$:me,Nb:ne,Lb:oe,Ib:pe,Kb:qe,Jb:re,u:se,Ha:te,V:ue,Ia:ve,qb:we,Xa:xe,ma:ye,k:ze,Db:Ae,ja:Be,Cb:Ce,b:De,sb:Ee,da:Fe,Da:Ge,lb:He,O:Ie,X:Je,ha:Ke,ob:Le,Na:Me,Oa:Ne,L:Oe,
wa:Pe,Bb:Qe,La:Re,g:Se,_a:Te,_:Ue,ya:Ve,ba:We,ub:Xe,ia:Ye,Ma:Ze,d:$e,Za:af,Ca:bf,na:cf,Aa:df,Ba:ef,tb:ff,wb:gf,Ja:hf,m:jf,j:kf,r:lf,rb:mf,q:nf,P:of,D:pf,K:qf,ka:rf,za:sf,Ya:tf,la:uf,Ab:vf,Wa:wf,fa:xf,Pa:yf,xa:zf,pb:Af,ta:Bf,ea:Cf,mb:Df,ga:Ef,mc:Ca,ac:function(a,b){try{return fb(v.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.sd}}};function De(a,b){var c=X();try{S(a)(b)}catch(d){Y(c);if(!(d instanceof t))throw d;Z(1,0)}}
function Se(a,b,c){var d=X();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function $e(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function ee(a,b,c,d,e){var f=X();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function jf(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}
function kf(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function de(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function me(a,b,c,d,e,f,g,h,k,l,m,n){var r=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m,n)}catch(x){Y(r);if(!(x instanceof t))throw x;Z(1,0)}}function of(a,b,c,d,e,f,g,h,k){var l=X();try{S(a)(b,c,d,e,f,g,h,k)}catch(m){Y(l);if(!(m instanceof t))throw m;Z(1,0)}}
function nf(a,b,c,d,e,f,g,h){var k=X();try{S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}function lf(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function zf(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function rf(a,b,c,d,e,f,g,h,k,l,m,n){var r=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n)}catch(x){Y(r);if(!(x instanceof t))throw x;Z(1,0)}}
function Ae(a,b,c,d,e,f,g,h,k,l,m,n){var r=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n)}catch(x){Y(r);if(!(x instanceof t))throw x;Z(1,0)}}function Ce(a,b,c,d,e,f,g,h){var k=X();try{S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}function Qe(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function Be(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}
function Oe(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function je(a,b,c,d,e,f,g){var h=X();try{return S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function vf(a,b,c,d,e,f,g,h,k,l,m,n,r,x,z,A,E,I,F){var U=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n,r,x,z,A,E,I,F)}catch(K){Y(U);if(!(K instanceof t))throw K;Z(1,0)}}function yf(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}
function Ye(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Ne(a,b,c,d,e,f,g,h,k){var l=X();try{S(a)(b,c,d,e,f,g,h,k)}catch(m){Y(l);if(!(m instanceof t))throw m;Z(1,0)}}function Me(a,b,c,d,e,f,g,h,k,l){var m=X();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(n){Y(m);if(!(n instanceof t))throw n;Z(1,0)}}function Qd(a,b,c,d,e,f,g,h,k,l,m,n,r){var x=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m,n,r)}catch(z){Y(x);if(!(z instanceof t))throw z;Z(1,0)}}
function Pd(a,b,c,d,e,f,g,h,k,l,m,n,r,x,z){var A=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m,n,r,x,z)}catch(E){Y(A);if(!(E instanceof t))throw E;Z(1,0)}}function Pe(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function gf(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function be(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}
function ze(a){var b=X();try{S(a)()}catch(c){Y(b);if(!(c instanceof t))throw c;Z(1,0)}}function qf(a,b,c,d,e,f,g,h,k,l,m){var n=X();try{S(a)(b,c,d,e,f,g,h,k,l,m)}catch(r){Y(n);if(!(r instanceof t))throw r;Z(1,0)}}function pf(a,b,c,d,e,f,g,h,k,l){var m=X();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(n){Y(m);if(!(n instanceof t))throw n;Z(1,0)}}function Ze(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}
function ae(a,b,c,d,e){var f=X();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function Re(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Xd(a,b){var c=X();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof t))throw d;Z(1,0)}}function $d(a,b,c,d,e,f,g){var h=X();try{return S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}
function Ie(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Ke(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function Nd(a,b,c,d,e,f,g){var h=X();try{return S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function se(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}
function ie(a,b,c,d,e,f,g,h,k,l,m){var n=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m)}catch(r){Y(n);if(!(r instanceof t))throw r;Z(1,0)}}function hf(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function Xe(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function ff(a,b,c,d,e,f,g,h,k,l,m){var n=X();try{S(a)(b,c,d,e,f,g,h,k,l,m)}catch(r){Y(n);if(!(r instanceof t))throw r;Z(1,0)}}
function Fe(a,b,c){var d=X();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function Td(a,b,c,d,e,f,g){var h=X();try{return S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function Ee(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function mf(a,b,c,d,e,f,g,h,k,l){var m=X();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(n){Y(m);if(!(n instanceof t))throw n;Z(1,0)}}
function ke(a,b,c,d,e,f,g,h){var k=X();try{return S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}function Sd(a,b,c,d,e){var f=X();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function we(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0);return 0n}}function Af(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}
function Le(a,b,c,d,e,f,g,h){var k=X();try{S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}function Je(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function Md(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function ve(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0);return 0n}}
function ue(a,b){var c=X();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof t))throw d;Z(1,0);return 0n}}function Df(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Bf(a,b,c){var d=X();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function te(a,b,c,d,e){var f=X();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}
function Ef(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function He(a,b,c){var d=X();try{S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function Id(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function Od(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}
function Ld(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Vd(a,b){var c=X();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof t))throw d;Z(1,0)}}function Rd(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Wd(a,b){var c=X();try{return S(a)(b)}catch(d){Y(c);if(!(d instanceof t))throw d;Z(1,0)}}function Ud(a){var b=X();try{return S(a)()}catch(c){Y(b);if(!(c instanceof t))throw c;Z(1,0)}}
function ge(a,b,c,d,e,f){var g=X();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function Kd(a,b,c,d,e,f){var g=X();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function Ue(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function ce(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}
function Te(a,b,c,d){var e=X();try{S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0)}}function Jd(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function Ge(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function cf(a,b,c,d,e,f,g,h){var k=X();try{S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}
function af(a,b,c,d,e,f,g,h,k,l){var m=X();try{S(a)(b,c,d,e,f,g,h,k,l)}catch(n){Y(m);if(!(n instanceof t))throw n;Z(1,0)}}function bf(a,b,c,d,e,f,g,h,k){var l=X();try{S(a)(b,c,d,e,f,g,h,k)}catch(m){Y(l);if(!(m instanceof t))throw m;Z(1,0)}}function ef(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function df(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}
function We(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function sf(a,b,c,d,e,f,g,h,k,l,m,n,r){var x=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n,r)}catch(z){Y(x);if(!(z instanceof t))throw z;Z(1,0)}}function tf(a,b,c,d,e,f,g,h,k,l,m,n,r,x){var z=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n,r,x)}catch(A){Y(z);if(!(A instanceof t))throw A;Z(1,0)}}function Ve(a,b,c,d,e,f){var g=X();try{S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}
function xe(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0);return 0n}}function ne(a,b,c,d,e,f,g,h,k,l,m,n,r){var x=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m,n,r)}catch(z){Y(x);if(!(z instanceof t))throw z;Z(1,0)}}function he(a,b,c,d,e,f,g,h){var k=X();try{return S(a)(b,c,d,e,f,g,h)}catch(l){Y(k);if(!(l instanceof t))throw l;Z(1,0)}}function Yd(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}
function ye(a,b,c,d){var e=X();try{return S(a)(b,c,d)}catch(f){Y(e);if(!(f instanceof t))throw f;Z(1,0);return 0n}}function wf(a,b,c,d,e,f,g,h,k,l,m){var n=X();try{S(a)(b,c,d,e,f,g,h,k,l,m)}catch(r){Y(n);if(!(r instanceof t))throw r;Z(1,0)}}function xf(a,b,c,d,e,f,g){var h=X();try{S(a)(b,c,d,e,f,g)}catch(k){Y(h);if(!(k instanceof t))throw k;Z(1,0)}}function Cf(a,b,c,d,e){var f=X();try{S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}
function oe(a,b,c,d,e,f,g,h,k,l,m,n,r,x,z,A,E){var I=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m,n,r,x,z,A,E)}catch(F){Y(I);if(!(F instanceof t))throw F;Z(1,0)}}function Zd(a,b,c){var d=X();try{return S(a)(b,c)}catch(e){Y(d);if(!(e instanceof t))throw e;Z(1,0)}}function qe(a,b,c,d,e){var f=X();try{return S(a)(b,c,d,e)}catch(g){Y(f);if(!(g instanceof t))throw g;Z(1,0)}}function re(a,b,c,d,e,f){var g=X();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}
function le(a,b,c,d,e,f,g,h,k,l,m){var n=X();try{return S(a)(b,c,d,e,f,g,h,k,l,m)}catch(r){Y(n);if(!(r instanceof t))throw r;Z(1,0)}}function pe(a,b,c,d,e,f){var g=X();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}function fe(a,b,c,d,e,f){var g=X();try{return S(a)(b,c,d,e,f)}catch(h){Y(g);if(!(h instanceof t))throw h;Z(1,0)}}
function uf(a,b,c,d,e,f,g,h,k,l,m,n,r,x,z,A){var E=X();try{S(a)(b,c,d,e,f,g,h,k,l,m,n,r,x,z,A)}catch(I){Y(E);if(!(I instanceof t))throw I;Z(1,0)}}
function Gf(){function a(){p.calledRun=!0;if(!fa){qa=!0;p.noFSInit||FS.oe||FS.init();Hf.Cc();Oa(xd);FS.Ge=!1;la?.(p);p.onRuntimeInitialized?.();if(!p.noInitialRun){var b=Fd;try{var c=b(0,0);Fa(c,!0)}catch(d){za(d)}}if(p.postRun)for("function"==typeof p.postRun&&(p.postRun=[p.postRun]);p.postRun.length;)b=p.postRun.shift(),Pa.push(b);Oa(Pa)}}if(0<xb)yb=Gf;else{if(p.preRun)for("function"==typeof p.preRun&&(p.preRun=[p.preRun]);p.preRun.length;)Qa.push(p.preRun.shift());Oa(Qa);0<xb?yb=Gf:p.setStatus?
(p.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>p.setStatus(""),1);a()},1)):a()}}var Hf;
Hf=await (async function(){function a(c){c=Hf=c.exports;Ed=c.Dc;Fd=p._main=c.Ec;V=c.Fc;Ea=c.Gc;p._calloc=c.Hc;Cd=c.Jc;Bd=c.Kc;Jc=c.Lc;p._emscripten_builtin_malloc=c.Mc;Da=c.Nc;p.___libc_calloc=c.Oc;p.___libc_free=c.Pc;p.___libc_malloc=c.Qc;p._emscripten_builtin_free=c.Rc;sb=c.Sc;Gd=c.Tc;p._strndup=c.Uc;p.__Znaj=c.Vc;p.__ZnajSt11align_val_t=c.Wc;p.__Znwj=c.Xc;p.__ZnwjSt11align_val_t=c.Yc;p.___libc_realloc=c.Zc;p._emscripten_builtin_calloc=c._c;p._emscripten_builtin_realloc=c.$c;p._malloc_size=
c.ad;p._malloc_usable_size=c.bd;p._reallocf=c.cd;Z=c.dd;Xa=c.ed;Y=c.fd;zd=c.gd;X=c.hd;Ad=c.id;Ya=c.jd;Hd=c.kd;ta=c.Bc;Hc=c.Ic;sa();return Hf}var b={a:Ff};if(p.instantiateWasm)return new Promise(c=>{p.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=p.locateFile?p.locateFile("vips.wasm",ba):ba+"vips.wasm";return a((await xa(b)).instance)}());Gf();qa?moduleRtn=p:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);
